// Structured address information from geocoding services.
// Contains location coordinates and hierarchical address components.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: models/address.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AddressLocationType represents the precision level of geocoded coordinates.
type AddressLocationType int32

const (
	// Default unspecified address location type.
	AddressLocationType_ADDRESS_LOCATION_TYPE_UNSPECIFIED AddressLocationType = 0
	// Precise location at rooftop level or exact point.
	AddressLocationType_ADDRESS_LOCATION_TYPE_ROOFTOP AddressLocationType = 1
	// Interpolated location between two precise points (e.g., street address).
	AddressLocationType_ADDRESS_LOCATION_TYPE_RANGE_INTERPOLATED AddressLocationType = 2
	// Geometric center of a result such as a polyline or polygon.
	AddressLocationType_ADDRESS_LOCATION_TYPE_GEOMETRIC_CENTER AddressLocationType = 3
	// Approximate location (e.g., postal code centroid).
	AddressLocationType_ADDRESS_LOCATION_TYPE_APPROXIMATE AddressLocationType = 4
)

// Enum value maps for AddressLocationType.
var (
	AddressLocationType_name = map[int32]string{
		0: "ADDRESS_LOCATION_TYPE_UNSPECIFIED",
		1: "ADDRESS_LOCATION_TYPE_ROOFTOP",
		2: "ADDRESS_LOCATION_TYPE_RANGE_INTERPOLATED",
		3: "ADDRESS_LOCATION_TYPE_GEOMETRIC_CENTER",
		4: "ADDRESS_LOCATION_TYPE_APPROXIMATE",
	}
	AddressLocationType_value = map[string]int32{
		"ADDRESS_LOCATION_TYPE_UNSPECIFIED":        0,
		"ADDRESS_LOCATION_TYPE_ROOFTOP":            1,
		"ADDRESS_LOCATION_TYPE_RANGE_INTERPOLATED": 2,
		"ADDRESS_LOCATION_TYPE_GEOMETRIC_CENTER":   3,
		"ADDRESS_LOCATION_TYPE_APPROXIMATE":        4,
	}
)

func (x AddressLocationType) Enum() *AddressLocationType {
	p := new(AddressLocationType)
	*p = x
	return p
}

func (x AddressLocationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AddressLocationType) Descriptor() protoreflect.EnumDescriptor {
	return file_models_address_proto_enumTypes[0].Descriptor()
}

func (AddressLocationType) Type() protoreflect.EnumType {
	return &file_models_address_proto_enumTypes[0]
}

func (x AddressLocationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AddressLocationType.Descriptor instead.
func (AddressLocationType) EnumDescriptor() ([]byte, []int) {
	return file_models_address_proto_rawDescGZIP(), []int{0}
}

// Address represents a geocoded physical location with structured components.
// Contains coordinates, administrative divisions, and address details.
// Next id: 19
type Address struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier for this address record (UUID v7).
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Latitude coordinate in decimal degrees.
	Latitude float64 `protobuf:"fixed64,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	// Longitude coordinate in decimal degrees.
	Longitude float64 `protobuf:"fixed64,3,opt,name=longitude,proto3" json:"longitude,omitempty"`
	// Human-readable formatted address string.
	FormattedAddress string `protobuf:"bytes,4,opt,name=formatted_address,json=formattedAddress,proto3" json:"formatted_address,omitempty"`
	// Full country name (e.g., "United States").
	Country string `protobuf:"bytes,5,opt,name=country,proto3" json:"country,omitempty"`
	// ISO 3166-1 alpha-2 country code (e.g., "US").
	CountryCode string `protobuf:"bytes,6,opt,name=country_code,json=countryCode,proto3" json:"country_code,omitempty"`
	// First-level administrative division (e.g., state, province).
	AdministrativeAreaLevel_1 string `protobuf:"bytes,7,opt,name=administrative_area_level_1,json=administrativeAreaLevel1,proto3" json:"administrative_area_level_1,omitempty"`
	// Second-level administrative division (e.g., county).
	AdministrativeAreaLevel_2 string `protobuf:"bytes,8,opt,name=administrative_area_level_2,json=administrativeAreaLevel2,proto3" json:"administrative_area_level_2,omitempty"`
	// City or town name.
	Locality string `protobuf:"bytes,9,opt,name=locality,proto3" json:"locality,omitempty"`
	// Neighborhood or district within a city.
	Sublocality string `protobuf:"bytes,10,opt,name=sublocality,proto3" json:"sublocality,omitempty"`
	// Postal or ZIP code.
	PostalCode string `protobuf:"bytes,11,opt,name=postal_code,json=postalCode,proto3" json:"postal_code,omitempty"`
	// Street number (e.g., "1600").
	StreetNumber string `protobuf:"bytes,12,opt,name=street_number,json=streetNumber,proto3" json:"street_number,omitempty"`
	// Street name (e.g., "Amphitheatre Parkway").
	Route string `protobuf:"bytes,13,opt,name=route,proto3" json:"route,omitempty"`
	// Building name or premise identifier.
	Premise string `protobuf:"bytes,14,opt,name=premise,proto3" json:"premise,omitempty"`
	// Geocoding service's unique identifier for this location.
	PlaceId string `protobuf:"bytes,15,opt,name=place_id,json=placeId,proto3" json:"place_id,omitempty"`
	// Precision level of the geocoded coordinates.
	LocationType AddressLocationType `protobuf:"varint,16,opt,name=location_type,json=locationType,proto3,enum=parrygg.models.AddressLocationType" json:"location_type,omitempty"`
	// When this address record was created.
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,17,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// When this address record was last updated.
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,18,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Address) Reset() {
	*x = Address{}
	mi := &file_models_address_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_models_address_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_models_address_proto_rawDescGZIP(), []int{0}
}

func (x *Address) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Address) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Address) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *Address) GetFormattedAddress() string {
	if x != nil {
		return x.FormattedAddress
	}
	return ""
}

func (x *Address) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *Address) GetCountryCode() string {
	if x != nil {
		return x.CountryCode
	}
	return ""
}

func (x *Address) GetAdministrativeAreaLevel_1() string {
	if x != nil {
		return x.AdministrativeAreaLevel_1
	}
	return ""
}

func (x *Address) GetAdministrativeAreaLevel_2() string {
	if x != nil {
		return x.AdministrativeAreaLevel_2
	}
	return ""
}

func (x *Address) GetLocality() string {
	if x != nil {
		return x.Locality
	}
	return ""
}

func (x *Address) GetSublocality() string {
	if x != nil {
		return x.Sublocality
	}
	return ""
}

func (x *Address) GetPostalCode() string {
	if x != nil {
		return x.PostalCode
	}
	return ""
}

func (x *Address) GetStreetNumber() string {
	if x != nil {
		return x.StreetNumber
	}
	return ""
}

func (x *Address) GetRoute() string {
	if x != nil {
		return x.Route
	}
	return ""
}

func (x *Address) GetPremise() string {
	if x != nil {
		return x.Premise
	}
	return ""
}

func (x *Address) GetPlaceId() string {
	if x != nil {
		return x.PlaceId
	}
	return ""
}

func (x *Address) GetLocationType() AddressLocationType {
	if x != nil {
		return x.LocationType
	}
	return AddressLocationType_ADDRESS_LOCATION_TYPE_UNSPECIFIED
}

func (x *Address) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Address) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_models_address_proto protoreflect.FileDescriptor

const file_models_address_proto_rawDesc = "" +
	"\n" +
	"\x14models/address.proto\x12\x0eparrygg.models\x1a\x1fgoogle/protobuf/timestamp.proto\"\xca\x05\n" +
	"\aAddress\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\blatitude\x18\x02 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x03 \x01(\x01R\tlongitude\x12+\n" +
	"\x11formatted_address\x18\x04 \x01(\tR\x10formattedAddress\x12\x18\n" +
	"\acountry\x18\x05 \x01(\tR\acountry\x12!\n" +
	"\fcountry_code\x18\x06 \x01(\tR\vcountryCode\x12=\n" +
	"\x1badministrative_area_level_1\x18\a \x01(\tR\x18administrativeAreaLevel1\x12=\n" +
	"\x1badministrative_area_level_2\x18\b \x01(\tR\x18administrativeAreaLevel2\x12\x1a\n" +
	"\blocality\x18\t \x01(\tR\blocality\x12 \n" +
	"\vsublocality\x18\n" +
	" \x01(\tR\vsublocality\x12\x1f\n" +
	"\vpostal_code\x18\v \x01(\tR\n" +
	"postalCode\x12#\n" +
	"\rstreet_number\x18\f \x01(\tR\fstreetNumber\x12\x14\n" +
	"\x05route\x18\r \x01(\tR\x05route\x12\x18\n" +
	"\apremise\x18\x0e \x01(\tR\apremise\x12\x19\n" +
	"\bplace_id\x18\x0f \x01(\tR\aplaceId\x12H\n" +
	"\rlocation_type\x18\x10 \x01(\x0e2#.parrygg.models.AddressLocationTypeR\flocationType\x129\n" +
	"\n" +
	"created_at\x18\x11 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x12 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt*\xe0\x01\n" +
	"\x13AddressLocationType\x12%\n" +
	"!ADDRESS_LOCATION_TYPE_UNSPECIFIED\x10\x00\x12!\n" +
	"\x1dADDRESS_LOCATION_TYPE_ROOFTOP\x10\x01\x12,\n" +
	"(ADDRESS_LOCATION_TYPE_RANGE_INTERPOLATED\x10\x02\x12*\n" +
	"&ADDRESS_LOCATION_TYPE_GEOMETRIC_CENTER\x10\x03\x12%\n" +
	"!ADDRESS_LOCATION_TYPE_APPROXIMATE\x10\x04BA\n" +
	"\x14gg.parry.grpc.modelsP\x01Z'github.com/AaronLieb/octagon/parrygg/pbb\x06proto3"

var (
	file_models_address_proto_rawDescOnce sync.Once
	file_models_address_proto_rawDescData []byte
)

func file_models_address_proto_rawDescGZIP() []byte {
	file_models_address_proto_rawDescOnce.Do(func() {
		file_models_address_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_models_address_proto_rawDesc), len(file_models_address_proto_rawDesc)))
	})
	return file_models_address_proto_rawDescData
}

var file_models_address_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_models_address_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_models_address_proto_goTypes = []any{
	(AddressLocationType)(0),      // 0: parrygg.models.AddressLocationType
	(*Address)(nil),               // 1: parrygg.models.Address
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_models_address_proto_depIdxs = []int32{
	0, // 0: parrygg.models.Address.location_type:type_name -> parrygg.models.AddressLocationType
	2, // 1: parrygg.models.Address.created_at:type_name -> google.protobuf.Timestamp
	2, // 2: parrygg.models.Address.updated_at:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_models_address_proto_init() }
func file_models_address_proto_init() {
	if File_models_address_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_models_address_proto_rawDesc), len(file_models_address_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_models_address_proto_goTypes,
		DependencyIndexes: file_models_address_proto_depIdxs,
		EnumInfos:         file_models_address_proto_enumTypes,
		MessageInfos:      file_models_address_proto_msgTypes,
	}.Build()
	File_models_address_proto = out.File
	file_models_address_proto_goTypes = nil
	file_models_address_proto_depIdxs = nil
}
