// Tournament bracket management service.
// Provides operations for bracket lifecycle, match progression, and results.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: services/bracket_service.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BracketService_GetBracket_FullMethodName           = "/parrygg.services.BracketService/GetBracket"
	BracketService_GetBracketTimestamp_FullMethodName  = "/parrygg.services.BracketService/GetBracketTimestamp"
	BracketService_ResetBracket_FullMethodName         = "/parrygg.services.BracketService/ResetBracket"
	BracketService_GetBracketPlacements_FullMethodName = "/parrygg.services.BracketService/GetBracketPlacements"
	BracketService_StartBracket_FullMethodName         = "/parrygg.services.BracketService/StartBracket"
)

// BracketServiceClient is the client API for BracketService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// BracketService provides tournament bracket management operations.
// Handles bracket lifecycle, match progression, and final results.
type BracketServiceClient interface {
	// Retrieve a bracket by ID or slug path.
	GetBracket(ctx context.Context, in *GetBracketRequest, opts ...grpc.CallOption) (*GetBracketResponse, error)
	// Get the last modification timestamp for a bracket.
	GetBracketTimestamp(ctx context.Context, in *GetBracketTimestampRequest, opts ...grpc.CallOption) (*GetBracketTimestampResponse, error)
	// Reset a bracket to initial state, clearing all matches.
	ResetBracket(ctx context.Context, in *ResetBracketRequest, opts ...grpc.CallOption) (*ResetBracketResponse, error)
	// Get final standings for a completed bracket.
	GetBracketPlacements(ctx context.Context, in *GetBracketPlacementsRequest, opts ...grpc.CallOption) (*GetBracketPlacementsResponse, error)
	// Start bracket competition and create initial matches.
	StartBracket(ctx context.Context, in *StartBracketRequest, opts ...grpc.CallOption) (*StartBracketResponse, error)
}

type bracketServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBracketServiceClient(cc grpc.ClientConnInterface) BracketServiceClient {
	return &bracketServiceClient{cc}
}

func (c *bracketServiceClient) GetBracket(ctx context.Context, in *GetBracketRequest, opts ...grpc.CallOption) (*GetBracketResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBracketResponse)
	err := c.cc.Invoke(ctx, BracketService_GetBracket_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bracketServiceClient) GetBracketTimestamp(ctx context.Context, in *GetBracketTimestampRequest, opts ...grpc.CallOption) (*GetBracketTimestampResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBracketTimestampResponse)
	err := c.cc.Invoke(ctx, BracketService_GetBracketTimestamp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bracketServiceClient) ResetBracket(ctx context.Context, in *ResetBracketRequest, opts ...grpc.CallOption) (*ResetBracketResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResetBracketResponse)
	err := c.cc.Invoke(ctx, BracketService_ResetBracket_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bracketServiceClient) GetBracketPlacements(ctx context.Context, in *GetBracketPlacementsRequest, opts ...grpc.CallOption) (*GetBracketPlacementsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBracketPlacementsResponse)
	err := c.cc.Invoke(ctx, BracketService_GetBracketPlacements_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bracketServiceClient) StartBracket(ctx context.Context, in *StartBracketRequest, opts ...grpc.CallOption) (*StartBracketResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartBracketResponse)
	err := c.cc.Invoke(ctx, BracketService_StartBracket_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BracketServiceServer is the server API for BracketService service.
// All implementations must embed UnimplementedBracketServiceServer
// for forward compatibility.
//
// BracketService provides tournament bracket management operations.
// Handles bracket lifecycle, match progression, and final results.
type BracketServiceServer interface {
	// Retrieve a bracket by ID or slug path.
	GetBracket(context.Context, *GetBracketRequest) (*GetBracketResponse, error)
	// Get the last modification timestamp for a bracket.
	GetBracketTimestamp(context.Context, *GetBracketTimestampRequest) (*GetBracketTimestampResponse, error)
	// Reset a bracket to initial state, clearing all matches.
	ResetBracket(context.Context, *ResetBracketRequest) (*ResetBracketResponse, error)
	// Get final standings for a completed bracket.
	GetBracketPlacements(context.Context, *GetBracketPlacementsRequest) (*GetBracketPlacementsResponse, error)
	// Start bracket competition and create initial matches.
	StartBracket(context.Context, *StartBracketRequest) (*StartBracketResponse, error)
	mustEmbedUnimplementedBracketServiceServer()
}

// UnimplementedBracketServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBracketServiceServer struct{}

func (UnimplementedBracketServiceServer) GetBracket(context.Context, *GetBracketRequest) (*GetBracketResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBracket not implemented")
}
func (UnimplementedBracketServiceServer) GetBracketTimestamp(context.Context, *GetBracketTimestampRequest) (*GetBracketTimestampResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBracketTimestamp not implemented")
}
func (UnimplementedBracketServiceServer) ResetBracket(context.Context, *ResetBracketRequest) (*ResetBracketResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResetBracket not implemented")
}
func (UnimplementedBracketServiceServer) GetBracketPlacements(context.Context, *GetBracketPlacementsRequest) (*GetBracketPlacementsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBracketPlacements not implemented")
}
func (UnimplementedBracketServiceServer) StartBracket(context.Context, *StartBracketRequest) (*StartBracketResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartBracket not implemented")
}
func (UnimplementedBracketServiceServer) mustEmbedUnimplementedBracketServiceServer() {}
func (UnimplementedBracketServiceServer) testEmbeddedByValue()                        {}

// UnsafeBracketServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BracketServiceServer will
// result in compilation errors.
type UnsafeBracketServiceServer interface {
	mustEmbedUnimplementedBracketServiceServer()
}

func RegisterBracketServiceServer(s grpc.ServiceRegistrar, srv BracketServiceServer) {
	// If the following call panics, it indicates UnimplementedBracketServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BracketService_ServiceDesc, srv)
}

func _BracketService_GetBracket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBracketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BracketServiceServer).GetBracket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BracketService_GetBracket_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BracketServiceServer).GetBracket(ctx, req.(*GetBracketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BracketService_GetBracketTimestamp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBracketTimestampRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BracketServiceServer).GetBracketTimestamp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BracketService_GetBracketTimestamp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BracketServiceServer).GetBracketTimestamp(ctx, req.(*GetBracketTimestampRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BracketService_ResetBracket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetBracketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BracketServiceServer).ResetBracket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BracketService_ResetBracket_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BracketServiceServer).ResetBracket(ctx, req.(*ResetBracketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BracketService_GetBracketPlacements_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBracketPlacementsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BracketServiceServer).GetBracketPlacements(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BracketService_GetBracketPlacements_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BracketServiceServer).GetBracketPlacements(ctx, req.(*GetBracketPlacementsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BracketService_StartBracket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartBracketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BracketServiceServer).StartBracket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BracketService_StartBracket_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BracketServiceServer).StartBracket(ctx, req.(*StartBracketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BracketService_ServiceDesc is the grpc.ServiceDesc for BracketService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BracketService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "parrygg.services.BracketService",
	HandlerType: (*BracketServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBracket",
			Handler:    _BracketService_GetBracket_Handler,
		},
		{
			MethodName: "GetBracketTimestamp",
			Handler:    _BracketService_GetBracketTimestamp_Handler,
		},
		{
			MethodName: "ResetBracket",
			Handler:    _BracketService_ResetBracket_Handler,
		},
		{
			MethodName: "GetBracketPlacements",
			Handler:    _BracketService_GetBracketPlacements_Handler,
		},
		{
			MethodName: "StartBracket",
			Handler:    _BracketService_StartBracket_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/bracket_service.proto",
}
