// Tournament entrant and participant management.
// Handles individual participants and teams registering for tournament events.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: models/entrant.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Entrant represents a participant in tournaments (individual or team).
// Groups one or more users together as a competitive unit.
type Entrant struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier for the entrant (UUID v7).
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Users that make up this entrant (1 for singles, 2+ for teams).
	Users         []*User `protobuf:"bytes,2,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entrant) Reset() {
	*x = Entrant{}
	mi := &file_models_entrant_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entrant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entrant) ProtoMessage() {}

func (x *Entrant) ProtoReflect() protoreflect.Message {
	mi := &file_models_entrant_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entrant.ProtoReflect.Descriptor instead.
func (*Entrant) Descriptor() ([]byte, []int) {
	return file_models_entrant_proto_rawDescGZIP(), []int{0}
}

func (x *Entrant) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Entrant) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

// EventEntrant represents an entrant's participation in a specific event.
// Links an entrant to an event with registration details and team requests.
type EventEntrant struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the event this entrant is registered for.
	EventId string `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	// The entrant information (users, etc.).
	Entrant *Entrant `protobuf:"bytes,2,opt,name=entrant,proto3" json:"entrant,omitempty"`
	// Display name for this entrant in the event.
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// Unique identifier for this event entrant registration (UUID v7).
	Id string `protobuf:"bytes,4,opt,name=id,proto3" json:"id,omitempty"`
	// Pending teammate requests for team formation.
	TeammateRequests []*TeammateRequest `protobuf:"bytes,5,rep,name=teammate_requests,json=teammateRequests,proto3" json:"teammate_requests,omitempty"`
	// This entrant's initial seed in the event.
	Seed          int32 `protobuf:"varint,6,opt,name=seed,proto3" json:"seed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventEntrant) Reset() {
	*x = EventEntrant{}
	mi := &file_models_entrant_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventEntrant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventEntrant) ProtoMessage() {}

func (x *EventEntrant) ProtoReflect() protoreflect.Message {
	mi := &file_models_entrant_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventEntrant.ProtoReflect.Descriptor instead.
func (*EventEntrant) Descriptor() ([]byte, []int) {
	return file_models_entrant_proto_rawDescGZIP(), []int{1}
}

func (x *EventEntrant) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *EventEntrant) GetEntrant() *Entrant {
	if x != nil {
		return x.Entrant
	}
	return nil
}

func (x *EventEntrant) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EventEntrant) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EventEntrant) GetTeammateRequests() []*TeammateRequest {
	if x != nil {
		return x.TeammateRequests
	}
	return nil
}

func (x *EventEntrant) GetSeed() int32 {
	if x != nil {
		return x.Seed
	}
	return 0
}

// EventEntrantMutation updates mutable fields of an event entrant.
// Subset of EventEntrant with fields that may be mutated by a request.
type EventEntrantMutation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Updated display name for the entrant.
	Name          *string `protobuf:"bytes,1,opt,name=name,proto3,oneof" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventEntrantMutation) Reset() {
	*x = EventEntrantMutation{}
	mi := &file_models_entrant_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventEntrantMutation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventEntrantMutation) ProtoMessage() {}

func (x *EventEntrantMutation) ProtoReflect() protoreflect.Message {
	mi := &file_models_entrant_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventEntrantMutation.ProtoReflect.Descriptor instead.
func (*EventEntrantMutation) Descriptor() ([]byte, []int) {
	return file_models_entrant_proto_rawDescGZIP(), []int{2}
}

func (x *EventEntrantMutation) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

// TeamMutation updates team composition and metadata.
type TeamMutation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Updated list of user IDs that make up the team.
	UserIds []string `protobuf:"bytes,1,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	// Updated team display name.
	Name          *string `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TeamMutation) Reset() {
	*x = TeamMutation{}
	mi := &file_models_entrant_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TeamMutation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeamMutation) ProtoMessage() {}

func (x *TeamMutation) ProtoReflect() protoreflect.Message {
	mi := &file_models_entrant_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeamMutation.ProtoReflect.Descriptor instead.
func (*TeamMutation) Descriptor() ([]byte, []int) {
	return file_models_entrant_proto_rawDescGZIP(), []int{3}
}

func (x *TeamMutation) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

func (x *TeamMutation) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

var File_models_entrant_proto protoreflect.FileDescriptor

const file_models_entrant_proto_rawDesc = "" +
	"\n" +
	"\x14models/entrant.proto\x12\x0eparrygg.models\x1a\x14models/request.proto\x1a\x11models/user.proto\"E\n" +
	"\aEntrant\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12*\n" +
	"\x05users\x18\x02 \x03(\v2\x14.parrygg.models.UserR\x05users\"\xe2\x01\n" +
	"\fEventEntrant\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x121\n" +
	"\aentrant\x18\x02 \x01(\v2\x17.parrygg.models.EntrantR\aentrant\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x0e\n" +
	"\x02id\x18\x04 \x01(\tR\x02id\x12L\n" +
	"\x11teammate_requests\x18\x05 \x03(\v2\x1f.parrygg.models.TeammateRequestR\x10teammateRequests\x12\x12\n" +
	"\x04seed\x18\x06 \x01(\x05R\x04seed\"8\n" +
	"\x14EventEntrantMutation\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tH\x00R\x04name\x88\x01\x01B\a\n" +
	"\x05_name\"K\n" +
	"\fTeamMutation\x12\x19\n" +
	"\buser_ids\x18\x01 \x03(\tR\auserIds\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01B\a\n" +
	"\x05_nameBA\n" +
	"\x14gg.parry.grpc.modelsP\x01Z'github.com/AaronLieb/octagon/parrygg/pbb\x06proto3"

var (
	file_models_entrant_proto_rawDescOnce sync.Once
	file_models_entrant_proto_rawDescData []byte
)

func file_models_entrant_proto_rawDescGZIP() []byte {
	file_models_entrant_proto_rawDescOnce.Do(func() {
		file_models_entrant_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_models_entrant_proto_rawDesc), len(file_models_entrant_proto_rawDesc)))
	})
	return file_models_entrant_proto_rawDescData
}

var file_models_entrant_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_models_entrant_proto_goTypes = []any{
	(*Entrant)(nil),              // 0: parrygg.models.Entrant
	(*EventEntrant)(nil),         // 1: parrygg.models.EventEntrant
	(*EventEntrantMutation)(nil), // 2: parrygg.models.EventEntrantMutation
	(*TeamMutation)(nil),         // 3: parrygg.models.TeamMutation
	(*User)(nil),                 // 4: parrygg.models.User
	(*TeammateRequest)(nil),      // 5: parrygg.models.TeammateRequest
}
var file_models_entrant_proto_depIdxs = []int32{
	4, // 0: parrygg.models.Entrant.users:type_name -> parrygg.models.User
	0, // 1: parrygg.models.EventEntrant.entrant:type_name -> parrygg.models.Entrant
	5, // 2: parrygg.models.EventEntrant.teammate_requests:type_name -> parrygg.models.TeammateRequest
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_models_entrant_proto_init() }
func file_models_entrant_proto_init() {
	if File_models_entrant_proto != nil {
		return
	}
	file_models_request_proto_init()
	file_models_user_proto_init()
	file_models_entrant_proto_msgTypes[2].OneofWrappers = []any{}
	file_models_entrant_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_models_entrant_proto_rawDesc), len(file_models_entrant_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_models_entrant_proto_goTypes,
		DependencyIndexes: file_models_entrant_proto_depIdxs,
		MessageInfos:      file_models_entrant_proto_msgTypes,
	}.Build()
	File_models_entrant_proto = out.File
	file_models_entrant_proto_goTypes = nil
	file_models_entrant_proto_depIdxs = nil
}
