// Tournament entrant and team management service.
// Provides operations for participant registration, team formation, and entrant lifecycle.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: services/entrant_service.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EntrantService_GetEventEntrant_FullMethodName        = "/parrygg.services.EntrantService/GetEventEntrant"
	EntrantService_CreateEventEntrant_FullMethodName     = "/parrygg.services.EntrantService/CreateEventEntrant"
	EntrantService_UpdateEventEntrant_FullMethodName     = "/parrygg.services.EntrantService/UpdateEventEntrant"
	EntrantService_DeleteEventEntrant_FullMethodName     = "/parrygg.services.EntrantService/DeleteEventEntrant"
	EntrantService_RemoveFromEventEntrant_FullMethodName = "/parrygg.services.EntrantService/RemoveFromEventEntrant"
	EntrantService_DisbandEventEntrant_FullMethodName    = "/parrygg.services.EntrantService/DisbandEventEntrant"
	EntrantService_CreateTeam_FullMethodName             = "/parrygg.services.EntrantService/CreateTeam"
	EntrantService_UpdateTeam_FullMethodName             = "/parrygg.services.EntrantService/UpdateTeam"
)

// EntrantServiceClient is the client API for EntrantService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EntrantServiceClient interface {
	GetEventEntrant(ctx context.Context, in *GetEventEntrantRequest, opts ...grpc.CallOption) (*GetEventEntrantResponse, error)
	CreateEventEntrant(ctx context.Context, in *CreateEventEntrantRequest, opts ...grpc.CallOption) (*CreateEventEntrantResponse, error)
	UpdateEventEntrant(ctx context.Context, in *UpdateEventEntrantRequest, opts ...grpc.CallOption) (*UpdateEventEntrantResponse, error)
	DeleteEventEntrant(ctx context.Context, in *DeleteEventEntrantRequest, opts ...grpc.CallOption) (*DeleteEventEntrantResponse, error)
	RemoveFromEventEntrant(ctx context.Context, in *RemoveFromEventEntrantRequest, opts ...grpc.CallOption) (*RemoveFromEventEntrantResponse, error)
	DisbandEventEntrant(ctx context.Context, in *DisbandEventEntrantRequest, opts ...grpc.CallOption) (*DisbandEventEntrantResponse, error)
	CreateTeam(ctx context.Context, in *CreateTeamRequest, opts ...grpc.CallOption) (*CreateTeamResponse, error)
	UpdateTeam(ctx context.Context, in *UpdateTeamRequest, opts ...grpc.CallOption) (*UpdateTeamResponse, error)
}

type entrantServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEntrantServiceClient(cc grpc.ClientConnInterface) EntrantServiceClient {
	return &entrantServiceClient{cc}
}

func (c *entrantServiceClient) GetEventEntrant(ctx context.Context, in *GetEventEntrantRequest, opts ...grpc.CallOption) (*GetEventEntrantResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEventEntrantResponse)
	err := c.cc.Invoke(ctx, EntrantService_GetEventEntrant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entrantServiceClient) CreateEventEntrant(ctx context.Context, in *CreateEventEntrantRequest, opts ...grpc.CallOption) (*CreateEventEntrantResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateEventEntrantResponse)
	err := c.cc.Invoke(ctx, EntrantService_CreateEventEntrant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entrantServiceClient) UpdateEventEntrant(ctx context.Context, in *UpdateEventEntrantRequest, opts ...grpc.CallOption) (*UpdateEventEntrantResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateEventEntrantResponse)
	err := c.cc.Invoke(ctx, EntrantService_UpdateEventEntrant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entrantServiceClient) DeleteEventEntrant(ctx context.Context, in *DeleteEventEntrantRequest, opts ...grpc.CallOption) (*DeleteEventEntrantResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteEventEntrantResponse)
	err := c.cc.Invoke(ctx, EntrantService_DeleteEventEntrant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entrantServiceClient) RemoveFromEventEntrant(ctx context.Context, in *RemoveFromEventEntrantRequest, opts ...grpc.CallOption) (*RemoveFromEventEntrantResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveFromEventEntrantResponse)
	err := c.cc.Invoke(ctx, EntrantService_RemoveFromEventEntrant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entrantServiceClient) DisbandEventEntrant(ctx context.Context, in *DisbandEventEntrantRequest, opts ...grpc.CallOption) (*DisbandEventEntrantResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DisbandEventEntrantResponse)
	err := c.cc.Invoke(ctx, EntrantService_DisbandEventEntrant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entrantServiceClient) CreateTeam(ctx context.Context, in *CreateTeamRequest, opts ...grpc.CallOption) (*CreateTeamResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateTeamResponse)
	err := c.cc.Invoke(ctx, EntrantService_CreateTeam_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entrantServiceClient) UpdateTeam(ctx context.Context, in *UpdateTeamRequest, opts ...grpc.CallOption) (*UpdateTeamResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateTeamResponse)
	err := c.cc.Invoke(ctx, EntrantService_UpdateTeam_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EntrantServiceServer is the server API for EntrantService service.
// All implementations must embed UnimplementedEntrantServiceServer
// for forward compatibility.
type EntrantServiceServer interface {
	GetEventEntrant(context.Context, *GetEventEntrantRequest) (*GetEventEntrantResponse, error)
	CreateEventEntrant(context.Context, *CreateEventEntrantRequest) (*CreateEventEntrantResponse, error)
	UpdateEventEntrant(context.Context, *UpdateEventEntrantRequest) (*UpdateEventEntrantResponse, error)
	DeleteEventEntrant(context.Context, *DeleteEventEntrantRequest) (*DeleteEventEntrantResponse, error)
	RemoveFromEventEntrant(context.Context, *RemoveFromEventEntrantRequest) (*RemoveFromEventEntrantResponse, error)
	DisbandEventEntrant(context.Context, *DisbandEventEntrantRequest) (*DisbandEventEntrantResponse, error)
	CreateTeam(context.Context, *CreateTeamRequest) (*CreateTeamResponse, error)
	UpdateTeam(context.Context, *UpdateTeamRequest) (*UpdateTeamResponse, error)
	mustEmbedUnimplementedEntrantServiceServer()
}

// UnimplementedEntrantServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEntrantServiceServer struct{}

func (UnimplementedEntrantServiceServer) GetEventEntrant(context.Context, *GetEventEntrantRequest) (*GetEventEntrantResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEventEntrant not implemented")
}
func (UnimplementedEntrantServiceServer) CreateEventEntrant(context.Context, *CreateEventEntrantRequest) (*CreateEventEntrantResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateEventEntrant not implemented")
}
func (UnimplementedEntrantServiceServer) UpdateEventEntrant(context.Context, *UpdateEventEntrantRequest) (*UpdateEventEntrantResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateEventEntrant not implemented")
}
func (UnimplementedEntrantServiceServer) DeleteEventEntrant(context.Context, *DeleteEventEntrantRequest) (*DeleteEventEntrantResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteEventEntrant not implemented")
}
func (UnimplementedEntrantServiceServer) RemoveFromEventEntrant(context.Context, *RemoveFromEventEntrantRequest) (*RemoveFromEventEntrantResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveFromEventEntrant not implemented")
}
func (UnimplementedEntrantServiceServer) DisbandEventEntrant(context.Context, *DisbandEventEntrantRequest) (*DisbandEventEntrantResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DisbandEventEntrant not implemented")
}
func (UnimplementedEntrantServiceServer) CreateTeam(context.Context, *CreateTeamRequest) (*CreateTeamResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTeam not implemented")
}
func (UnimplementedEntrantServiceServer) UpdateTeam(context.Context, *UpdateTeamRequest) (*UpdateTeamResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateTeam not implemented")
}
func (UnimplementedEntrantServiceServer) mustEmbedUnimplementedEntrantServiceServer() {}
func (UnimplementedEntrantServiceServer) testEmbeddedByValue()                        {}

// UnsafeEntrantServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EntrantServiceServer will
// result in compilation errors.
type UnsafeEntrantServiceServer interface {
	mustEmbedUnimplementedEntrantServiceServer()
}

func RegisterEntrantServiceServer(s grpc.ServiceRegistrar, srv EntrantServiceServer) {
	// If the following call panics, it indicates UnimplementedEntrantServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EntrantService_ServiceDesc, srv)
}

func _EntrantService_GetEventEntrant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEventEntrantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntrantServiceServer).GetEventEntrant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EntrantService_GetEventEntrant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntrantServiceServer).GetEventEntrant(ctx, req.(*GetEventEntrantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntrantService_CreateEventEntrant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateEventEntrantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntrantServiceServer).CreateEventEntrant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EntrantService_CreateEventEntrant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntrantServiceServer).CreateEventEntrant(ctx, req.(*CreateEventEntrantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntrantService_UpdateEventEntrant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateEventEntrantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntrantServiceServer).UpdateEventEntrant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EntrantService_UpdateEventEntrant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntrantServiceServer).UpdateEventEntrant(ctx, req.(*UpdateEventEntrantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntrantService_DeleteEventEntrant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteEventEntrantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntrantServiceServer).DeleteEventEntrant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EntrantService_DeleteEventEntrant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntrantServiceServer).DeleteEventEntrant(ctx, req.(*DeleteEventEntrantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntrantService_RemoveFromEventEntrant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveFromEventEntrantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntrantServiceServer).RemoveFromEventEntrant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EntrantService_RemoveFromEventEntrant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntrantServiceServer).RemoveFromEventEntrant(ctx, req.(*RemoveFromEventEntrantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntrantService_DisbandEventEntrant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisbandEventEntrantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntrantServiceServer).DisbandEventEntrant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EntrantService_DisbandEventEntrant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntrantServiceServer).DisbandEventEntrant(ctx, req.(*DisbandEventEntrantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntrantService_CreateTeam_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTeamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntrantServiceServer).CreateTeam(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EntrantService_CreateTeam_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntrantServiceServer).CreateTeam(ctx, req.(*CreateTeamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntrantService_UpdateTeam_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTeamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntrantServiceServer).UpdateTeam(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EntrantService_UpdateTeam_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntrantServiceServer).UpdateTeam(ctx, req.(*UpdateTeamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EntrantService_ServiceDesc is the grpc.ServiceDesc for EntrantService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EntrantService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "parrygg.services.EntrantService",
	HandlerType: (*EntrantServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetEventEntrant",
			Handler:    _EntrantService_GetEventEntrant_Handler,
		},
		{
			MethodName: "CreateEventEntrant",
			Handler:    _EntrantService_CreateEventEntrant_Handler,
		},
		{
			MethodName: "UpdateEventEntrant",
			Handler:    _EntrantService_UpdateEventEntrant_Handler,
		},
		{
			MethodName: "DeleteEventEntrant",
			Handler:    _EntrantService_DeleteEventEntrant_Handler,
		},
		{
			MethodName: "RemoveFromEventEntrant",
			Handler:    _EntrantService_RemoveFromEventEntrant_Handler,
		},
		{
			MethodName: "DisbandEventEntrant",
			Handler:    _EntrantService_DisbandEventEntrant_Handler,
		},
		{
			MethodName: "CreateTeam",
			Handler:    _EntrantService_CreateTeam_Handler,
		},
		{
			MethodName: "UpdateTeam",
			Handler:    _EntrantService_UpdateTeam_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/entrant_service.proto",
}
