// Event management service for tournament events.
// Provides CRUD operations, registration management, and event administration.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: services/event_service.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EventService_GetEvent_FullMethodName           = "/parrygg.services.EventService/GetEvent"
	EventService_GetEvents_FullMethodName          = "/parrygg.services.EventService/GetEvents"
	EventService_GetEventPlacements_FullMethodName = "/parrygg.services.EventService/GetEventPlacements"
	EventService_GetEventEntrants_FullMethodName   = "/parrygg.services.EventService/GetEventEntrants"
	EventService_ResetEvent_FullMethodName         = "/parrygg.services.EventService/ResetEvent"
	EventService_GetEntrantResult_FullMethodName   = "/parrygg.services.EventService/GetEntrantResult"
)

// EventServiceClient is the client API for EventService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// EventService provides tournament event management operations.
// Handles event lifecycle, registration, and bracket administration.
type EventServiceClient interface {
	// Retrieve a single event by ID.
	GetEvent(ctx context.Context, in *GetEventRequest, opts ...grpc.CallOption) (*GetEventResponse, error)
	// List events matching filter criteria.
	GetEvents(ctx context.Context, in *GetEventsRequest, opts ...grpc.CallOption) (*GetEventsResponse, error)
	// Get final standings for a completed event.
	GetEventPlacements(ctx context.Context, in *GetEventPlacementsRequest, opts ...grpc.CallOption) (*GetEventPlacementsResponse, error)
	// List all participants in an event.
	GetEventEntrants(ctx context.Context, in *GetEventEntrantsRequest, opts ...grpc.CallOption) (*GetEventEntrantsResponse, error)
	// Reset event brackets and matches to initial state.
	ResetEvent(ctx context.Context, in *ResetEventRequest, opts ...grpc.CallOption) (*ResetEventResponse, error)
	// Get detailed results information on a single entrant's performance within an event.
	GetEntrantResult(ctx context.Context, in *GetEntrantResultRequest, opts ...grpc.CallOption) (*GetEntrantResultResponse, error)
}

type eventServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEventServiceClient(cc grpc.ClientConnInterface) EventServiceClient {
	return &eventServiceClient{cc}
}

func (c *eventServiceClient) GetEvent(ctx context.Context, in *GetEventRequest, opts ...grpc.CallOption) (*GetEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEventResponse)
	err := c.cc.Invoke(ctx, EventService_GetEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) GetEvents(ctx context.Context, in *GetEventsRequest, opts ...grpc.CallOption) (*GetEventsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEventsResponse)
	err := c.cc.Invoke(ctx, EventService_GetEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) GetEventPlacements(ctx context.Context, in *GetEventPlacementsRequest, opts ...grpc.CallOption) (*GetEventPlacementsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEventPlacementsResponse)
	err := c.cc.Invoke(ctx, EventService_GetEventPlacements_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) GetEventEntrants(ctx context.Context, in *GetEventEntrantsRequest, opts ...grpc.CallOption) (*GetEventEntrantsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEventEntrantsResponse)
	err := c.cc.Invoke(ctx, EventService_GetEventEntrants_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) ResetEvent(ctx context.Context, in *ResetEventRequest, opts ...grpc.CallOption) (*ResetEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResetEventResponse)
	err := c.cc.Invoke(ctx, EventService_ResetEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) GetEntrantResult(ctx context.Context, in *GetEntrantResultRequest, opts ...grpc.CallOption) (*GetEntrantResultResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEntrantResultResponse)
	err := c.cc.Invoke(ctx, EventService_GetEntrantResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EventServiceServer is the server API for EventService service.
// All implementations must embed UnimplementedEventServiceServer
// for forward compatibility.
//
// EventService provides tournament event management operations.
// Handles event lifecycle, registration, and bracket administration.
type EventServiceServer interface {
	// Retrieve a single event by ID.
	GetEvent(context.Context, *GetEventRequest) (*GetEventResponse, error)
	// List events matching filter criteria.
	GetEvents(context.Context, *GetEventsRequest) (*GetEventsResponse, error)
	// Get final standings for a completed event.
	GetEventPlacements(context.Context, *GetEventPlacementsRequest) (*GetEventPlacementsResponse, error)
	// List all participants in an event.
	GetEventEntrants(context.Context, *GetEventEntrantsRequest) (*GetEventEntrantsResponse, error)
	// Reset event brackets and matches to initial state.
	ResetEvent(context.Context, *ResetEventRequest) (*ResetEventResponse, error)
	// Get detailed results information on a single entrant's performance within an event.
	GetEntrantResult(context.Context, *GetEntrantResultRequest) (*GetEntrantResultResponse, error)
	mustEmbedUnimplementedEventServiceServer()
}

// UnimplementedEventServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEventServiceServer struct{}

func (UnimplementedEventServiceServer) GetEvent(context.Context, *GetEventRequest) (*GetEventResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEvent not implemented")
}
func (UnimplementedEventServiceServer) GetEvents(context.Context, *GetEventsRequest) (*GetEventsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEvents not implemented")
}
func (UnimplementedEventServiceServer) GetEventPlacements(context.Context, *GetEventPlacementsRequest) (*GetEventPlacementsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEventPlacements not implemented")
}
func (UnimplementedEventServiceServer) GetEventEntrants(context.Context, *GetEventEntrantsRequest) (*GetEventEntrantsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEventEntrants not implemented")
}
func (UnimplementedEventServiceServer) ResetEvent(context.Context, *ResetEventRequest) (*ResetEventResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResetEvent not implemented")
}
func (UnimplementedEventServiceServer) GetEntrantResult(context.Context, *GetEntrantResultRequest) (*GetEntrantResultResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEntrantResult not implemented")
}
func (UnimplementedEventServiceServer) mustEmbedUnimplementedEventServiceServer() {}
func (UnimplementedEventServiceServer) testEmbeddedByValue()                      {}

// UnsafeEventServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EventServiceServer will
// result in compilation errors.
type UnsafeEventServiceServer interface {
	mustEmbedUnimplementedEventServiceServer()
}

func RegisterEventServiceServer(s grpc.ServiceRegistrar, srv EventServiceServer) {
	// If the following call panics, it indicates UnimplementedEventServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EventService_ServiceDesc, srv)
}

func _EventService_GetEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).GetEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_GetEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).GetEvent(ctx, req.(*GetEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_GetEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).GetEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_GetEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).GetEvents(ctx, req.(*GetEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_GetEventPlacements_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEventPlacementsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).GetEventPlacements(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_GetEventPlacements_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).GetEventPlacements(ctx, req.(*GetEventPlacementsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_GetEventEntrants_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEventEntrantsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).GetEventEntrants(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_GetEventEntrants_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).GetEventEntrants(ctx, req.(*GetEventEntrantsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_ResetEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).ResetEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_ResetEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).ResetEvent(ctx, req.(*ResetEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_GetEntrantResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEntrantResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).GetEntrantResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventService_GetEntrantResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).GetEntrantResult(ctx, req.(*GetEntrantResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EventService_ServiceDesc is the grpc.ServiceDesc for EventService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EventService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "parrygg.services.EventService",
	HandlerType: (*EventServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetEvent",
			Handler:    _EventService_GetEvent_Handler,
		},
		{
			MethodName: "GetEvents",
			Handler:    _EventService_GetEvents_Handler,
		},
		{
			MethodName: "GetEventPlacements",
			Handler:    _EventService_GetEventPlacements_Handler,
		},
		{
			MethodName: "GetEventEntrants",
			Handler:    _EventService_GetEventEntrants_Handler,
		},
		{
			MethodName: "ResetEvent",
			Handler:    _EventService_ResetEvent_Handler,
		},
		{
			MethodName: "GetEntrantResult",
			Handler:    _EventService_GetEntrantResult_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/event_service.proto",
}
