// Event management service for tournament events.
// Provides CRUD operations, registration management, and event administration.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: services/event_service.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventView int32

const (
	// Returns only the settings and identifiers for the event and its phases.
	EventView_EVENT_VIEW_SETTINGS_ONLY EventView = 0
	// Returns information about the event's phases, their brackets, and the seeds within + progressions between them.
	EventView_EVENT_VIEW_BRACKET_SUMMARY EventView = 1
)

// Enum value maps for EventView.
var (
	EventView_name = map[int32]string{
		0: "EVENT_VIEW_SETTINGS_ONLY",
		1: "EVENT_VIEW_BRACKET_SUMMARY",
	}
	EventView_value = map[string]int32{
		"EVENT_VIEW_SETTINGS_ONLY":   0,
		"EVENT_VIEW_BRACKET_SUMMARY": 1,
	}
)

func (x EventView) Enum() *EventView {
	p := new(EventView)
	*p = x
	return p
}

func (x EventView) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventView) Descriptor() protoreflect.EnumDescriptor {
	return file_services_event_service_proto_enumTypes[0].Descriptor()
}

func (EventView) Type() protoreflect.EnumType {
	return &file_services_event_service_proto_enumTypes[0]
}

func (x EventView) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventView.Descriptor instead.
func (EventView) EnumDescriptor() ([]byte, []int) {
	return file_services_event_service_proto_rawDescGZIP(), []int{0}
}

// GetEventRequest retrieves a single event by ID.
type GetEventRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier of the event to retrieve.
	Id            string           `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Identifier    *EventIdentifier `protobuf:"bytes,2,opt,name=identifier,proto3" json:"identifier,omitempty"`
	Options       *GetEventOptions `protobuf:"bytes,3,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventRequest) Reset() {
	*x = GetEventRequest{}
	mi := &file_services_event_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventRequest) ProtoMessage() {}

func (x *GetEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_event_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventRequest.ProtoReflect.Descriptor instead.
func (*GetEventRequest) Descriptor() ([]byte, []int) {
	return file_services_event_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetEventRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetEventRequest) GetIdentifier() *EventIdentifier {
	if x != nil {
		return x.Identifier
	}
	return nil
}

func (x *GetEventRequest) GetOptions() *GetEventOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

// GetEventResponse contains the requested event.
type GetEventResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The requested event.
	Event         *Event `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventResponse) Reset() {
	*x = GetEventResponse{}
	mi := &file_services_event_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventResponse) ProtoMessage() {}

func (x *GetEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_event_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventResponse.ProtoReflect.Descriptor instead.
func (*GetEventResponse) Descriptor() ([]byte, []int) {
	return file_services_event_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetEventResponse) GetEvent() *Event {
	if x != nil {
		return x.Event
	}
	return nil
}

// Options passed to GetEvent.
type GetEventOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Determines how much information should be returned about the event.
	EventView     EventView `protobuf:"varint,1,opt,name=event_view,json=eventView,proto3,enum=parrygg.services.EventView" json:"event_view,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventOptions) Reset() {
	*x = GetEventOptions{}
	mi := &file_services_event_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventOptions) ProtoMessage() {}

func (x *GetEventOptions) ProtoReflect() protoreflect.Message {
	mi := &file_services_event_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventOptions.ProtoReflect.Descriptor instead.
func (*GetEventOptions) Descriptor() ([]byte, []int) {
	return file_services_event_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetEventOptions) GetEventView() EventView {
	if x != nil {
		return x.EventView
	}
	return EventView_EVENT_VIEW_SETTINGS_ONLY
}

// GetEventsRequest retrieves multiple events based on filter criteria.
type GetEventsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Filter criteria for selecting events.
	Filter        *EventsFilter `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventsRequest) Reset() {
	*x = GetEventsRequest{}
	mi := &file_services_event_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventsRequest) ProtoMessage() {}

func (x *GetEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_event_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventsRequest.ProtoReflect.Descriptor instead.
func (*GetEventsRequest) Descriptor() ([]byte, []int) {
	return file_services_event_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetEventsRequest) GetFilter() *EventsFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

// GetEventsResponse contains the filtered list of events.
type GetEventsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Events matching the filter criteria.
	Events        []*Event `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventsResponse) Reset() {
	*x = GetEventsResponse{}
	mi := &file_services_event_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventsResponse) ProtoMessage() {}

func (x *GetEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_event_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventsResponse.ProtoReflect.Descriptor instead.
func (*GetEventsResponse) Descriptor() ([]byte, []int) {
	return file_services_event_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetEventsResponse) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

// ResetEventRequest clears all bracket and match data for an event.
type ResetEventRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the event to reset.
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetEventRequest) Reset() {
	*x = ResetEventRequest{}
	mi := &file_services_event_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetEventRequest) ProtoMessage() {}

func (x *ResetEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_event_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetEventRequest.ProtoReflect.Descriptor instead.
func (*ResetEventRequest) Descriptor() ([]byte, []int) {
	return file_services_event_service_proto_rawDescGZIP(), []int{5}
}

func (x *ResetEventRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// ResetEventResponse confirms the reset operation completed.
type ResetEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetEventResponse) Reset() {
	*x = ResetEventResponse{}
	mi := &file_services_event_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetEventResponse) ProtoMessage() {}

func (x *ResetEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_event_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetEventResponse.ProtoReflect.Descriptor instead.
func (*ResetEventResponse) Descriptor() ([]byte, []int) {
	return file_services_event_service_proto_rawDescGZIP(), []int{6}
}

// GetEventPlacementsRequest retrieves final standings for an event.
type GetEventPlacementsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Identifier:
	//
	//	*GetEventPlacementsRequest_Id
	//	*GetEventPlacementsRequest_EventSlugPath
	Identifier    isGetEventPlacementsRequest_Identifier `protobuf_oneof:"identifier"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventPlacementsRequest) Reset() {
	*x = GetEventPlacementsRequest{}
	mi := &file_services_event_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventPlacementsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventPlacementsRequest) ProtoMessage() {}

func (x *GetEventPlacementsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_event_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventPlacementsRequest.ProtoReflect.Descriptor instead.
func (*GetEventPlacementsRequest) Descriptor() ([]byte, []int) {
	return file_services_event_service_proto_rawDescGZIP(), []int{7}
}

func (x *GetEventPlacementsRequest) GetIdentifier() isGetEventPlacementsRequest_Identifier {
	if x != nil {
		return x.Identifier
	}
	return nil
}

func (x *GetEventPlacementsRequest) GetId() string {
	if x != nil {
		if x, ok := x.Identifier.(*GetEventPlacementsRequest_Id); ok {
			return x.Id
		}
	}
	return ""
}

func (x *GetEventPlacementsRequest) GetEventSlugPath() *EventSlugPath {
	if x != nil {
		if x, ok := x.Identifier.(*GetEventPlacementsRequest_EventSlugPath); ok {
			return x.EventSlugPath
		}
	}
	return nil
}

type isGetEventPlacementsRequest_Identifier interface {
	isGetEventPlacementsRequest_Identifier()
}

type GetEventPlacementsRequest_Id struct {
	// Direct event ID lookup.
	Id string `protobuf:"bytes,1,opt,name=id,proto3,oneof"`
}

type GetEventPlacementsRequest_EventSlugPath struct {
	// Slug-based path lookup.
	EventSlugPath *EventSlugPath `protobuf:"bytes,2,opt,name=event_slug_path,json=eventSlugPath,proto3,oneof"`
}

func (*GetEventPlacementsRequest_Id) isGetEventPlacementsRequest_Identifier() {}

func (*GetEventPlacementsRequest_EventSlugPath) isGetEventPlacementsRequest_Identifier() {}

// GetEventPlacementsResponse contains the final event standings.
type GetEventPlacementsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Final placements ordered by ranking.
	Placements    []*Placement `protobuf:"bytes,1,rep,name=placements,proto3" json:"placements,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventPlacementsResponse) Reset() {
	*x = GetEventPlacementsResponse{}
	mi := &file_services_event_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventPlacementsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventPlacementsResponse) ProtoMessage() {}

func (x *GetEventPlacementsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_event_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventPlacementsResponse.ProtoReflect.Descriptor instead.
func (*GetEventPlacementsResponse) Descriptor() ([]byte, []int) {
	return file_services_event_service_proto_rawDescGZIP(), []int{8}
}

func (x *GetEventPlacementsResponse) GetPlacements() []*Placement {
	if x != nil {
		return x.Placements
	}
	return nil
}

// GetEntrantResultRequest retrieves information about a particular entrant or user's performance within an event.
type GetEntrantResultRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	EventIdentifier *EventIdentifier       `protobuf:"bytes,1,opt,name=event_identifier,json=eventIdentifier,proto3" json:"event_identifier,omitempty"`
	// Types that are valid to be assigned to EntrantIdentifier:
	//
	//	*GetEntrantResultRequest_EntrantId
	//	*GetEntrantResultRequest_UserId
	EntrantIdentifier isGetEntrantResultRequest_EntrantIdentifier `protobuf_oneof:"entrant_identifier"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetEntrantResultRequest) Reset() {
	*x = GetEntrantResultRequest{}
	mi := &file_services_event_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEntrantResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEntrantResultRequest) ProtoMessage() {}

func (x *GetEntrantResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_event_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEntrantResultRequest.ProtoReflect.Descriptor instead.
func (*GetEntrantResultRequest) Descriptor() ([]byte, []int) {
	return file_services_event_service_proto_rawDescGZIP(), []int{9}
}

func (x *GetEntrantResultRequest) GetEventIdentifier() *EventIdentifier {
	if x != nil {
		return x.EventIdentifier
	}
	return nil
}

func (x *GetEntrantResultRequest) GetEntrantIdentifier() isGetEntrantResultRequest_EntrantIdentifier {
	if x != nil {
		return x.EntrantIdentifier
	}
	return nil
}

func (x *GetEntrantResultRequest) GetEntrantId() string {
	if x != nil {
		if x, ok := x.EntrantIdentifier.(*GetEntrantResultRequest_EntrantId); ok {
			return x.EntrantId
		}
	}
	return ""
}

func (x *GetEntrantResultRequest) GetUserId() string {
	if x != nil {
		if x, ok := x.EntrantIdentifier.(*GetEntrantResultRequest_UserId); ok {
			return x.UserId
		}
	}
	return ""
}

type isGetEntrantResultRequest_EntrantIdentifier interface {
	isGetEntrantResultRequest_EntrantIdentifier()
}

type GetEntrantResultRequest_EntrantId struct {
	EntrantId string `protobuf:"bytes,2,opt,name=entrant_id,json=entrantId,proto3,oneof"`
}

type GetEntrantResultRequest_UserId struct {
	UserId string `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3,oneof"`
}

func (*GetEntrantResultRequest_EntrantId) isGetEntrantResultRequest_EntrantIdentifier() {}

func (*GetEntrantResultRequest_UserId) isGetEntrantResultRequest_EntrantIdentifier() {}

// GetEntrantResultResponse contains the entrant's results.
type GetEntrantResultResponse struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Placement *Placement             `protobuf:"bytes,1,opt,name=placement,proto3" json:"placement,omitempty"`
	// The entrant's match results, organized by phase and bracket.
	Phases        []*Phase `protobuf:"bytes,2,rep,name=phases,proto3" json:"phases,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEntrantResultResponse) Reset() {
	*x = GetEntrantResultResponse{}
	mi := &file_services_event_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEntrantResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEntrantResultResponse) ProtoMessage() {}

func (x *GetEntrantResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_event_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEntrantResultResponse.ProtoReflect.Descriptor instead.
func (*GetEntrantResultResponse) Descriptor() ([]byte, []int) {
	return file_services_event_service_proto_rawDescGZIP(), []int{10}
}

func (x *GetEntrantResultResponse) GetPlacement() *Placement {
	if x != nil {
		return x.Placement
	}
	return nil
}

func (x *GetEntrantResultResponse) GetPhases() []*Phase {
	if x != nil {
		return x.Phases
	}
	return nil
}

// GetEventEntrantsRequest retrieves all participants in an event.
type GetEventEntrantsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Event to get entrants for.
	EventIdentifier *EventIdentifier `protobuf:"bytes,1,opt,name=event_identifier,json=eventIdentifier,proto3" json:"event_identifier,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetEventEntrantsRequest) Reset() {
	*x = GetEventEntrantsRequest{}
	mi := &file_services_event_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventEntrantsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventEntrantsRequest) ProtoMessage() {}

func (x *GetEventEntrantsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_event_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventEntrantsRequest.ProtoReflect.Descriptor instead.
func (*GetEventEntrantsRequest) Descriptor() ([]byte, []int) {
	return file_services_event_service_proto_rawDescGZIP(), []int{11}
}

func (x *GetEventEntrantsRequest) GetEventIdentifier() *EventIdentifier {
	if x != nil {
		return x.EventIdentifier
	}
	return nil
}

// GetEventEntrantsResponse contains all event participants.
type GetEventEntrantsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// All entrants registered for the event.
	EventEntrants []*EventEntrant `protobuf:"bytes,1,rep,name=event_entrants,json=eventEntrants,proto3" json:"event_entrants,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventEntrantsResponse) Reset() {
	*x = GetEventEntrantsResponse{}
	mi := &file_services_event_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventEntrantsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventEntrantsResponse) ProtoMessage() {}

func (x *GetEventEntrantsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_event_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventEntrantsResponse.ProtoReflect.Descriptor instead.
func (*GetEventEntrantsResponse) Descriptor() ([]byte, []int) {
	return file_services_event_service_proto_rawDescGZIP(), []int{12}
}

func (x *GetEventEntrantsResponse) GetEventEntrants() []*EventEntrant {
	if x != nil {
		return x.EventEntrants
	}
	return nil
}

var File_services_event_service_proto protoreflect.FileDescriptor

const file_services_event_service_proto_rawDesc = "" +
	"\n" +
	"\x1cservices/event_service.proto\x12\x10parrygg.services\x1a\x12models/event.proto\x1a\x16models/hierarchy.proto\x1a\x13models/filter.proto\x1a\x14models/entrant.proto\x1a\x12models/phase.proto\x1a\x14models/request.proto\x1a\x19models/event_export.proto\"\x9f\x01\n" +
	"\x0fGetEventRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12?\n" +
	"\n" +
	"identifier\x18\x02 \x01(\v2\x1f.parrygg.models.EventIdentifierR\n" +
	"identifier\x12;\n" +
	"\aoptions\x18\x03 \x01(\v2!.parrygg.services.GetEventOptionsR\aoptions\"?\n" +
	"\x10GetEventResponse\x12+\n" +
	"\x05event\x18\x01 \x01(\v2\x15.parrygg.models.EventR\x05event\"M\n" +
	"\x0fGetEventOptions\x12:\n" +
	"\n" +
	"event_view\x18\x01 \x01(\x0e2\x1b.parrygg.services.EventViewR\teventView\"H\n" +
	"\x10GetEventsRequest\x124\n" +
	"\x06filter\x18\x01 \x01(\v2\x1c.parrygg.models.EventsFilterR\x06filter\"B\n" +
	"\x11GetEventsResponse\x12-\n" +
	"\x06events\x18\x01 \x03(\v2\x15.parrygg.models.EventR\x06events\"#\n" +
	"\x11ResetEventRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x14\n" +
	"\x12ResetEventResponse\"\x84\x01\n" +
	"\x19GetEventPlacementsRequest\x12\x10\n" +
	"\x02id\x18\x01 \x01(\tH\x00R\x02id\x12G\n" +
	"\x0fevent_slug_path\x18\x02 \x01(\v2\x1d.parrygg.models.EventSlugPathH\x00R\reventSlugPathB\f\n" +
	"\n" +
	"identifier\"W\n" +
	"\x1aGetEventPlacementsResponse\x129\n" +
	"\n" +
	"placements\x18\x01 \x03(\v2\x19.parrygg.models.PlacementR\n" +
	"placements\"\xb7\x01\n" +
	"\x17GetEntrantResultRequest\x12J\n" +
	"\x10event_identifier\x18\x01 \x01(\v2\x1f.parrygg.models.EventIdentifierR\x0feventIdentifier\x12\x1f\n" +
	"\n" +
	"entrant_id\x18\x02 \x01(\tH\x00R\tentrantId\x12\x19\n" +
	"\auser_id\x18\x03 \x01(\tH\x00R\x06userIdB\x14\n" +
	"\x12entrant_identifier\"\x82\x01\n" +
	"\x18GetEntrantResultResponse\x127\n" +
	"\tplacement\x18\x01 \x01(\v2\x19.parrygg.models.PlacementR\tplacement\x12-\n" +
	"\x06phases\x18\x02 \x03(\v2\x15.parrygg.models.PhaseR\x06phases\"e\n" +
	"\x17GetEventEntrantsRequest\x12J\n" +
	"\x10event_identifier\x18\x01 \x01(\v2\x1f.parrygg.models.EventIdentifierR\x0feventIdentifier\"_\n" +
	"\x18GetEventEntrantsResponse\x12C\n" +
	"\x0eevent_entrants\x18\x01 \x03(\v2\x1c.parrygg.models.EventEntrantR\reventEntrants*I\n" +
	"\tEventView\x12\x1c\n" +
	"\x18EVENT_VIEW_SETTINGS_ONLY\x10\x00\x12\x1e\n" +
	"\x1aEVENT_VIEW_BRACKET_SUMMARY\x10\x012\xe3\x04\n" +
	"\fEventService\x12S\n" +
	"\bGetEvent\x12!.parrygg.services.GetEventRequest\x1a\".parrygg.services.GetEventResponse\"\x00\x12V\n" +
	"\tGetEvents\x12\".parrygg.services.GetEventsRequest\x1a#.parrygg.services.GetEventsResponse\"\x00\x12q\n" +
	"\x12GetEventPlacements\x12+.parrygg.services.GetEventPlacementsRequest\x1a,.parrygg.services.GetEventPlacementsResponse\"\x00\x12k\n" +
	"\x10GetEventEntrants\x12).parrygg.services.GetEventEntrantsRequest\x1a*.parrygg.services.GetEventEntrantsResponse\"\x00\x12Y\n" +
	"\n" +
	"ResetEvent\x12#.parrygg.services.ResetEventRequest\x1a$.parrygg.services.ResetEventResponse\"\x00\x12k\n" +
	"\x10GetEntrantResult\x12).parrygg.services.GetEntrantResultRequest\x1a*.parrygg.services.GetEntrantResultResponse\"\x00BC\n" +
	"\x16gg.parry.grpc.servicesP\x01Z'github.com/AaronLieb/octagon/parrygg/pbb\x06proto3"

var (
	file_services_event_service_proto_rawDescOnce sync.Once
	file_services_event_service_proto_rawDescData []byte
)

func file_services_event_service_proto_rawDescGZIP() []byte {
	file_services_event_service_proto_rawDescOnce.Do(func() {
		file_services_event_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_services_event_service_proto_rawDesc), len(file_services_event_service_proto_rawDesc)))
	})
	return file_services_event_service_proto_rawDescData
}

var file_services_event_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_services_event_service_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_services_event_service_proto_goTypes = []any{
	(EventView)(0),                     // 0: parrygg.services.EventView
	(*GetEventRequest)(nil),            // 1: parrygg.services.GetEventRequest
	(*GetEventResponse)(nil),           // 2: parrygg.services.GetEventResponse
	(*GetEventOptions)(nil),            // 3: parrygg.services.GetEventOptions
	(*GetEventsRequest)(nil),           // 4: parrygg.services.GetEventsRequest
	(*GetEventsResponse)(nil),          // 5: parrygg.services.GetEventsResponse
	(*ResetEventRequest)(nil),          // 6: parrygg.services.ResetEventRequest
	(*ResetEventResponse)(nil),         // 7: parrygg.services.ResetEventResponse
	(*GetEventPlacementsRequest)(nil),  // 8: parrygg.services.GetEventPlacementsRequest
	(*GetEventPlacementsResponse)(nil), // 9: parrygg.services.GetEventPlacementsResponse
	(*GetEntrantResultRequest)(nil),    // 10: parrygg.services.GetEntrantResultRequest
	(*GetEntrantResultResponse)(nil),   // 11: parrygg.services.GetEntrantResultResponse
	(*GetEventEntrantsRequest)(nil),    // 12: parrygg.services.GetEventEntrantsRequest
	(*GetEventEntrantsResponse)(nil),   // 13: parrygg.services.GetEventEntrantsResponse
	(*EventIdentifier)(nil),            // 14: parrygg.models.EventIdentifier
	(*Event)(nil),                      // 15: parrygg.models.Event
	(*EventsFilter)(nil),               // 16: parrygg.models.EventsFilter
	(*EventSlugPath)(nil),              // 17: parrygg.models.EventSlugPath
	(*Placement)(nil),                  // 18: parrygg.models.Placement
	(*Phase)(nil),                      // 19: parrygg.models.Phase
	(*EventEntrant)(nil),               // 20: parrygg.models.EventEntrant
}
var file_services_event_service_proto_depIdxs = []int32{
	14, // 0: parrygg.services.GetEventRequest.identifier:type_name -> parrygg.models.EventIdentifier
	3,  // 1: parrygg.services.GetEventRequest.options:type_name -> parrygg.services.GetEventOptions
	15, // 2: parrygg.services.GetEventResponse.event:type_name -> parrygg.models.Event
	0,  // 3: parrygg.services.GetEventOptions.event_view:type_name -> parrygg.services.EventView
	16, // 4: parrygg.services.GetEventsRequest.filter:type_name -> parrygg.models.EventsFilter
	15, // 5: parrygg.services.GetEventsResponse.events:type_name -> parrygg.models.Event
	17, // 6: parrygg.services.GetEventPlacementsRequest.event_slug_path:type_name -> parrygg.models.EventSlugPath
	18, // 7: parrygg.services.GetEventPlacementsResponse.placements:type_name -> parrygg.models.Placement
	14, // 8: parrygg.services.GetEntrantResultRequest.event_identifier:type_name -> parrygg.models.EventIdentifier
	18, // 9: parrygg.services.GetEntrantResultResponse.placement:type_name -> parrygg.models.Placement
	19, // 10: parrygg.services.GetEntrantResultResponse.phases:type_name -> parrygg.models.Phase
	14, // 11: parrygg.services.GetEventEntrantsRequest.event_identifier:type_name -> parrygg.models.EventIdentifier
	20, // 12: parrygg.services.GetEventEntrantsResponse.event_entrants:type_name -> parrygg.models.EventEntrant
	1,  // 13: parrygg.services.EventService.GetEvent:input_type -> parrygg.services.GetEventRequest
	4,  // 14: parrygg.services.EventService.GetEvents:input_type -> parrygg.services.GetEventsRequest
	8,  // 15: parrygg.services.EventService.GetEventPlacements:input_type -> parrygg.services.GetEventPlacementsRequest
	12, // 16: parrygg.services.EventService.GetEventEntrants:input_type -> parrygg.services.GetEventEntrantsRequest
	6,  // 17: parrygg.services.EventService.ResetEvent:input_type -> parrygg.services.ResetEventRequest
	10, // 18: parrygg.services.EventService.GetEntrantResult:input_type -> parrygg.services.GetEntrantResultRequest
	2,  // 19: parrygg.services.EventService.GetEvent:output_type -> parrygg.services.GetEventResponse
	5,  // 20: parrygg.services.EventService.GetEvents:output_type -> parrygg.services.GetEventsResponse
	9,  // 21: parrygg.services.EventService.GetEventPlacements:output_type -> parrygg.services.GetEventPlacementsResponse
	13, // 22: parrygg.services.EventService.GetEventEntrants:output_type -> parrygg.services.GetEventEntrantsResponse
	7,  // 23: parrygg.services.EventService.ResetEvent:output_type -> parrygg.services.ResetEventResponse
	11, // 24: parrygg.services.EventService.GetEntrantResult:output_type -> parrygg.services.GetEntrantResultResponse
	19, // [19:25] is the sub-list for method output_type
	13, // [13:19] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_services_event_service_proto_init() }
func file_services_event_service_proto_init() {
	if File_services_event_service_proto != nil {
		return
	}
	file_models_event_proto_init()
	file_models_hierarchy_proto_init()
	file_models_filter_proto_init()
	file_models_entrant_proto_init()
	file_models_phase_proto_init()
	file_models_request_proto_init()
	file_models_event_export_proto_init()
	file_services_event_service_proto_msgTypes[7].OneofWrappers = []any{
		(*GetEventPlacementsRequest_Id)(nil),
		(*GetEventPlacementsRequest_EventSlugPath)(nil),
	}
	file_services_event_service_proto_msgTypes[9].OneofWrappers = []any{
		(*GetEntrantResultRequest_EntrantId)(nil),
		(*GetEntrantResultRequest_UserId)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_services_event_service_proto_rawDesc), len(file_services_event_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_event_service_proto_goTypes,
		DependencyIndexes: file_services_event_service_proto_depIdxs,
		EnumInfos:         file_services_event_service_proto_enumTypes,
		MessageInfos:      file_services_event_service_proto_msgTypes,
	}.Build()
	File_services_event_service_proto = out.File
	file_services_event_service_proto_goTypes = nil
	file_services_event_service_proto_depIdxs = nil
}
