// Game definitions for tournament competitions.
// Manages video game metadata, descriptions, and associated images.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: models/game.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CharacterImageType defines the purpose and display context for character images.
type CharacterImageType int32

const (
	// Default unspecified character image type.
	CharacterImageType_CHARACTER_IMAGE_TYPE_UNSPECIFIED CharacterImageType = 0
	// Stock icon image for the character.
	CharacterImageType_CHARACTER_IMAGE_TYPE_STOCK_ICON CharacterImageType = 1
	// Portrait image for the character.
	CharacterImageType_CHARACTER_IMAGE_TYPE_PORTRAIT CharacterImageType = 2
)

// Enum value maps for CharacterImageType.
var (
	CharacterImageType_name = map[int32]string{
		0: "CHARACTER_IMAGE_TYPE_UNSPECIFIED",
		1: "CHARACTER_IMAGE_TYPE_STOCK_ICON",
		2: "CHARACTER_IMAGE_TYPE_PORTRAIT",
	}
	CharacterImageType_value = map[string]int32{
		"CHARACTER_IMAGE_TYPE_UNSPECIFIED": 0,
		"CHARACTER_IMAGE_TYPE_STOCK_ICON":  1,
		"CHARACTER_IMAGE_TYPE_PORTRAIT":    2,
	}
)

func (x CharacterImageType) Enum() *CharacterImageType {
	p := new(CharacterImageType)
	*p = x
	return p
}

func (x CharacterImageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CharacterImageType) Descriptor() protoreflect.EnumDescriptor {
	return file_models_game_proto_enumTypes[0].Descriptor()
}

func (CharacterImageType) Type() protoreflect.EnumType {
	return &file_models_game_proto_enumTypes[0]
}

func (x CharacterImageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CharacterImageType.Descriptor instead.
func (CharacterImageType) EnumDescriptor() ([]byte, []int) {
	return file_models_game_proto_rawDescGZIP(), []int{0}
}

// StageImageType defines the purpose and display context for stage images.
type StageImageType int32

const (
	// Default unspecified stage image type.
	StageImageType_STAGE_IMAGE_TYPE_UNSPECIFIED StageImageType = 0
	// Thumbnail image for the stage.
	StageImageType_STAGE_IMAGE_TYPE_THUMBNAIL StageImageType = 1
)

// Enum value maps for StageImageType.
var (
	StageImageType_name = map[int32]string{
		0: "STAGE_IMAGE_TYPE_UNSPECIFIED",
		1: "STAGE_IMAGE_TYPE_THUMBNAIL",
	}
	StageImageType_value = map[string]int32{
		"STAGE_IMAGE_TYPE_UNSPECIFIED": 0,
		"STAGE_IMAGE_TYPE_THUMBNAIL":   1,
	}
)

func (x StageImageType) Enum() *StageImageType {
	p := new(StageImageType)
	*p = x
	return p
}

func (x StageImageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StageImageType) Descriptor() protoreflect.EnumDescriptor {
	return file_models_game_proto_enumTypes[1].Descriptor()
}

func (StageImageType) Type() protoreflect.EnumType {
	return &file_models_game_proto_enumTypes[1]
}

func (x StageImageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StageImageType.Descriptor instead.
func (StageImageType) EnumDescriptor() ([]byte, []int) {
	return file_models_game_proto_rawDescGZIP(), []int{1}
}

// Game represents a video game that can be played in tournaments.
// Contains metadata and visual assets for the game.
// Next id: 8
type Game struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier for the game (UUID v7).
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Display name of the game (e.g., "Super Smash Bros. Melee").
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Description of the game and its competitive scene.
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// Images associated with the game (logos, artwork, etc.).
	Images []*Image `protobuf:"bytes,4,rep,name=images,proto3" json:"images,omitempty"`
	// URL-friendly slug for the game (e.g., "super-smash-bros-melee").
	Slug string `protobuf:"bytes,5,opt,name=slug,proto3" json:"slug,omitempty"`
	// All playable characters in this game with their variant images.
	Characters []*Character `protobuf:"bytes,6,rep,name=characters,proto3" json:"characters,omitempty"`
	// All playable stages in this game with their variant images.
	Stages        []*Stage `protobuf:"bytes,7,rep,name=stages,proto3" json:"stages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Game) Reset() {
	*x = Game{}
	mi := &file_models_game_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Game) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Game) ProtoMessage() {}

func (x *Game) ProtoReflect() protoreflect.Message {
	mi := &file_models_game_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Game.ProtoReflect.Descriptor instead.
func (*Game) Descriptor() ([]byte, []int) {
	return file_models_game_proto_rawDescGZIP(), []int{0}
}

func (x *Game) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Game) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Game) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Game) GetImages() []*Image {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *Game) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *Game) GetCharacters() []*Character {
	if x != nil {
		return x.Characters
	}
	return nil
}

func (x *Game) GetStages() []*Stage {
	if x != nil {
		return x.Stages
	}
	return nil
}

// GameMutation updates mutable fields of a game.
type GameMutation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Updated display name for the game.
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameMutation) Reset() {
	*x = GameMutation{}
	mi := &file_models_game_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameMutation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameMutation) ProtoMessage() {}

func (x *GameMutation) ProtoReflect() protoreflect.Message {
	mi := &file_models_game_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameMutation.ProtoReflect.Descriptor instead.
func (*GameMutation) Descriptor() ([]byte, []int) {
	return file_models_game_proto_rawDescGZIP(), []int{1}
}

func (x *GameMutation) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// CharacterImage represents an image associated with a character.
// Next id: 4
type CharacterImage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The image url.
	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	// Type classification for display purposes.
	Type CharacterImageType `protobuf:"varint,2,opt,name=type,proto3,enum=parrygg.models.CharacterImageType" json:"type,omitempty"`
	// Variant metadata (e.g., costume/skin information).
	Variant       *structpb.Struct `protobuf:"bytes,3,opt,name=variant,proto3" json:"variant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CharacterImage) Reset() {
	*x = CharacterImage{}
	mi := &file_models_game_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CharacterImage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CharacterImage) ProtoMessage() {}

func (x *CharacterImage) ProtoReflect() protoreflect.Message {
	mi := &file_models_game_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CharacterImage.ProtoReflect.Descriptor instead.
func (*CharacterImage) Descriptor() ([]byte, []int) {
	return file_models_game_proto_rawDescGZIP(), []int{2}
}

func (x *CharacterImage) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *CharacterImage) GetType() CharacterImageType {
	if x != nil {
		return x.Type
	}
	return CharacterImageType_CHARACTER_IMAGE_TYPE_UNSPECIFIED
}

func (x *CharacterImage) GetVariant() *structpb.Struct {
	if x != nil {
		return x.Variant
	}
	return nil
}

// Character represents a playable character in a game.
// Next id: 6
type Character struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier for the character (UUID v7).
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Identifier of the game this character belongs to.
	GameId string `protobuf:"bytes,2,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	// Display name of the character.
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// URL-friendly slug for the character (e.g., "doctor-mario").
	Slug string `protobuf:"bytes,4,opt,name=slug,proto3" json:"slug,omitempty"`
	// Images associated with the character (stock icons, portraits, etc.).
	Images        []*CharacterImage `protobuf:"bytes,5,rep,name=images,proto3" json:"images,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Character) Reset() {
	*x = Character{}
	mi := &file_models_game_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Character) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Character) ProtoMessage() {}

func (x *Character) ProtoReflect() protoreflect.Message {
	mi := &file_models_game_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Character.ProtoReflect.Descriptor instead.
func (*Character) Descriptor() ([]byte, []int) {
	return file_models_game_proto_rawDescGZIP(), []int{3}
}

func (x *Character) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Character) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *Character) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Character) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *Character) GetImages() []*CharacterImage {
	if x != nil {
		return x.Images
	}
	return nil
}

// StageImage represents an image associated with a stage.
// Next id: 4
type StageImage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The image url.
	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	// Type classification for display purposes.
	Type StageImageType `protobuf:"varint,2,opt,name=type,proto3,enum=parrygg.models.StageImageType" json:"type,omitempty"`
	// Variant metadata (e.g., battlefield form, hazards on/off).
	Variant       *structpb.Struct `protobuf:"bytes,3,opt,name=variant,proto3" json:"variant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StageImage) Reset() {
	*x = StageImage{}
	mi := &file_models_game_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StageImage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StageImage) ProtoMessage() {}

func (x *StageImage) ProtoReflect() protoreflect.Message {
	mi := &file_models_game_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StageImage.ProtoReflect.Descriptor instead.
func (*StageImage) Descriptor() ([]byte, []int) {
	return file_models_game_proto_rawDescGZIP(), []int{4}
}

func (x *StageImage) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *StageImage) GetType() StageImageType {
	if x != nil {
		return x.Type
	}
	return StageImageType_STAGE_IMAGE_TYPE_UNSPECIFIED
}

func (x *StageImage) GetVariant() *structpb.Struct {
	if x != nil {
		return x.Variant
	}
	return nil
}

// Stage represents a playable stage/level in a game.
// Next id: 6
type Stage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier for the stage (UUID v7).
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Identifier of the game this stage belongs to.
	GameId string `protobuf:"bytes,2,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	// Display name of the stage.
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// URL-friendly slug for the stage (e.g., "final-destination").
	Slug string `protobuf:"bytes,4,opt,name=slug,proto3" json:"slug,omitempty"`
	// Images associated with the stage (thumbnails, etc.).
	Images        []*StageImage `protobuf:"bytes,5,rep,name=images,proto3" json:"images,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Stage) Reset() {
	*x = Stage{}
	mi := &file_models_game_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stage) ProtoMessage() {}

func (x *Stage) ProtoReflect() protoreflect.Message {
	mi := &file_models_game_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stage.ProtoReflect.Descriptor instead.
func (*Stage) Descriptor() ([]byte, []int) {
	return file_models_game_proto_rawDescGZIP(), []int{5}
}

func (x *Stage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Stage) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *Stage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Stage) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *Stage) GetImages() []*StageImage {
	if x != nil {
		return x.Images
	}
	return nil
}

var File_models_game_proto protoreflect.FileDescriptor

const file_models_game_proto_rawDesc = "" +
	"\n" +
	"\x11models/game.proto\x12\x0eparrygg.models\x1a\x12models/image.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xf9\x01\n" +
	"\x04Game\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12-\n" +
	"\x06images\x18\x04 \x03(\v2\x15.parrygg.models.ImageR\x06images\x12\x12\n" +
	"\x04slug\x18\x05 \x01(\tR\x04slug\x129\n" +
	"\n" +
	"characters\x18\x06 \x03(\v2\x19.parrygg.models.CharacterR\n" +
	"characters\x12-\n" +
	"\x06stages\x18\a \x03(\v2\x15.parrygg.models.StageR\x06stages\"\"\n" +
	"\fGameMutation\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x8d\x01\n" +
	"\x0eCharacterImage\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x126\n" +
	"\x04type\x18\x02 \x01(\x0e2\".parrygg.models.CharacterImageTypeR\x04type\x121\n" +
	"\avariant\x18\x03 \x01(\v2\x17.google.protobuf.StructR\avariant\"\x94\x01\n" +
	"\tCharacter\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\agame_id\x18\x02 \x01(\tR\x06gameId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04slug\x18\x04 \x01(\tR\x04slug\x126\n" +
	"\x06images\x18\x05 \x03(\v2\x1e.parrygg.models.CharacterImageR\x06images\"\x85\x01\n" +
	"\n" +
	"StageImage\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x122\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1e.parrygg.models.StageImageTypeR\x04type\x121\n" +
	"\avariant\x18\x03 \x01(\v2\x17.google.protobuf.StructR\avariant\"\x8c\x01\n" +
	"\x05Stage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\agame_id\x18\x02 \x01(\tR\x06gameId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04slug\x18\x04 \x01(\tR\x04slug\x122\n" +
	"\x06images\x18\x05 \x03(\v2\x1a.parrygg.models.StageImageR\x06images*\x82\x01\n" +
	"\x12CharacterImageType\x12$\n" +
	" CHARACTER_IMAGE_TYPE_UNSPECIFIED\x10\x00\x12#\n" +
	"\x1fCHARACTER_IMAGE_TYPE_STOCK_ICON\x10\x01\x12!\n" +
	"\x1dCHARACTER_IMAGE_TYPE_PORTRAIT\x10\x02*R\n" +
	"\x0eStageImageType\x12 \n" +
	"\x1cSTAGE_IMAGE_TYPE_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aSTAGE_IMAGE_TYPE_THUMBNAIL\x10\x01BA\n" +
	"\x14gg.parry.grpc.modelsP\x01Z'github.com/AaronLieb/octagon/parrygg/pbb\x06proto3"

var (
	file_models_game_proto_rawDescOnce sync.Once
	file_models_game_proto_rawDescData []byte
)

func file_models_game_proto_rawDescGZIP() []byte {
	file_models_game_proto_rawDescOnce.Do(func() {
		file_models_game_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_models_game_proto_rawDesc), len(file_models_game_proto_rawDesc)))
	})
	return file_models_game_proto_rawDescData
}

var file_models_game_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_models_game_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_models_game_proto_goTypes = []any{
	(CharacterImageType)(0), // 0: parrygg.models.CharacterImageType
	(StageImageType)(0),     // 1: parrygg.models.StageImageType
	(*Game)(nil),            // 2: parrygg.models.Game
	(*GameMutation)(nil),    // 3: parrygg.models.GameMutation
	(*CharacterImage)(nil),  // 4: parrygg.models.CharacterImage
	(*Character)(nil),       // 5: parrygg.models.Character
	(*StageImage)(nil),      // 6: parrygg.models.StageImage
	(*Stage)(nil),           // 7: parrygg.models.Stage
	(*Image)(nil),           // 8: parrygg.models.Image
	(*structpb.Struct)(nil), // 9: google.protobuf.Struct
}
var file_models_game_proto_depIdxs = []int32{
	8, // 0: parrygg.models.Game.images:type_name -> parrygg.models.Image
	5, // 1: parrygg.models.Game.characters:type_name -> parrygg.models.Character
	7, // 2: parrygg.models.Game.stages:type_name -> parrygg.models.Stage
	0, // 3: parrygg.models.CharacterImage.type:type_name -> parrygg.models.CharacterImageType
	9, // 4: parrygg.models.CharacterImage.variant:type_name -> google.protobuf.Struct
	4, // 5: parrygg.models.Character.images:type_name -> parrygg.models.CharacterImage
	1, // 6: parrygg.models.StageImage.type:type_name -> parrygg.models.StageImageType
	9, // 7: parrygg.models.StageImage.variant:type_name -> google.protobuf.Struct
	6, // 8: parrygg.models.Stage.images:type_name -> parrygg.models.StageImage
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_models_game_proto_init() }
func file_models_game_proto_init() {
	if File_models_game_proto != nil {
		return
	}
	file_models_image_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_models_game_proto_rawDesc), len(file_models_game_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_models_game_proto_goTypes,
		DependencyIndexes: file_models_game_proto_depIdxs,
		EnumInfos:         file_models_game_proto_enumTypes,
		MessageInfos:      file_models_game_proto_msgTypes,
	}.Build()
	File_models_game_proto = out.File
	file_models_game_proto_goTypes = nil
	file_models_game_proto_depIdxs = nil
}
