// Tournament hierarchy navigation service.
// Provides path-based navigation and breadcrumb generation for tournament structures.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: services/hierarchy_service.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HierarchyService_GetEventHierarchy_FullMethodName        = "/parrygg.services.HierarchyService/GetEventHierarchy"
	HierarchyService_GetPhaseHierarchy_FullMethodName        = "/parrygg.services.HierarchyService/GetPhaseHierarchy"
	HierarchyService_GetBracketHierarchy_FullMethodName      = "/parrygg.services.HierarchyService/GetBracketHierarchy"
	HierarchyService_GetAllBracketHierarchies_FullMethodName = "/parrygg.services.HierarchyService/GetAllBracketHierarchies"
)

// HierarchyServiceClient is the client API for HierarchyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HierarchyServiceClient interface {
	// Retrieves the complete hierarchy structure for an event by ID or slug path.
	GetEventHierarchy(ctx context.Context, in *GetEventHierarchyRequest, opts ...grpc.CallOption) (*GetEventHierarchyResponse, error)
	// Retrieves the complete hierarchy structure for a phase by ID or slug path.
	GetPhaseHierarchy(ctx context.Context, in *GetPhaseHierarchyRequest, opts ...grpc.CallOption) (*GetPhaseHierarchyResponse, error)
	// Retrieves the complete hierarchy structure for a bracket by ID or slug path.
	GetBracketHierarchy(ctx context.Context, in *GetBracketHierarchyRequest, opts ...grpc.CallOption) (*GetBracketHierarchyResponse, error)
	// Retrieves the hierarchy structures to access all brackets within an event.
	GetAllBracketHierarchies(ctx context.Context, in *GetAllBracketHierarchiesRequest, opts ...grpc.CallOption) (*GetAllBracketHierarchiesResponse, error)
}

type hierarchyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHierarchyServiceClient(cc grpc.ClientConnInterface) HierarchyServiceClient {
	return &hierarchyServiceClient{cc}
}

func (c *hierarchyServiceClient) GetEventHierarchy(ctx context.Context, in *GetEventHierarchyRequest, opts ...grpc.CallOption) (*GetEventHierarchyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEventHierarchyResponse)
	err := c.cc.Invoke(ctx, HierarchyService_GetEventHierarchy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hierarchyServiceClient) GetPhaseHierarchy(ctx context.Context, in *GetPhaseHierarchyRequest, opts ...grpc.CallOption) (*GetPhaseHierarchyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPhaseHierarchyResponse)
	err := c.cc.Invoke(ctx, HierarchyService_GetPhaseHierarchy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hierarchyServiceClient) GetBracketHierarchy(ctx context.Context, in *GetBracketHierarchyRequest, opts ...grpc.CallOption) (*GetBracketHierarchyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBracketHierarchyResponse)
	err := c.cc.Invoke(ctx, HierarchyService_GetBracketHierarchy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hierarchyServiceClient) GetAllBracketHierarchies(ctx context.Context, in *GetAllBracketHierarchiesRequest, opts ...grpc.CallOption) (*GetAllBracketHierarchiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllBracketHierarchiesResponse)
	err := c.cc.Invoke(ctx, HierarchyService_GetAllBracketHierarchies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HierarchyServiceServer is the server API for HierarchyService service.
// All implementations must embed UnimplementedHierarchyServiceServer
// for forward compatibility.
type HierarchyServiceServer interface {
	// Retrieves the complete hierarchy structure for an event by ID or slug path.
	GetEventHierarchy(context.Context, *GetEventHierarchyRequest) (*GetEventHierarchyResponse, error)
	// Retrieves the complete hierarchy structure for a phase by ID or slug path.
	GetPhaseHierarchy(context.Context, *GetPhaseHierarchyRequest) (*GetPhaseHierarchyResponse, error)
	// Retrieves the complete hierarchy structure for a bracket by ID or slug path.
	GetBracketHierarchy(context.Context, *GetBracketHierarchyRequest) (*GetBracketHierarchyResponse, error)
	// Retrieves the hierarchy structures to access all brackets within an event.
	GetAllBracketHierarchies(context.Context, *GetAllBracketHierarchiesRequest) (*GetAllBracketHierarchiesResponse, error)
	mustEmbedUnimplementedHierarchyServiceServer()
}

// UnimplementedHierarchyServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHierarchyServiceServer struct{}

func (UnimplementedHierarchyServiceServer) GetEventHierarchy(context.Context, *GetEventHierarchyRequest) (*GetEventHierarchyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEventHierarchy not implemented")
}
func (UnimplementedHierarchyServiceServer) GetPhaseHierarchy(context.Context, *GetPhaseHierarchyRequest) (*GetPhaseHierarchyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPhaseHierarchy not implemented")
}
func (UnimplementedHierarchyServiceServer) GetBracketHierarchy(context.Context, *GetBracketHierarchyRequest) (*GetBracketHierarchyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBracketHierarchy not implemented")
}
func (UnimplementedHierarchyServiceServer) GetAllBracketHierarchies(context.Context, *GetAllBracketHierarchiesRequest) (*GetAllBracketHierarchiesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAllBracketHierarchies not implemented")
}
func (UnimplementedHierarchyServiceServer) mustEmbedUnimplementedHierarchyServiceServer() {}
func (UnimplementedHierarchyServiceServer) testEmbeddedByValue()                          {}

// UnsafeHierarchyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HierarchyServiceServer will
// result in compilation errors.
type UnsafeHierarchyServiceServer interface {
	mustEmbedUnimplementedHierarchyServiceServer()
}

func RegisterHierarchyServiceServer(s grpc.ServiceRegistrar, srv HierarchyServiceServer) {
	// If the following call panics, it indicates UnimplementedHierarchyServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HierarchyService_ServiceDesc, srv)
}

func _HierarchyService_GetEventHierarchy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEventHierarchyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HierarchyServiceServer).GetEventHierarchy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HierarchyService_GetEventHierarchy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HierarchyServiceServer).GetEventHierarchy(ctx, req.(*GetEventHierarchyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HierarchyService_GetPhaseHierarchy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPhaseHierarchyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HierarchyServiceServer).GetPhaseHierarchy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HierarchyService_GetPhaseHierarchy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HierarchyServiceServer).GetPhaseHierarchy(ctx, req.(*GetPhaseHierarchyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HierarchyService_GetBracketHierarchy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBracketHierarchyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HierarchyServiceServer).GetBracketHierarchy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HierarchyService_GetBracketHierarchy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HierarchyServiceServer).GetBracketHierarchy(ctx, req.(*GetBracketHierarchyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HierarchyService_GetAllBracketHierarchies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllBracketHierarchiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HierarchyServiceServer).GetAllBracketHierarchies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HierarchyService_GetAllBracketHierarchies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HierarchyServiceServer).GetAllBracketHierarchies(ctx, req.(*GetAllBracketHierarchiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HierarchyService_ServiceDesc is the grpc.ServiceDesc for HierarchyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HierarchyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "parrygg.services.HierarchyService",
	HandlerType: (*HierarchyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetEventHierarchy",
			Handler:    _HierarchyService_GetEventHierarchy_Handler,
		},
		{
			MethodName: "GetPhaseHierarchy",
			Handler:    _HierarchyService_GetPhaseHierarchy_Handler,
		},
		{
			MethodName: "GetBracketHierarchy",
			Handler:    _HierarchyService_GetBracketHierarchy_Handler,
		},
		{
			MethodName: "GetAllBracketHierarchies",
			Handler:    _HierarchyService_GetAllBracketHierarchies_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/hierarchy_service.proto",
}
