// Tournament hierarchy and navigation structures.
// Provides path-based navigation through tournament/event/phase/bracket hierarchies.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: models/hierarchy.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PathType defines the type of entity in a tournament hierarchy.
type PathType int32

const (
	// Tournament level (top level).
	PathType_PATH_TYPE_TOURNAMENT PathType = 0
	// Event level within a tournament.
	PathType_PATH_TYPE_EVENT PathType = 1
	// Phase level within an event.
	PathType_PATH_TYPE_PHASE PathType = 2
	// Bracket level within a phase.
	PathType_PATH_TYPE_BRACKET PathType = 3
)

// Enum value maps for PathType.
var (
	PathType_name = map[int32]string{
		0: "PATH_TYPE_TOURNAMENT",
		1: "PATH_TYPE_EVENT",
		2: "PATH_TYPE_PHASE",
		3: "PATH_TYPE_BRACKET",
	}
	PathType_value = map[string]int32{
		"PATH_TYPE_TOURNAMENT": 0,
		"PATH_TYPE_EVENT":      1,
		"PATH_TYPE_PHASE":      2,
		"PATH_TYPE_BRACKET":    3,
	}
)

func (x PathType) Enum() *PathType {
	p := new(PathType)
	*p = x
	return p
}

func (x PathType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PathType) Descriptor() protoreflect.EnumDescriptor {
	return file_models_hierarchy_proto_enumTypes[0].Descriptor()
}

func (PathType) Type() protoreflect.EnumType {
	return &file_models_hierarchy_proto_enumTypes[0]
}

func (x PathType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PathType.Descriptor instead.
func (PathType) EnumDescriptor() ([]byte, []int) {
	return file_models_hierarchy_proto_rawDescGZIP(), []int{0}
}

// Path represents a single level in the tournament hierarchy.
type Path struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier for this path element.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Type of hierarchy level this path represents.
	Type PathType `protobuf:"varint,2,opt,name=type,proto3,enum=parrygg.models.PathType" json:"type,omitempty"`
	// Display name for this path element.
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// URL-friendly slug for this path element.
	Slug          string `protobuf:"bytes,4,opt,name=slug,proto3" json:"slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Path) Reset() {
	*x = Path{}
	mi := &file_models_hierarchy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Path) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Path) ProtoMessage() {}

func (x *Path) ProtoReflect() protoreflect.Message {
	mi := &file_models_hierarchy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Path.ProtoReflect.Descriptor instead.
func (*Path) Descriptor() ([]byte, []int) {
	return file_models_hierarchy_proto_rawDescGZIP(), []int{0}
}

func (x *Path) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Path) GetType() PathType {
	if x != nil {
		return x.Type
	}
	return PathType_PATH_TYPE_TOURNAMENT
}

func (x *Path) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Path) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

// EventSlugPath provides slug-based identification for events.
type EventSlugPath struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// URL slug of the parent tournament.
	TournamentSlug string `protobuf:"bytes,1,opt,name=tournament_slug,json=tournamentSlug,proto3" json:"tournament_slug,omitempty"`
	// URL slug of the event.
	EventSlug     string `protobuf:"bytes,2,opt,name=event_slug,json=eventSlug,proto3" json:"event_slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventSlugPath) Reset() {
	*x = EventSlugPath{}
	mi := &file_models_hierarchy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventSlugPath) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventSlugPath) ProtoMessage() {}

func (x *EventSlugPath) ProtoReflect() protoreflect.Message {
	mi := &file_models_hierarchy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventSlugPath.ProtoReflect.Descriptor instead.
func (*EventSlugPath) Descriptor() ([]byte, []int) {
	return file_models_hierarchy_proto_rawDescGZIP(), []int{1}
}

func (x *EventSlugPath) GetTournamentSlug() string {
	if x != nil {
		return x.TournamentSlug
	}
	return ""
}

func (x *EventSlugPath) GetEventSlug() string {
	if x != nil {
		return x.EventSlug
	}
	return ""
}

// PhaseSlugPath provides slug-based identification for phases.
type PhaseSlugPath struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// URL slug of the parent tournament.
	TournamentSlug string `protobuf:"bytes,1,opt,name=tournament_slug,json=tournamentSlug,proto3" json:"tournament_slug,omitempty"`
	// URL slug of the parent event.
	EventSlug string `protobuf:"bytes,2,opt,name=event_slug,json=eventSlug,proto3" json:"event_slug,omitempty"`
	// URL slug of the phase.
	PhaseSlug     string `protobuf:"bytes,3,opt,name=phase_slug,json=phaseSlug,proto3" json:"phase_slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PhaseSlugPath) Reset() {
	*x = PhaseSlugPath{}
	mi := &file_models_hierarchy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PhaseSlugPath) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhaseSlugPath) ProtoMessage() {}

func (x *PhaseSlugPath) ProtoReflect() protoreflect.Message {
	mi := &file_models_hierarchy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhaseSlugPath.ProtoReflect.Descriptor instead.
func (*PhaseSlugPath) Descriptor() ([]byte, []int) {
	return file_models_hierarchy_proto_rawDescGZIP(), []int{2}
}

func (x *PhaseSlugPath) GetTournamentSlug() string {
	if x != nil {
		return x.TournamentSlug
	}
	return ""
}

func (x *PhaseSlugPath) GetEventSlug() string {
	if x != nil {
		return x.EventSlug
	}
	return ""
}

func (x *PhaseSlugPath) GetPhaseSlug() string {
	if x != nil {
		return x.PhaseSlug
	}
	return ""
}

// BracketSlugPath provides slug-based identification for brackets.
type BracketSlugPath struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// URL slug of the parent tournament.
	TournamentSlug string `protobuf:"bytes,1,opt,name=tournament_slug,json=tournamentSlug,proto3" json:"tournament_slug,omitempty"`
	// URL slug of the parent event.
	EventSlug string `protobuf:"bytes,2,opt,name=event_slug,json=eventSlug,proto3" json:"event_slug,omitempty"`
	// URL slug of the parent phase.
	PhaseSlug string `protobuf:"bytes,3,opt,name=phase_slug,json=phaseSlug,proto3" json:"phase_slug,omitempty"`
	// URL slug of the bracket.
	BracketSlug   string `protobuf:"bytes,4,opt,name=bracket_slug,json=bracketSlug,proto3" json:"bracket_slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BracketSlugPath) Reset() {
	*x = BracketSlugPath{}
	mi := &file_models_hierarchy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BracketSlugPath) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BracketSlugPath) ProtoMessage() {}

func (x *BracketSlugPath) ProtoReflect() protoreflect.Message {
	mi := &file_models_hierarchy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BracketSlugPath.ProtoReflect.Descriptor instead.
func (*BracketSlugPath) Descriptor() ([]byte, []int) {
	return file_models_hierarchy_proto_rawDescGZIP(), []int{3}
}

func (x *BracketSlugPath) GetTournamentSlug() string {
	if x != nil {
		return x.TournamentSlug
	}
	return ""
}

func (x *BracketSlugPath) GetEventSlug() string {
	if x != nil {
		return x.EventSlug
	}
	return ""
}

func (x *BracketSlugPath) GetPhaseSlug() string {
	if x != nil {
		return x.PhaseSlug
	}
	return ""
}

func (x *BracketSlugPath) GetBracketSlug() string {
	if x != nil {
		return x.BracketSlug
	}
	return ""
}

// Hierarchy represents a complete navigation path through tournament structure.
type Hierarchy struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Ordered path elements from tournament down to target entity.
	Paths         []*Path `protobuf:"bytes,1,rep,name=paths,proto3" json:"paths,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hierarchy) Reset() {
	*x = Hierarchy{}
	mi := &file_models_hierarchy_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hierarchy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hierarchy) ProtoMessage() {}

func (x *Hierarchy) ProtoReflect() protoreflect.Message {
	mi := &file_models_hierarchy_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hierarchy.ProtoReflect.Descriptor instead.
func (*Hierarchy) Descriptor() ([]byte, []int) {
	return file_models_hierarchy_proto_rawDescGZIP(), []int{4}
}

func (x *Hierarchy) GetPaths() []*Path {
	if x != nil {
		return x.Paths
	}
	return nil
}

var File_models_hierarchy_proto protoreflect.FileDescriptor

const file_models_hierarchy_proto_rawDesc = "" +
	"\n" +
	"\x16models/hierarchy.proto\x12\x0eparrygg.models\"l\n" +
	"\x04Path\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12,\n" +
	"\x04type\x18\x02 \x01(\x0e2\x18.parrygg.models.PathTypeR\x04type\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04slug\x18\x04 \x01(\tR\x04slug\"W\n" +
	"\rEventSlugPath\x12'\n" +
	"\x0ftournament_slug\x18\x01 \x01(\tR\x0etournamentSlug\x12\x1d\n" +
	"\n" +
	"event_slug\x18\x02 \x01(\tR\teventSlug\"v\n" +
	"\rPhaseSlugPath\x12'\n" +
	"\x0ftournament_slug\x18\x01 \x01(\tR\x0etournamentSlug\x12\x1d\n" +
	"\n" +
	"event_slug\x18\x02 \x01(\tR\teventSlug\x12\x1d\n" +
	"\n" +
	"phase_slug\x18\x03 \x01(\tR\tphaseSlug\"\x9b\x01\n" +
	"\x0fBracketSlugPath\x12'\n" +
	"\x0ftournament_slug\x18\x01 \x01(\tR\x0etournamentSlug\x12\x1d\n" +
	"\n" +
	"event_slug\x18\x02 \x01(\tR\teventSlug\x12\x1d\n" +
	"\n" +
	"phase_slug\x18\x03 \x01(\tR\tphaseSlug\x12!\n" +
	"\fbracket_slug\x18\x04 \x01(\tR\vbracketSlug\"7\n" +
	"\tHierarchy\x12*\n" +
	"\x05paths\x18\x01 \x03(\v2\x14.parrygg.models.PathR\x05paths*e\n" +
	"\bPathType\x12\x18\n" +
	"\x14PATH_TYPE_TOURNAMENT\x10\x00\x12\x13\n" +
	"\x0fPATH_TYPE_EVENT\x10\x01\x12\x13\n" +
	"\x0fPATH_TYPE_PHASE\x10\x02\x12\x15\n" +
	"\x11PATH_TYPE_BRACKET\x10\x03BA\n" +
	"\x14gg.parry.grpc.modelsP\x01Z'github.com/AaronLieb/octagon/parrygg/pbb\x06proto3"

var (
	file_models_hierarchy_proto_rawDescOnce sync.Once
	file_models_hierarchy_proto_rawDescData []byte
)

func file_models_hierarchy_proto_rawDescGZIP() []byte {
	file_models_hierarchy_proto_rawDescOnce.Do(func() {
		file_models_hierarchy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_models_hierarchy_proto_rawDesc), len(file_models_hierarchy_proto_rawDesc)))
	})
	return file_models_hierarchy_proto_rawDescData
}

var file_models_hierarchy_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_models_hierarchy_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_models_hierarchy_proto_goTypes = []any{
	(PathType)(0),           // 0: parrygg.models.PathType
	(*Path)(nil),            // 1: parrygg.models.Path
	(*EventSlugPath)(nil),   // 2: parrygg.models.EventSlugPath
	(*PhaseSlugPath)(nil),   // 3: parrygg.models.PhaseSlugPath
	(*BracketSlugPath)(nil), // 4: parrygg.models.BracketSlugPath
	(*Hierarchy)(nil),       // 5: parrygg.models.Hierarchy
}
var file_models_hierarchy_proto_depIdxs = []int32{
	0, // 0: parrygg.models.Path.type:type_name -> parrygg.models.PathType
	1, // 1: parrygg.models.Hierarchy.paths:type_name -> parrygg.models.Path
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_models_hierarchy_proto_init() }
func file_models_hierarchy_proto_init() {
	if File_models_hierarchy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_models_hierarchy_proto_rawDesc), len(file_models_hierarchy_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_models_hierarchy_proto_goTypes,
		DependencyIndexes: file_models_hierarchy_proto_depIdxs,
		EnumInfos:         file_models_hierarchy_proto_enumTypes,
		MessageInfos:      file_models_hierarchy_proto_msgTypes,
	}.Build()
	File_models_hierarchy_proto = out.File
	file_models_hierarchy_proto_goTypes = nil
	file_models_hierarchy_proto_depIdxs = nil
}
