// Image management for tournaments, games, and users.
// Handles different types of visual assets with URL-based storage.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: models/image.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ImageType defines the purpose and display context for images.
// Next id: 4
type ImageType int32

const (
	// Default unspecified image type.
	ImageType_IMAGE_TYPE_UNSPECIFIED ImageType = 0
	// Banner image for headers and promotional displays.
	ImageType_IMAGE_TYPE_BANNER ImageType = 1
	// Avatar image for user profiles and small displays.
	ImageType_IMAGE_TYPE_AVATAR ImageType = 2
	// Cover image for large background displays.
	ImageType_IMAGE_TYPE_COVER ImageType = 3
)

// Enum value maps for ImageType.
var (
	ImageType_name = map[int32]string{
		0: "IMAGE_TYPE_UNSPECIFIED",
		1: "IMAGE_TYPE_BANNER",
		2: "IMAGE_TYPE_AVATAR",
		3: "IMAGE_TYPE_COVER",
	}
	ImageType_value = map[string]int32{
		"IMAGE_TYPE_UNSPECIFIED": 0,
		"IMAGE_TYPE_BANNER":      1,
		"IMAGE_TYPE_AVATAR":      2,
		"IMAGE_TYPE_COVER":       3,
	}
)

func (x ImageType) Enum() *ImageType {
	p := new(ImageType)
	*p = x
	return p
}

func (x ImageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ImageType) Descriptor() protoreflect.EnumDescriptor {
	return file_models_image_proto_enumTypes[0].Descriptor()
}

func (ImageType) Type() protoreflect.EnumType {
	return &file_models_image_proto_enumTypes[0]
}

func (x ImageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ImageType.Descriptor instead.
func (ImageType) EnumDescriptor() ([]byte, []int) {
	return file_models_image_proto_rawDescGZIP(), []int{0}
}

// Image represents a visual asset with type classification.
// Next id: 4
type Image struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier for the image (UUID v7).
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// URL where the image can be accessed.
	Url string `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	// Type classification for display purposes.
	Type          ImageType `protobuf:"varint,3,opt,name=type,proto3,enum=parrygg.models.ImageType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Image) Reset() {
	*x = Image{}
	mi := &file_models_image_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Image) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Image) ProtoMessage() {}

func (x *Image) ProtoReflect() protoreflect.Message {
	mi := &file_models_image_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Image.ProtoReflect.Descriptor instead.
func (*Image) Descriptor() ([]byte, []int) {
	return file_models_image_proto_rawDescGZIP(), []int{0}
}

func (x *Image) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Image) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Image) GetType() ImageType {
	if x != nil {
		return x.Type
	}
	return ImageType_IMAGE_TYPE_UNSPECIFIED
}

var File_models_image_proto protoreflect.FileDescriptor

const file_models_image_proto_rawDesc = "" +
	"\n" +
	"\x12models/image.proto\x12\x0eparrygg.models\"X\n" +
	"\x05Image\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12-\n" +
	"\x04type\x18\x03 \x01(\x0e2\x19.parrygg.models.ImageTypeR\x04type*k\n" +
	"\tImageType\x12\x1a\n" +
	"\x16IMAGE_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11IMAGE_TYPE_BANNER\x10\x01\x12\x15\n" +
	"\x11IMAGE_TYPE_AVATAR\x10\x02\x12\x14\n" +
	"\x10IMAGE_TYPE_COVER\x10\x03BA\n" +
	"\x14gg.parry.grpc.modelsP\x01Z'github.com/AaronLieb/octagon/parrygg/pbb\x06proto3"

var (
	file_models_image_proto_rawDescOnce sync.Once
	file_models_image_proto_rawDescData []byte
)

func file_models_image_proto_rawDescGZIP() []byte {
	file_models_image_proto_rawDescOnce.Do(func() {
		file_models_image_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_models_image_proto_rawDesc), len(file_models_image_proto_rawDesc)))
	})
	return file_models_image_proto_rawDescData
}

var file_models_image_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_models_image_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_models_image_proto_goTypes = []any{
	(ImageType)(0), // 0: parrygg.models.ImageType
	(*Image)(nil),  // 1: parrygg.models.Image
}
var file_models_image_proto_depIdxs = []int32{
	0, // 0: parrygg.models.Image.type:type_name -> parrygg.models.ImageType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_models_image_proto_init() }
func file_models_image_proto_init() {
	if File_models_image_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_models_image_proto_rawDesc), len(file_models_image_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_models_image_proto_goTypes,
		DependencyIndexes: file_models_image_proto_depIdxs,
		EnumInfos:         file_models_image_proto_enumTypes,
		MessageInfos:      file_models_image_proto_msgTypes,
	}.Build()
	File_models_image_proto = out.File
	file_models_image_proto_goTypes = nil
	file_models_image_proto_depIdxs = nil
}
