// Match management service for tournament bracket matches.
// Provides operations for match lifecycle, scoring, and state management.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: services/match_service.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MatchService_GetMatch_FullMethodName       = "/parrygg.services.MatchService/GetMatch"
	MatchService_GetMatches_FullMethodName     = "/parrygg.services.MatchService/GetMatches"
	MatchService_SetMatchResult_FullMethodName = "/parrygg.services.MatchService/SetMatchResult"
	MatchService_StartMatch_FullMethodName     = "/parrygg.services.MatchService/StartMatch"
	MatchService_ResetMatch_FullMethodName     = "/parrygg.services.MatchService/ResetMatch"
)

// MatchServiceClient is the client API for MatchService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MatchService provides tournament match management operations.
// Handles match lifecycle, scoring, and result reporting.
type MatchServiceClient interface {
	// Retrieve a specific match by ID.
	GetMatch(ctx context.Context, in *GetMatchRequest, opts ...grpc.CallOption) (*GetMatchResponse, error)
	// Retrieve multiple matches based on filter criteria.
	GetMatches(ctx context.Context, in *GetMatchesRequest, opts ...grpc.CallOption) (*GetMatchesResponse, error)
	// Update match results and participant scores.
	SetMatchResult(ctx context.Context, in *SetMatchResultRequest, opts ...grpc.CallOption) (*SetMatchResultResponse, error)
	// Start a match and change state to in-progress.
	StartMatch(ctx context.Context, in *StartMatchRequest, opts ...grpc.CallOption) (*StartMatchResponse, error)
	// Reset a match to initial state, clearing results.
	ResetMatch(ctx context.Context, in *ResetMatchRequest, opts ...grpc.CallOption) (*ResetMatchResponse, error)
}

type matchServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMatchServiceClient(cc grpc.ClientConnInterface) MatchServiceClient {
	return &matchServiceClient{cc}
}

func (c *matchServiceClient) GetMatch(ctx context.Context, in *GetMatchRequest, opts ...grpc.CallOption) (*GetMatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMatchResponse)
	err := c.cc.Invoke(ctx, MatchService_GetMatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matchServiceClient) GetMatches(ctx context.Context, in *GetMatchesRequest, opts ...grpc.CallOption) (*GetMatchesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMatchesResponse)
	err := c.cc.Invoke(ctx, MatchService_GetMatches_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matchServiceClient) SetMatchResult(ctx context.Context, in *SetMatchResultRequest, opts ...grpc.CallOption) (*SetMatchResultResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetMatchResultResponse)
	err := c.cc.Invoke(ctx, MatchService_SetMatchResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matchServiceClient) StartMatch(ctx context.Context, in *StartMatchRequest, opts ...grpc.CallOption) (*StartMatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartMatchResponse)
	err := c.cc.Invoke(ctx, MatchService_StartMatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matchServiceClient) ResetMatch(ctx context.Context, in *ResetMatchRequest, opts ...grpc.CallOption) (*ResetMatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResetMatchResponse)
	err := c.cc.Invoke(ctx, MatchService_ResetMatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MatchServiceServer is the server API for MatchService service.
// All implementations must embed UnimplementedMatchServiceServer
// for forward compatibility.
//
// MatchService provides tournament match management operations.
// Handles match lifecycle, scoring, and result reporting.
type MatchServiceServer interface {
	// Retrieve a specific match by ID.
	GetMatch(context.Context, *GetMatchRequest) (*GetMatchResponse, error)
	// Retrieve multiple matches based on filter criteria.
	GetMatches(context.Context, *GetMatchesRequest) (*GetMatchesResponse, error)
	// Update match results and participant scores.
	SetMatchResult(context.Context, *SetMatchResultRequest) (*SetMatchResultResponse, error)
	// Start a match and change state to in-progress.
	StartMatch(context.Context, *StartMatchRequest) (*StartMatchResponse, error)
	// Reset a match to initial state, clearing results.
	ResetMatch(context.Context, *ResetMatchRequest) (*ResetMatchResponse, error)
	mustEmbedUnimplementedMatchServiceServer()
}

// UnimplementedMatchServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMatchServiceServer struct{}

func (UnimplementedMatchServiceServer) GetMatch(context.Context, *GetMatchRequest) (*GetMatchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMatch not implemented")
}
func (UnimplementedMatchServiceServer) GetMatches(context.Context, *GetMatchesRequest) (*GetMatchesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMatches not implemented")
}
func (UnimplementedMatchServiceServer) SetMatchResult(context.Context, *SetMatchResultRequest) (*SetMatchResultResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetMatchResult not implemented")
}
func (UnimplementedMatchServiceServer) StartMatch(context.Context, *StartMatchRequest) (*StartMatchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartMatch not implemented")
}
func (UnimplementedMatchServiceServer) ResetMatch(context.Context, *ResetMatchRequest) (*ResetMatchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResetMatch not implemented")
}
func (UnimplementedMatchServiceServer) mustEmbedUnimplementedMatchServiceServer() {}
func (UnimplementedMatchServiceServer) testEmbeddedByValue()                      {}

// UnsafeMatchServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MatchServiceServer will
// result in compilation errors.
type UnsafeMatchServiceServer interface {
	mustEmbedUnimplementedMatchServiceServer()
}

func RegisterMatchServiceServer(s grpc.ServiceRegistrar, srv MatchServiceServer) {
	// If the following call panics, it indicates UnimplementedMatchServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MatchService_ServiceDesc, srv)
}

func _MatchService_GetMatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchServiceServer).GetMatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MatchService_GetMatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchServiceServer).GetMatch(ctx, req.(*GetMatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MatchService_GetMatches_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMatchesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchServiceServer).GetMatches(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MatchService_GetMatches_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchServiceServer).GetMatches(ctx, req.(*GetMatchesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MatchService_SetMatchResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetMatchResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchServiceServer).SetMatchResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MatchService_SetMatchResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchServiceServer).SetMatchResult(ctx, req.(*SetMatchResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MatchService_StartMatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartMatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchServiceServer).StartMatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MatchService_StartMatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchServiceServer).StartMatch(ctx, req.(*StartMatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MatchService_ResetMatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetMatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchServiceServer).ResetMatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MatchService_ResetMatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchServiceServer).ResetMatch(ctx, req.(*ResetMatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MatchService_ServiceDesc is the grpc.ServiceDesc for MatchService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MatchService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "parrygg.services.MatchService",
	HandlerType: (*MatchServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMatch",
			Handler:    _MatchService_GetMatch_Handler,
		},
		{
			MethodName: "GetMatches",
			Handler:    _MatchService_GetMatches_Handler,
		},
		{
			MethodName: "SetMatchResult",
			Handler:    _MatchService_SetMatchResult_Handler,
		},
		{
			MethodName: "StartMatch",
			Handler:    _MatchService_StartMatch_Handler,
		},
		{
			MethodName: "ResetMatch",
			Handler:    _MatchService_ResetMatch_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/match_service.proto",
}
