// Match management service for tournament bracket matches.
// Provides operations for match lifecycle, scoring, and state management.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: services/match_service.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetMatchRequest retrieves a specific match.
type GetMatchRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the match to retrieve.
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMatchRequest) Reset() {
	*x = GetMatchRequest{}
	mi := &file_services_match_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMatchRequest) ProtoMessage() {}

func (x *GetMatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_match_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMatchRequest.ProtoReflect.Descriptor instead.
func (*GetMatchRequest) Descriptor() ([]byte, []int) {
	return file_services_match_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetMatchRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// GetMatchResponse contains the requested match.
type GetMatchResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The requested match with participant slots and scores.
	Match         *Match `protobuf:"bytes,1,opt,name=match,proto3" json:"match,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMatchResponse) Reset() {
	*x = GetMatchResponse{}
	mi := &file_services_match_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMatchResponse) ProtoMessage() {}

func (x *GetMatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_match_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMatchResponse.ProtoReflect.Descriptor instead.
func (*GetMatchResponse) Descriptor() ([]byte, []int) {
	return file_services_match_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetMatchResponse) GetMatch() *Match {
	if x != nil {
		return x.Match
	}
	return nil
}

// GetMatchesRequest retrieves multiple matches based on filter criteria.
type GetMatchesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filter        *MatchesFilter         `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMatchesRequest) Reset() {
	*x = GetMatchesRequest{}
	mi := &file_services_match_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMatchesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMatchesRequest) ProtoMessage() {}

func (x *GetMatchesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_match_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMatchesRequest.ProtoReflect.Descriptor instead.
func (*GetMatchesRequest) Descriptor() ([]byte, []int) {
	return file_services_match_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetMatchesRequest) GetFilter() *MatchesFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

// GetMatchesResponse contains the list of matches with context.
type GetMatchesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Matches       []*MatchContext        `protobuf:"bytes,2,rep,name=matches,proto3" json:"matches,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMatchesResponse) Reset() {
	*x = GetMatchesResponse{}
	mi := &file_services_match_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMatchesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMatchesResponse) ProtoMessage() {}

func (x *GetMatchesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_match_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMatchesResponse.ProtoReflect.Descriptor instead.
func (*GetMatchesResponse) Descriptor() ([]byte, []int) {
	return file_services_match_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetMatchesResponse) GetMatches() []*MatchContext {
	if x != nil {
		return x.Matches
	}
	return nil
}

// SetMatchResultRequest updates match scores and results.
type SetMatchResultRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the match to update.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Score and state updates for participants.
	Result        *MatchResult `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetMatchResultRequest) Reset() {
	*x = SetMatchResultRequest{}
	mi := &file_services_match_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetMatchResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetMatchResultRequest) ProtoMessage() {}

func (x *SetMatchResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_match_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetMatchResultRequest.ProtoReflect.Descriptor instead.
func (*SetMatchResultRequest) Descriptor() ([]byte, []int) {
	return file_services_match_service_proto_rawDescGZIP(), []int{4}
}

func (x *SetMatchResultRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SetMatchResultRequest) GetResult() *MatchResult {
	if x != nil {
		return x.Result
	}
	return nil
}

// SetMatchResultResponse confirms result update.
type SetMatchResultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetMatchResultResponse) Reset() {
	*x = SetMatchResultResponse{}
	mi := &file_services_match_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetMatchResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetMatchResultResponse) ProtoMessage() {}

func (x *SetMatchResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_match_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetMatchResultResponse.ProtoReflect.Descriptor instead.
func (*SetMatchResultResponse) Descriptor() ([]byte, []int) {
	return file_services_match_service_proto_rawDescGZIP(), []int{5}
}

// ResetMatchRequest clears match results and returns to initial state.
type ResetMatchRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the match to reset.
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetMatchRequest) Reset() {
	*x = ResetMatchRequest{}
	mi := &file_services_match_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetMatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetMatchRequest) ProtoMessage() {}

func (x *ResetMatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_match_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetMatchRequest.ProtoReflect.Descriptor instead.
func (*ResetMatchRequest) Descriptor() ([]byte, []int) {
	return file_services_match_service_proto_rawDescGZIP(), []int{6}
}

func (x *ResetMatchRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// ResetMatchResponse confirms match reset.
type ResetMatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetMatchResponse) Reset() {
	*x = ResetMatchResponse{}
	mi := &file_services_match_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetMatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetMatchResponse) ProtoMessage() {}

func (x *ResetMatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_match_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetMatchResponse.ProtoReflect.Descriptor instead.
func (*ResetMatchResponse) Descriptor() ([]byte, []int) {
	return file_services_match_service_proto_rawDescGZIP(), []int{7}
}

// StartMatchRequest begins a match competition.
type StartMatchRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the match to start.
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartMatchRequest) Reset() {
	*x = StartMatchRequest{}
	mi := &file_services_match_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartMatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartMatchRequest) ProtoMessage() {}

func (x *StartMatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_match_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartMatchRequest.ProtoReflect.Descriptor instead.
func (*StartMatchRequest) Descriptor() ([]byte, []int) {
	return file_services_match_service_proto_rawDescGZIP(), []int{8}
}

func (x *StartMatchRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// StartMatchResponse confirms match start.
type StartMatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartMatchResponse) Reset() {
	*x = StartMatchResponse{}
	mi := &file_services_match_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartMatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartMatchResponse) ProtoMessage() {}

func (x *StartMatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_match_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartMatchResponse.ProtoReflect.Descriptor instead.
func (*StartMatchResponse) Descriptor() ([]byte, []int) {
	return file_services_match_service_proto_rawDescGZIP(), []int{9}
}

var File_services_match_service_proto protoreflect.FileDescriptor

const file_services_match_service_proto_rawDesc = "" +
	"\n" +
	"\x1cservices/match_service.proto\x12\x10parrygg.services\x1a\x14models/bracket.proto\x1a\x13models/filter.proto\"!\n" +
	"\x0fGetMatchRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"?\n" +
	"\x10GetMatchResponse\x12+\n" +
	"\x05match\x18\x01 \x01(\v2\x15.parrygg.models.MatchR\x05match\"J\n" +
	"\x11GetMatchesRequest\x125\n" +
	"\x06filter\x18\x01 \x01(\v2\x1d.parrygg.models.MatchesFilterR\x06filter\"R\n" +
	"\x12GetMatchesResponse\x126\n" +
	"\amatches\x18\x02 \x03(\v2\x1c.parrygg.models.MatchContextR\amatchesJ\x04\b\x01\x10\x02\"\\\n" +
	"\x15SetMatchResultRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x123\n" +
	"\x06result\x18\x02 \x01(\v2\x1b.parrygg.models.MatchResultR\x06result\"\x18\n" +
	"\x16SetMatchResultResponse\"#\n" +
	"\x11ResetMatchRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x14\n" +
	"\x12ResetMatchResponse\"#\n" +
	"\x11StartMatchRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x14\n" +
	"\x12StartMatchResponse2\xdb\x03\n" +
	"\fMatchService\x12S\n" +
	"\bGetMatch\x12!.parrygg.services.GetMatchRequest\x1a\".parrygg.services.GetMatchResponse\"\x00\x12Y\n" +
	"\n" +
	"GetMatches\x12#.parrygg.services.GetMatchesRequest\x1a$.parrygg.services.GetMatchesResponse\"\x00\x12e\n" +
	"\x0eSetMatchResult\x12'.parrygg.services.SetMatchResultRequest\x1a(.parrygg.services.SetMatchResultResponse\"\x00\x12Y\n" +
	"\n" +
	"StartMatch\x12#.parrygg.services.StartMatchRequest\x1a$.parrygg.services.StartMatchResponse\"\x00\x12Y\n" +
	"\n" +
	"ResetMatch\x12#.parrygg.services.ResetMatchRequest\x1a$.parrygg.services.ResetMatchResponse\"\x00BC\n" +
	"\x16gg.parry.grpc.servicesP\x01Z'github.com/AaronLieb/octagon/parrygg/pbb\x06proto3"

var (
	file_services_match_service_proto_rawDescOnce sync.Once
	file_services_match_service_proto_rawDescData []byte
)

func file_services_match_service_proto_rawDescGZIP() []byte {
	file_services_match_service_proto_rawDescOnce.Do(func() {
		file_services_match_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_services_match_service_proto_rawDesc), len(file_services_match_service_proto_rawDesc)))
	})
	return file_services_match_service_proto_rawDescData
}

var file_services_match_service_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_services_match_service_proto_goTypes = []any{
	(*GetMatchRequest)(nil),        // 0: parrygg.services.GetMatchRequest
	(*GetMatchResponse)(nil),       // 1: parrygg.services.GetMatchResponse
	(*GetMatchesRequest)(nil),      // 2: parrygg.services.GetMatchesRequest
	(*GetMatchesResponse)(nil),     // 3: parrygg.services.GetMatchesResponse
	(*SetMatchResultRequest)(nil),  // 4: parrygg.services.SetMatchResultRequest
	(*SetMatchResultResponse)(nil), // 5: parrygg.services.SetMatchResultResponse
	(*ResetMatchRequest)(nil),      // 6: parrygg.services.ResetMatchRequest
	(*ResetMatchResponse)(nil),     // 7: parrygg.services.ResetMatchResponse
	(*StartMatchRequest)(nil),      // 8: parrygg.services.StartMatchRequest
	(*StartMatchResponse)(nil),     // 9: parrygg.services.StartMatchResponse
	(*Match)(nil),                  // 10: parrygg.models.Match
	(*MatchesFilter)(nil),          // 11: parrygg.models.MatchesFilter
	(*MatchContext)(nil),           // 12: parrygg.models.MatchContext
	(*MatchResult)(nil),            // 13: parrygg.models.MatchResult
}
var file_services_match_service_proto_depIdxs = []int32{
	10, // 0: parrygg.services.GetMatchResponse.match:type_name -> parrygg.models.Match
	11, // 1: parrygg.services.GetMatchesRequest.filter:type_name -> parrygg.models.MatchesFilter
	12, // 2: parrygg.services.GetMatchesResponse.matches:type_name -> parrygg.models.MatchContext
	13, // 3: parrygg.services.SetMatchResultRequest.result:type_name -> parrygg.models.MatchResult
	0,  // 4: parrygg.services.MatchService.GetMatch:input_type -> parrygg.services.GetMatchRequest
	2,  // 5: parrygg.services.MatchService.GetMatches:input_type -> parrygg.services.GetMatchesRequest
	4,  // 6: parrygg.services.MatchService.SetMatchResult:input_type -> parrygg.services.SetMatchResultRequest
	8,  // 7: parrygg.services.MatchService.StartMatch:input_type -> parrygg.services.StartMatchRequest
	6,  // 8: parrygg.services.MatchService.ResetMatch:input_type -> parrygg.services.ResetMatchRequest
	1,  // 9: parrygg.services.MatchService.GetMatch:output_type -> parrygg.services.GetMatchResponse
	3,  // 10: parrygg.services.MatchService.GetMatches:output_type -> parrygg.services.GetMatchesResponse
	5,  // 11: parrygg.services.MatchService.SetMatchResult:output_type -> parrygg.services.SetMatchResultResponse
	9,  // 12: parrygg.services.MatchService.StartMatch:output_type -> parrygg.services.StartMatchResponse
	7,  // 13: parrygg.services.MatchService.ResetMatch:output_type -> parrygg.services.ResetMatchResponse
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_services_match_service_proto_init() }
func file_services_match_service_proto_init() {
	if File_services_match_service_proto != nil {
		return
	}
	file_models_bracket_proto_init()
	file_models_filter_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_services_match_service_proto_rawDesc), len(file_services_match_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_match_service_proto_goTypes,
		DependencyIndexes: file_services_match_service_proto_depIdxs,
		MessageInfos:      file_services_match_service_proto_msgTypes,
	}.Build()
	File_services_match_service_proto = out.File
	file_services_match_service_proto_goTypes = nil
	file_services_match_service_proto_depIdxs = nil
}
