// Tournament page content management service.
// Handles custom tournament pages, content creation, and markdown processing.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: services/page_content_service.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PageContentService_GetPageContents_FullMethodName   = "/parrygg.services.PageContentService/GetPageContents"
	PageContentService_CreatePageContent_FullMethodName = "/parrygg.services.PageContentService/CreatePageContent"
	PageContentService_UpdatePageContent_FullMethodName = "/parrygg.services.PageContentService/UpdatePageContent"
	PageContentService_DeletePageContent_FullMethodName = "/parrygg.services.PageContentService/DeletePageContent"
)

// PageContentServiceClient is the client API for PageContentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PageContentServiceClient interface {
	// Retrieves all page contents for a tournament by ID or identifier.
	GetPageContents(ctx context.Context, in *GetPageContentsRequest, opts ...grpc.CallOption) (*GetPageContentsResponse, error)
	// Creates new page content for a tournament.
	CreatePageContent(ctx context.Context, in *CreatePageContentRequest, opts ...grpc.CallOption) (*CreatePageContentResponse, error)
	// Updates existing page content by ID.
	UpdatePageContent(ctx context.Context, in *UpdatePageContentRequest, opts ...grpc.CallOption) (*UpdatePageContentResponse, error)
	// Deletes page content by ID.
	DeletePageContent(ctx context.Context, in *DeletePageContentRequest, opts ...grpc.CallOption) (*DeletePageContentResponse, error)
}

type pageContentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPageContentServiceClient(cc grpc.ClientConnInterface) PageContentServiceClient {
	return &pageContentServiceClient{cc}
}

func (c *pageContentServiceClient) GetPageContents(ctx context.Context, in *GetPageContentsRequest, opts ...grpc.CallOption) (*GetPageContentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPageContentsResponse)
	err := c.cc.Invoke(ctx, PageContentService_GetPageContents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pageContentServiceClient) CreatePageContent(ctx context.Context, in *CreatePageContentRequest, opts ...grpc.CallOption) (*CreatePageContentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreatePageContentResponse)
	err := c.cc.Invoke(ctx, PageContentService_CreatePageContent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pageContentServiceClient) UpdatePageContent(ctx context.Context, in *UpdatePageContentRequest, opts ...grpc.CallOption) (*UpdatePageContentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdatePageContentResponse)
	err := c.cc.Invoke(ctx, PageContentService_UpdatePageContent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pageContentServiceClient) DeletePageContent(ctx context.Context, in *DeletePageContentRequest, opts ...grpc.CallOption) (*DeletePageContentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeletePageContentResponse)
	err := c.cc.Invoke(ctx, PageContentService_DeletePageContent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PageContentServiceServer is the server API for PageContentService service.
// All implementations must embed UnimplementedPageContentServiceServer
// for forward compatibility.
type PageContentServiceServer interface {
	// Retrieves all page contents for a tournament by ID or identifier.
	GetPageContents(context.Context, *GetPageContentsRequest) (*GetPageContentsResponse, error)
	// Creates new page content for a tournament.
	CreatePageContent(context.Context, *CreatePageContentRequest) (*CreatePageContentResponse, error)
	// Updates existing page content by ID.
	UpdatePageContent(context.Context, *UpdatePageContentRequest) (*UpdatePageContentResponse, error)
	// Deletes page content by ID.
	DeletePageContent(context.Context, *DeletePageContentRequest) (*DeletePageContentResponse, error)
	mustEmbedUnimplementedPageContentServiceServer()
}

// UnimplementedPageContentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPageContentServiceServer struct{}

func (UnimplementedPageContentServiceServer) GetPageContents(context.Context, *GetPageContentsRequest) (*GetPageContentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPageContents not implemented")
}
func (UnimplementedPageContentServiceServer) CreatePageContent(context.Context, *CreatePageContentRequest) (*CreatePageContentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatePageContent not implemented")
}
func (UnimplementedPageContentServiceServer) UpdatePageContent(context.Context, *UpdatePageContentRequest) (*UpdatePageContentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdatePageContent not implemented")
}
func (UnimplementedPageContentServiceServer) DeletePageContent(context.Context, *DeletePageContentRequest) (*DeletePageContentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeletePageContent not implemented")
}
func (UnimplementedPageContentServiceServer) mustEmbedUnimplementedPageContentServiceServer() {}
func (UnimplementedPageContentServiceServer) testEmbeddedByValue()                            {}

// UnsafePageContentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PageContentServiceServer will
// result in compilation errors.
type UnsafePageContentServiceServer interface {
	mustEmbedUnimplementedPageContentServiceServer()
}

func RegisterPageContentServiceServer(s grpc.ServiceRegistrar, srv PageContentServiceServer) {
	// If the following call panics, it indicates UnimplementedPageContentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PageContentService_ServiceDesc, srv)
}

func _PageContentService_GetPageContents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPageContentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PageContentServiceServer).GetPageContents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PageContentService_GetPageContents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PageContentServiceServer).GetPageContents(ctx, req.(*GetPageContentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PageContentService_CreatePageContent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePageContentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PageContentServiceServer).CreatePageContent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PageContentService_CreatePageContent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PageContentServiceServer).CreatePageContent(ctx, req.(*CreatePageContentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PageContentService_UpdatePageContent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePageContentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PageContentServiceServer).UpdatePageContent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PageContentService_UpdatePageContent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PageContentServiceServer).UpdatePageContent(ctx, req.(*UpdatePageContentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PageContentService_DeletePageContent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePageContentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PageContentServiceServer).DeletePageContent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PageContentService_DeletePageContent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PageContentServiceServer).DeletePageContent(ctx, req.(*DeletePageContentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PageContentService_ServiceDesc is the grpc.ServiceDesc for PageContentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PageContentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "parrygg.services.PageContentService",
	HandlerType: (*PageContentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPageContents",
			Handler:    _PageContentService_GetPageContents_Handler,
		},
		{
			MethodName: "CreatePageContent",
			Handler:    _PageContentService_CreatePageContent_Handler,
		},
		{
			MethodName: "UpdatePageContent",
			Handler:    _PageContentService_UpdatePageContent_Handler,
		},
		{
			MethodName: "DeletePageContent",
			Handler:    _PageContentService_DeletePageContent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/page_content_service.proto",
}
