// Filtering criteria for tournament and event queries.
// Provides search and filtering capabilities for retrieving specific subsets of data.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: models/pagination.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PaginationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Number of items to return per page.
	// If omitted or zero, the server applies a sane default.
	PageSize uint32 `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Optional cursor token (Struct) returned by the server.
	Cursor        *structpb.Struct `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaginationRequest) Reset() {
	*x = PaginationRequest{}
	mi := &file_models_pagination_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaginationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaginationRequest) ProtoMessage() {}

func (x *PaginationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_models_pagination_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaginationRequest.ProtoReflect.Descriptor instead.
func (*PaginationRequest) Descriptor() ([]byte, []int) {
	return file_models_pagination_proto_rawDescGZIP(), []int{0}
}

func (x *PaginationRequest) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *PaginationRequest) GetCursor() *structpb.Struct {
	if x != nil {
		return x.Cursor
	}
	return nil
}

type PaginationResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The cursor token for fetching the *next* page.
	NextCursor *structpb.Struct `protobuf:"bytes,1,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	// Boolean for whether there are more pages of available items.
	HasMore       bool `protobuf:"varint,2,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaginationResponse) Reset() {
	*x = PaginationResponse{}
	mi := &file_models_pagination_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaginationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaginationResponse) ProtoMessage() {}

func (x *PaginationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_models_pagination_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaginationResponse.ProtoReflect.Descriptor instead.
func (*PaginationResponse) Descriptor() ([]byte, []int) {
	return file_models_pagination_proto_rawDescGZIP(), []int{1}
}

func (x *PaginationResponse) GetNextCursor() *structpb.Struct {
	if x != nil {
		return x.NextCursor
	}
	return nil
}

func (x *PaginationResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

var File_models_pagination_proto protoreflect.FileDescriptor

const file_models_pagination_proto_rawDesc = "" +
	"\n" +
	"\x17models/pagination.proto\x12\x0eparrygg.models\x1a\x1cgoogle/protobuf/struct.proto\"a\n" +
	"\x11PaginationRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\rR\bpageSize\x12/\n" +
	"\x06cursor\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x06cursor\"i\n" +
	"\x12PaginationResponse\x128\n" +
	"\vnext_cursor\x18\x01 \x01(\v2\x17.google.protobuf.StructR\n" +
	"nextCursor\x12\x19\n" +
	"\bhas_more\x18\x02 \x01(\bR\ahasMoreBA\n" +
	"\x14gg.parry.grpc.modelsP\x01Z'github.com/AaronLieb/octagon/parrygg/pbb\x06proto3"

var (
	file_models_pagination_proto_rawDescOnce sync.Once
	file_models_pagination_proto_rawDescData []byte
)

func file_models_pagination_proto_rawDescGZIP() []byte {
	file_models_pagination_proto_rawDescOnce.Do(func() {
		file_models_pagination_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_models_pagination_proto_rawDesc), len(file_models_pagination_proto_rawDesc)))
	})
	return file_models_pagination_proto_rawDescData
}

var file_models_pagination_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_models_pagination_proto_goTypes = []any{
	(*PaginationRequest)(nil),  // 0: parrygg.models.PaginationRequest
	(*PaginationResponse)(nil), // 1: parrygg.models.PaginationResponse
	(*structpb.Struct)(nil),    // 2: google.protobuf.Struct
}
var file_models_pagination_proto_depIdxs = []int32{
	2, // 0: parrygg.models.PaginationRequest.cursor:type_name -> google.protobuf.Struct
	2, // 1: parrygg.models.PaginationResponse.next_cursor:type_name -> google.protobuf.Struct
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_models_pagination_proto_init() }
func file_models_pagination_proto_init() {
	if File_models_pagination_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_models_pagination_proto_rawDesc), len(file_models_pagination_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_models_pagination_proto_goTypes,
		DependencyIndexes: file_models_pagination_proto_depIdxs,
		MessageInfos:      file_models_pagination_proto_msgTypes,
	}.Build()
	File_models_pagination_proto = out.File
	file_models_pagination_proto_goTypes = nil
	file_models_pagination_proto_depIdxs = nil
}
