// Tournament phase management service.
// Provides operations for phase lifecycle, seeding, and bracket creation.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: services/phase_service.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PhaseService_GetPhase_FullMethodName           = "/parrygg.services.PhaseService/GetPhase"
	PhaseService_GetPhasePlacements_FullMethodName = "/parrygg.services.PhaseService/GetPhasePlacements"
)

// PhaseServiceClient is the client API for PhaseService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PhaseServiceClient interface {
	// Retrieves a phase by ID or slug identifier.
	GetPhase(ctx context.Context, in *GetPhaseRequest, opts ...grpc.CallOption) (*GetPhaseResponse, error)
	// Retrieves final placements for participants in a completed phase.
	GetPhasePlacements(ctx context.Context, in *GetPhasePlacementsRequest, opts ...grpc.CallOption) (*GetPhasePlacementsResponse, error)
}

type phaseServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPhaseServiceClient(cc grpc.ClientConnInterface) PhaseServiceClient {
	return &phaseServiceClient{cc}
}

func (c *phaseServiceClient) GetPhase(ctx context.Context, in *GetPhaseRequest, opts ...grpc.CallOption) (*GetPhaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPhaseResponse)
	err := c.cc.Invoke(ctx, PhaseService_GetPhase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *phaseServiceClient) GetPhasePlacements(ctx context.Context, in *GetPhasePlacementsRequest, opts ...grpc.CallOption) (*GetPhasePlacementsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPhasePlacementsResponse)
	err := c.cc.Invoke(ctx, PhaseService_GetPhasePlacements_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PhaseServiceServer is the server API for PhaseService service.
// All implementations must embed UnimplementedPhaseServiceServer
// for forward compatibility.
type PhaseServiceServer interface {
	// Retrieves a phase by ID or slug identifier.
	GetPhase(context.Context, *GetPhaseRequest) (*GetPhaseResponse, error)
	// Retrieves final placements for participants in a completed phase.
	GetPhasePlacements(context.Context, *GetPhasePlacementsRequest) (*GetPhasePlacementsResponse, error)
	mustEmbedUnimplementedPhaseServiceServer()
}

// UnimplementedPhaseServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPhaseServiceServer struct{}

func (UnimplementedPhaseServiceServer) GetPhase(context.Context, *GetPhaseRequest) (*GetPhaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPhase not implemented")
}
func (UnimplementedPhaseServiceServer) GetPhasePlacements(context.Context, *GetPhasePlacementsRequest) (*GetPhasePlacementsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPhasePlacements not implemented")
}
func (UnimplementedPhaseServiceServer) mustEmbedUnimplementedPhaseServiceServer() {}
func (UnimplementedPhaseServiceServer) testEmbeddedByValue()                      {}

// UnsafePhaseServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PhaseServiceServer will
// result in compilation errors.
type UnsafePhaseServiceServer interface {
	mustEmbedUnimplementedPhaseServiceServer()
}

func RegisterPhaseServiceServer(s grpc.ServiceRegistrar, srv PhaseServiceServer) {
	// If the following call panics, it indicates UnimplementedPhaseServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PhaseService_ServiceDesc, srv)
}

func _PhaseService_GetPhase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPhaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PhaseServiceServer).GetPhase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PhaseService_GetPhase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PhaseServiceServer).GetPhase(ctx, req.(*GetPhaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PhaseService_GetPhasePlacements_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPhasePlacementsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PhaseServiceServer).GetPhasePlacements(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PhaseService_GetPhasePlacements_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PhaseServiceServer).GetPhasePlacements(ctx, req.(*GetPhasePlacementsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PhaseService_ServiceDesc is the grpc.ServiceDesc for PhaseService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PhaseService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "parrygg.services.PhaseService",
	HandlerType: (*PhaseServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPhase",
			Handler:    _PhaseService_GetPhase_Handler,
		},
		{
			MethodName: "GetPhasePlacements",
			Handler:    _PhaseService_GetPhasePlacements_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/phase_service.proto",
}
