// Tournament phase management service.
// Provides operations for phase lifecycle, seeding, and bracket creation.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: services/phase_service.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetPhaseRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Identifier:
	//
	//	*GetPhaseRequest_Id
	//	*GetPhaseRequest_SlugId
	Identifier    isGetPhaseRequest_Identifier `protobuf_oneof:"identifier"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPhaseRequest) Reset() {
	*x = GetPhaseRequest{}
	mi := &file_services_phase_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPhaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPhaseRequest) ProtoMessage() {}

func (x *GetPhaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_phase_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPhaseRequest.ProtoReflect.Descriptor instead.
func (*GetPhaseRequest) Descriptor() ([]byte, []int) {
	return file_services_phase_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetPhaseRequest) GetIdentifier() isGetPhaseRequest_Identifier {
	if x != nil {
		return x.Identifier
	}
	return nil
}

func (x *GetPhaseRequest) GetId() string {
	if x != nil {
		if x, ok := x.Identifier.(*GetPhaseRequest_Id); ok {
			return x.Id
		}
	}
	return ""
}

func (x *GetPhaseRequest) GetSlugId() *PhaseSlugId {
	if x != nil {
		if x, ok := x.Identifier.(*GetPhaseRequest_SlugId); ok {
			return x.SlugId
		}
	}
	return nil
}

type isGetPhaseRequest_Identifier interface {
	isGetPhaseRequest_Identifier()
}

type GetPhaseRequest_Id struct {
	Id string `protobuf:"bytes,1,opt,name=id,proto3,oneof"`
}

type GetPhaseRequest_SlugId struct {
	SlugId *PhaseSlugId `protobuf:"bytes,2,opt,name=slug_id,json=slugId,proto3,oneof"`
}

func (*GetPhaseRequest_Id) isGetPhaseRequest_Identifier() {}

func (*GetPhaseRequest_SlugId) isGetPhaseRequest_Identifier() {}

type GetPhaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phase         *Phase                 `protobuf:"bytes,1,opt,name=phase,proto3" json:"phase,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPhaseResponse) Reset() {
	*x = GetPhaseResponse{}
	mi := &file_services_phase_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPhaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPhaseResponse) ProtoMessage() {}

func (x *GetPhaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_phase_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPhaseResponse.ProtoReflect.Descriptor instead.
func (*GetPhaseResponse) Descriptor() ([]byte, []int) {
	return file_services_phase_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetPhaseResponse) GetPhase() *Phase {
	if x != nil {
		return x.Phase
	}
	return nil
}

type GetPhasePlacementsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPhasePlacementsRequest) Reset() {
	*x = GetPhasePlacementsRequest{}
	mi := &file_services_phase_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPhasePlacementsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPhasePlacementsRequest) ProtoMessage() {}

func (x *GetPhasePlacementsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_phase_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPhasePlacementsRequest.ProtoReflect.Descriptor instead.
func (*GetPhasePlacementsRequest) Descriptor() ([]byte, []int) {
	return file_services_phase_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetPhasePlacementsRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetPhasePlacementsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Placements    []*Placement           `protobuf:"bytes,1,rep,name=placements,proto3" json:"placements,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPhasePlacementsResponse) Reset() {
	*x = GetPhasePlacementsResponse{}
	mi := &file_services_phase_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPhasePlacementsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPhasePlacementsResponse) ProtoMessage() {}

func (x *GetPhasePlacementsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_phase_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPhasePlacementsResponse.ProtoReflect.Descriptor instead.
func (*GetPhasePlacementsResponse) Descriptor() ([]byte, []int) {
	return file_services_phase_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetPhasePlacementsResponse) GetPlacements() []*Placement {
	if x != nil {
		return x.Placements
	}
	return nil
}

type ResetPhaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetPhaseRequest) Reset() {
	*x = ResetPhaseRequest{}
	mi := &file_services_phase_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetPhaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetPhaseRequest) ProtoMessage() {}

func (x *ResetPhaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_phase_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetPhaseRequest.ProtoReflect.Descriptor instead.
func (*ResetPhaseRequest) Descriptor() ([]byte, []int) {
	return file_services_phase_service_proto_rawDescGZIP(), []int{4}
}

func (x *ResetPhaseRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ResetPhaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetPhaseResponse) Reset() {
	*x = ResetPhaseResponse{}
	mi := &file_services_phase_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetPhaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetPhaseResponse) ProtoMessage() {}

func (x *ResetPhaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_phase_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetPhaseResponse.ProtoReflect.Descriptor instead.
func (*ResetPhaseResponse) Descriptor() ([]byte, []int) {
	return file_services_phase_service_proto_rawDescGZIP(), []int{5}
}

var File_services_phase_service_proto protoreflect.FileDescriptor

const file_services_phase_service_proto_rawDesc = "" +
	"\n" +
	"\x1cservices/phase_service.proto\x12\x10parrygg.services\x1a\x12models/phase.proto\x1a\x12models/event.proto\"i\n" +
	"\x0fGetPhaseRequest\x12\x10\n" +
	"\x02id\x18\x01 \x01(\tH\x00R\x02id\x126\n" +
	"\aslug_id\x18\x02 \x01(\v2\x1b.parrygg.models.PhaseSlugIdH\x00R\x06slugIdB\f\n" +
	"\n" +
	"identifier\"?\n" +
	"\x10GetPhaseResponse\x12+\n" +
	"\x05phase\x18\x01 \x01(\v2\x15.parrygg.models.PhaseR\x05phase\"+\n" +
	"\x19GetPhasePlacementsRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"W\n" +
	"\x1aGetPhasePlacementsResponse\x129\n" +
	"\n" +
	"placements\x18\x01 \x03(\v2\x19.parrygg.models.PlacementR\n" +
	"placements\"#\n" +
	"\x11ResetPhaseRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x14\n" +
	"\x12ResetPhaseResponse2\xd6\x01\n" +
	"\fPhaseService\x12S\n" +
	"\bGetPhase\x12!.parrygg.services.GetPhaseRequest\x1a\".parrygg.services.GetPhaseResponse\"\x00\x12q\n" +
	"\x12GetPhasePlacements\x12+.parrygg.services.GetPhasePlacementsRequest\x1a,.parrygg.services.GetPhasePlacementsResponse\"\x00BC\n" +
	"\x16gg.parry.grpc.servicesP\x01Z'github.com/AaronLieb/octagon/parrygg/pbb\x06proto3"

var (
	file_services_phase_service_proto_rawDescOnce sync.Once
	file_services_phase_service_proto_rawDescData []byte
)

func file_services_phase_service_proto_rawDescGZIP() []byte {
	file_services_phase_service_proto_rawDescOnce.Do(func() {
		file_services_phase_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_services_phase_service_proto_rawDesc), len(file_services_phase_service_proto_rawDesc)))
	})
	return file_services_phase_service_proto_rawDescData
}

var file_services_phase_service_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_services_phase_service_proto_goTypes = []any{
	(*GetPhaseRequest)(nil),            // 0: parrygg.services.GetPhaseRequest
	(*GetPhaseResponse)(nil),           // 1: parrygg.services.GetPhaseResponse
	(*GetPhasePlacementsRequest)(nil),  // 2: parrygg.services.GetPhasePlacementsRequest
	(*GetPhasePlacementsResponse)(nil), // 3: parrygg.services.GetPhasePlacementsResponse
	(*ResetPhaseRequest)(nil),          // 4: parrygg.services.ResetPhaseRequest
	(*ResetPhaseResponse)(nil),         // 5: parrygg.services.ResetPhaseResponse
	(*PhaseSlugId)(nil),                // 6: parrygg.models.PhaseSlugId
	(*Phase)(nil),                      // 7: parrygg.models.Phase
	(*Placement)(nil),                  // 8: parrygg.models.Placement
}
var file_services_phase_service_proto_depIdxs = []int32{
	6, // 0: parrygg.services.GetPhaseRequest.slug_id:type_name -> parrygg.models.PhaseSlugId
	7, // 1: parrygg.services.GetPhaseResponse.phase:type_name -> parrygg.models.Phase
	8, // 2: parrygg.services.GetPhasePlacementsResponse.placements:type_name -> parrygg.models.Placement
	0, // 3: parrygg.services.PhaseService.GetPhase:input_type -> parrygg.services.GetPhaseRequest
	2, // 4: parrygg.services.PhaseService.GetPhasePlacements:input_type -> parrygg.services.GetPhasePlacementsRequest
	1, // 5: parrygg.services.PhaseService.GetPhase:output_type -> parrygg.services.GetPhaseResponse
	3, // 6: parrygg.services.PhaseService.GetPhasePlacements:output_type -> parrygg.services.GetPhasePlacementsResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_services_phase_service_proto_init() }
func file_services_phase_service_proto_init() {
	if File_services_phase_service_proto != nil {
		return
	}
	file_models_phase_proto_init()
	file_models_event_proto_init()
	file_services_phase_service_proto_msgTypes[0].OneofWrappers = []any{
		(*GetPhaseRequest_Id)(nil),
		(*GetPhaseRequest_SlugId)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_services_phase_service_proto_rawDesc), len(file_services_phase_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_phase_service_proto_goTypes,
		DependencyIndexes: file_services_phase_service_proto_depIdxs,
		MessageInfos:      file_services_phase_service_proto_msgTypes,
	}.Build()
	File_services_phase_service_proto = out.File
	file_services_phase_service_proto_goTypes = nil
	file_services_phase_service_proto_depIdxs = nil
}
