// Progression group settings management service.
// Provides CRUD operations for phase progression group settings.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: services/progression_group_settings_service.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetProgressionGroupSettingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProgressionGroupSettingsRequest) Reset() {
	*x = GetProgressionGroupSettingsRequest{}
	mi := &file_services_progression_group_settings_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProgressionGroupSettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProgressionGroupSettingsRequest) ProtoMessage() {}

func (x *GetProgressionGroupSettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_progression_group_settings_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProgressionGroupSettingsRequest.ProtoReflect.Descriptor instead.
func (*GetProgressionGroupSettingsRequest) Descriptor() ([]byte, []int) {
	return file_services_progression_group_settings_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetProgressionGroupSettingsRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetProgressionGroupSettingsResponse struct {
	state                    protoimpl.MessageState    `protogen:"open.v1"`
	ProgressionGroupSettings *ProgressionGroupSettings `protobuf:"bytes,1,opt,name=progression_group_settings,json=progressionGroupSettings,proto3" json:"progression_group_settings,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *GetProgressionGroupSettingsResponse) Reset() {
	*x = GetProgressionGroupSettingsResponse{}
	mi := &file_services_progression_group_settings_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProgressionGroupSettingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProgressionGroupSettingsResponse) ProtoMessage() {}

func (x *GetProgressionGroupSettingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_progression_group_settings_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProgressionGroupSettingsResponse.ProtoReflect.Descriptor instead.
func (*GetProgressionGroupSettingsResponse) Descriptor() ([]byte, []int) {
	return file_services_progression_group_settings_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetProgressionGroupSettingsResponse) GetProgressionGroupSettings() *ProgressionGroupSettings {
	if x != nil {
		return x.ProgressionGroupSettings
	}
	return nil
}

var File_services_progression_group_settings_service_proto protoreflect.FileDescriptor

const file_services_progression_group_settings_service_proto_rawDesc = "" +
	"\n" +
	"1services/progression_group_settings_service.proto\x12\x10parrygg.services\x1a\x18models/progression.proto\x1a\x12models/phase.proto\"4\n" +
	"\"GetProgressionGroupSettingsRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x8d\x01\n" +
	"#GetProgressionGroupSettingsResponse\x12f\n" +
	"\x1aprogression_group_settings\x18\x01 \x01(\v2(.parrygg.models.ProgressionGroupSettingsR\x18progressionGroupSettings2\xb0\x01\n" +
	"\x1fProgressionGroupSettingsService\x12\x8c\x01\n" +
	"\x1bGetProgressionGroupSettings\x124.parrygg.services.GetProgressionGroupSettingsRequest\x1a5.parrygg.services.GetProgressionGroupSettingsResponse\"\x00BC\n" +
	"\x16gg.parry.grpc.servicesP\x01Z'github.com/AaronLieb/octagon/parrygg/pbb\x06proto3"

var (
	file_services_progression_group_settings_service_proto_rawDescOnce sync.Once
	file_services_progression_group_settings_service_proto_rawDescData []byte
)

func file_services_progression_group_settings_service_proto_rawDescGZIP() []byte {
	file_services_progression_group_settings_service_proto_rawDescOnce.Do(func() {
		file_services_progression_group_settings_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_services_progression_group_settings_service_proto_rawDesc), len(file_services_progression_group_settings_service_proto_rawDesc)))
	})
	return file_services_progression_group_settings_service_proto_rawDescData
}

var file_services_progression_group_settings_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_services_progression_group_settings_service_proto_goTypes = []any{
	(*GetProgressionGroupSettingsRequest)(nil),  // 0: parrygg.services.GetProgressionGroupSettingsRequest
	(*GetProgressionGroupSettingsResponse)(nil), // 1: parrygg.services.GetProgressionGroupSettingsResponse
	(*ProgressionGroupSettings)(nil),            // 2: parrygg.models.ProgressionGroupSettings
}
var file_services_progression_group_settings_service_proto_depIdxs = []int32{
	2, // 0: parrygg.services.GetProgressionGroupSettingsResponse.progression_group_settings:type_name -> parrygg.models.ProgressionGroupSettings
	0, // 1: parrygg.services.ProgressionGroupSettingsService.GetProgressionGroupSettings:input_type -> parrygg.services.GetProgressionGroupSettingsRequest
	1, // 2: parrygg.services.ProgressionGroupSettingsService.GetProgressionGroupSettings:output_type -> parrygg.services.GetProgressionGroupSettingsResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_services_progression_group_settings_service_proto_init() }
func file_services_progression_group_settings_service_proto_init() {
	if File_services_progression_group_settings_service_proto != nil {
		return
	}
	file_models_progression_proto_init()
	file_models_phase_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_services_progression_group_settings_service_proto_rawDesc), len(file_services_progression_group_settings_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_progression_group_settings_service_proto_goTypes,
		DependencyIndexes: file_services_progression_group_settings_service_proto_depIdxs,
		MessageInfos:      file_services_progression_group_settings_service_proto_msgTypes,
	}.Build()
	File_services_progression_group_settings_service_proto = out.File
	file_services_progression_group_settings_service_proto_goTypes = nil
	file_services_progression_group_settings_service_proto_depIdxs = nil
}
