// URL-friendly identifier management for tournaments and events.
// Provides human-readable URLs and handles slug versioning and conflicts.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: models/slug.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SlugType defines the status and purpose of URL slugs.
type SlugType int32

const (
	// Default unspecified slug type.
	SlugType_SLUG_TYPE_UNSPECIFIED SlugType = 0
	// Current primary slug for the entity.
	SlugType_SLUG_TYPE_PRIMARY SlugType = 1
	// Previously used slug that now redirects.
	SlugType_SLUG_TYPE_OUTDATED SlugType = 2
	// Custom slug set by user.
	SlugType_SLUG_TYPE_CUSTOM SlugType = 3
)

// Enum value maps for SlugType.
var (
	SlugType_name = map[int32]string{
		0: "SLUG_TYPE_UNSPECIFIED",
		1: "SLUG_TYPE_PRIMARY",
		2: "SLUG_TYPE_OUTDATED",
		3: "SLUG_TYPE_CUSTOM",
	}
	SlugType_value = map[string]int32{
		"SLUG_TYPE_UNSPECIFIED": 0,
		"SLUG_TYPE_PRIMARY":     1,
		"SLUG_TYPE_OUTDATED":    2,
		"SLUG_TYPE_CUSTOM":      3,
	}
)

func (x SlugType) Enum() *SlugType {
	p := new(SlugType)
	*p = x
	return p
}

func (x SlugType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SlugType) Descriptor() protoreflect.EnumDescriptor {
	return file_models_slug_proto_enumTypes[0].Descriptor()
}

func (SlugType) Type() protoreflect.EnumType {
	return &file_models_slug_proto_enumTypes[0]
}

func (x SlugType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SlugType.Descriptor instead.
func (SlugType) EnumDescriptor() ([]byte, []int) {
	return file_models_slug_proto_rawDescGZIP(), []int{0}
}

// Slug represents a URL-friendly identifier for an entity.
type Slug struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The URL slug string.
	Slug string `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	// Type classification for this slug.
	Type          SlugType `protobuf:"varint,2,opt,name=type,proto3,enum=parrygg.models.SlugType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Slug) Reset() {
	*x = Slug{}
	mi := &file_models_slug_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Slug) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Slug) ProtoMessage() {}

func (x *Slug) ProtoReflect() protoreflect.Message {
	mi := &file_models_slug_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Slug.ProtoReflect.Descriptor instead.
func (*Slug) Descriptor() ([]byte, []int) {
	return file_models_slug_proto_rawDescGZIP(), []int{0}
}

func (x *Slug) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *Slug) GetType() SlugType {
	if x != nil {
		return x.Type
	}
	return SlugType_SLUG_TYPE_UNSPECIFIED
}

// MutableSlug allows updating slug information.
type MutableSlug struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Updated slug string.
	Slug string `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	// Updated slug type.
	Type          SlugType `protobuf:"varint,2,opt,name=type,proto3,enum=parrygg.models.SlugType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MutableSlug) Reset() {
	*x = MutableSlug{}
	mi := &file_models_slug_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MutableSlug) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MutableSlug) ProtoMessage() {}

func (x *MutableSlug) ProtoReflect() protoreflect.Message {
	mi := &file_models_slug_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MutableSlug.ProtoReflect.Descriptor instead.
func (*MutableSlug) Descriptor() ([]byte, []int) {
	return file_models_slug_proto_rawDescGZIP(), []int{1}
}

func (x *MutableSlug) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *MutableSlug) GetType() SlugType {
	if x != nil {
		return x.Type
	}
	return SlugType_SLUG_TYPE_UNSPECIFIED
}

var File_models_slug_proto protoreflect.FileDescriptor

const file_models_slug_proto_rawDesc = "" +
	"\n" +
	"\x11models/slug.proto\x12\x0eparrygg.models\"H\n" +
	"\x04Slug\x12\x12\n" +
	"\x04slug\x18\x01 \x01(\tR\x04slug\x12,\n" +
	"\x04type\x18\x02 \x01(\x0e2\x18.parrygg.models.SlugTypeR\x04type\"O\n" +
	"\vMutableSlug\x12\x12\n" +
	"\x04slug\x18\x01 \x01(\tR\x04slug\x12,\n" +
	"\x04type\x18\x02 \x01(\x0e2\x18.parrygg.models.SlugTypeR\x04type*j\n" +
	"\bSlugType\x12\x19\n" +
	"\x15SLUG_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11SLUG_TYPE_PRIMARY\x10\x01\x12\x16\n" +
	"\x12SLUG_TYPE_OUTDATED\x10\x02\x12\x14\n" +
	"\x10SLUG_TYPE_CUSTOM\x10\x03BA\n" +
	"\x14gg.parry.grpc.modelsP\x01Z'github.com/AaronLieb/octagon/parrygg/pbb\x06proto3"

var (
	file_models_slug_proto_rawDescOnce sync.Once
	file_models_slug_proto_rawDescData []byte
)

func file_models_slug_proto_rawDescGZIP() []byte {
	file_models_slug_proto_rawDescOnce.Do(func() {
		file_models_slug_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_models_slug_proto_rawDesc), len(file_models_slug_proto_rawDesc)))
	})
	return file_models_slug_proto_rawDescData
}

var file_models_slug_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_models_slug_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_models_slug_proto_goTypes = []any{
	(SlugType)(0),       // 0: parrygg.models.SlugType
	(*Slug)(nil),        // 1: parrygg.models.Slug
	(*MutableSlug)(nil), // 2: parrygg.models.MutableSlug
}
var file_models_slug_proto_depIdxs = []int32{
	0, // 0: parrygg.models.Slug.type:type_name -> parrygg.models.SlugType
	0, // 1: parrygg.models.MutableSlug.type:type_name -> parrygg.models.SlugType
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_models_slug_proto_init() }
func file_models_slug_proto_init() {
	if File_models_slug_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_models_slug_proto_rawDesc), len(file_models_slug_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_models_slug_proto_goTypes,
		DependencyIndexes: file_models_slug_proto_depIdxs,
		EnumInfos:         file_models_slug_proto_enumTypes,
		MessageInfos:      file_models_slug_proto_msgTypes,
	}.Build()
	File_models_slug_proto = out.File
	file_models_slug_proto_goTypes = nil
	file_models_slug_proto_depIdxs = nil
}
