// Tournament management and organization system.
// Core tournament entities with events, registration, administration, and content management.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: models/tournament.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TournamentState represents the current lifecycle state of a tournament.
type TournamentState int32

const (
	// Default unspecified state.
	TournamentState_TOURNAMENT_STATE_UNSPECIFIED TournamentState = 0
	// Tournament created but not yet ready for registration.
	TournamentState_TOURNAMENT_STATE_PENDING TournamentState = 1
	// Tournament ready for registration and participation.
	TournamentState_TOURNAMENT_STATE_READY TournamentState = 2
	// Tournament currently running with active events.
	TournamentState_TOURNAMENT_STATE_IN_PROGRESS TournamentState = 3
	// Tournament completed with final results.
	TournamentState_TOURNAMENT_STATE_COMPLETED TournamentState = 4
)

// Enum value maps for TournamentState.
var (
	TournamentState_name = map[int32]string{
		0: "TOURNAMENT_STATE_UNSPECIFIED",
		1: "TOURNAMENT_STATE_PENDING",
		2: "TOURNAMENT_STATE_READY",
		3: "TOURNAMENT_STATE_IN_PROGRESS",
		4: "TOURNAMENT_STATE_COMPLETED",
	}
	TournamentState_value = map[string]int32{
		"TOURNAMENT_STATE_UNSPECIFIED": 0,
		"TOURNAMENT_STATE_PENDING":     1,
		"TOURNAMENT_STATE_READY":       2,
		"TOURNAMENT_STATE_IN_PROGRESS": 3,
		"TOURNAMENT_STATE_COMPLETED":   4,
	}
)

func (x TournamentState) Enum() *TournamentState {
	p := new(TournamentState)
	*p = x
	return p
}

func (x TournamentState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TournamentState) Descriptor() protoreflect.EnumDescriptor {
	return file_models_tournament_proto_enumTypes[0].Descriptor()
}

func (TournamentState) Type() protoreflect.EnumType {
	return &file_models_tournament_proto_enumTypes[0]
}

func (x TournamentState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TournamentState.Descriptor instead.
func (TournamentState) EnumDescriptor() ([]byte, []int) {
	return file_models_tournament_proto_rawDescGZIP(), []int{0}
}

// TournamentPermission defines administrative access levels for tournaments.
type TournamentPermission int32

const (
	// Default unspecified permission level.
	TournamentPermission_PERMISSION_LEVEL_UNSPECIFIED TournamentPermission = 0
	// Full administrative access to tournament.
	TournamentPermission_PERMISSION_LEVEL_ADMIN TournamentPermission = 1
	// Management access with most administrative privileges.
	TournamentPermission_PERMISSION_LEVEL_MANAGER TournamentPermission = 2
	// Reporting access for match updates and results.
	TournamentPermission_PERMISSION_LEVEL_REPORTER TournamentPermission = 3
)

// Enum value maps for TournamentPermission.
var (
	TournamentPermission_name = map[int32]string{
		0: "PERMISSION_LEVEL_UNSPECIFIED",
		1: "PERMISSION_LEVEL_ADMIN",
		2: "PERMISSION_LEVEL_MANAGER",
		3: "PERMISSION_LEVEL_REPORTER",
	}
	TournamentPermission_value = map[string]int32{
		"PERMISSION_LEVEL_UNSPECIFIED": 0,
		"PERMISSION_LEVEL_ADMIN":       1,
		"PERMISSION_LEVEL_MANAGER":     2,
		"PERMISSION_LEVEL_REPORTER":    3,
	}
)

func (x TournamentPermission) Enum() *TournamentPermission {
	p := new(TournamentPermission)
	*p = x
	return p
}

func (x TournamentPermission) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TournamentPermission) Descriptor() protoreflect.EnumDescriptor {
	return file_models_tournament_proto_enumTypes[1].Descriptor()
}

func (TournamentPermission) Type() protoreflect.EnumType {
	return &file_models_tournament_proto_enumTypes[1]
}

func (x TournamentPermission) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TournamentPermission.Descriptor instead.
func (TournamentPermission) EnumDescriptor() ([]byte, []int) {
	return file_models_tournament_proto_rawDescGZIP(), []int{1}
}

// VisibilityLevel determines who can view and access a tournament.
type VisibilityLevel int32

const (
	// Unspecified visibility level.
	VisibilityLevel_VISIBILITY_LEVEL_UNSPECIFIED VisibilityLevel = 0
	// Public tournaments have no restrictions, and can be seen by anyone.
	VisibilityLevel_VISIBILITY_LEVEL_PUBLIC VisibilityLevel = 1
	// Link-Only tournaments can be opened from a direct link, but will not appear in searches or lists.
	VisibilityLevel_VISIBILITY_LEVEL_LINK_ONLY VisibilityLevel = 2
	// Hidden tournaments can only be seen by their admins and competitors.
	VisibilityLevel_VISIBILITY_LEVEL_HIDDEN VisibilityLevel = 3
)

// Enum value maps for VisibilityLevel.
var (
	VisibilityLevel_name = map[int32]string{
		0: "VISIBILITY_LEVEL_UNSPECIFIED",
		1: "VISIBILITY_LEVEL_PUBLIC",
		2: "VISIBILITY_LEVEL_LINK_ONLY",
		3: "VISIBILITY_LEVEL_HIDDEN",
	}
	VisibilityLevel_value = map[string]int32{
		"VISIBILITY_LEVEL_UNSPECIFIED": 0,
		"VISIBILITY_LEVEL_PUBLIC":      1,
		"VISIBILITY_LEVEL_LINK_ONLY":   2,
		"VISIBILITY_LEVEL_HIDDEN":      3,
	}
)

func (x VisibilityLevel) Enum() *VisibilityLevel {
	p := new(VisibilityLevel)
	*p = x
	return p
}

func (x VisibilityLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VisibilityLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_models_tournament_proto_enumTypes[2].Descriptor()
}

func (VisibilityLevel) Type() protoreflect.EnumType {
	return &file_models_tournament_proto_enumTypes[2]
}

func (x VisibilityLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VisibilityLevel.Descriptor instead.
func (VisibilityLevel) EnumDescriptor() ([]byte, []int) {
	return file_models_tournament_proto_rawDescGZIP(), []int{2}
}

// Tournament represents a competitive gaming tournament with multiple events.
// Contains all tournament metadata, events, and administrative information.
// Next id: 26
type Tournament struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier for the tournament (UUID v7).
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Full display name of the tournament.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Abbreviated name for compact displays.
	ShortName string `protobuf:"bytes,3,opt,name=short_name,json=shortName,proto3" json:"short_name,omitempty"`
	// Physical address where the tournament takes place.
	VenueAddress string `protobuf:"bytes,4,opt,name=venue_address,json=venueAddress,proto3" json:"venue_address,omitempty"`
	// Contact information for tournament administration.
	AdminContact string `protobuf:"bytes,7,opt,name=admin_contact,json=adminContact,proto3" json:"admin_contact,omitempty"`
	// Currency code for all monetary values (e.g., "USD").
	CurrencyCode string `protobuf:"bytes,8,opt,name=currency_code,json=currencyCode,proto3" json:"currency_code,omitempty"`
	// When the tournament begins.
	StartDate *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	// When the tournament ends.
	EndDate *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	// Current lifecycle state of the tournament.
	State TournamentState `protobuf:"varint,11,opt,name=state,proto3,enum=parrygg.models.TournamentState" json:"state,omitempty"`
	// Images associated with the tournament (banners, logos, etc.).
	Images []*Image `protobuf:"bytes,12,rep,name=images,proto3" json:"images,omitempty"`
	// Competition events within this tournament.
	Events []*Event `protobuf:"bytes,13,rep,name=events,proto3" json:"events,omitempty"`
	// Total number of registered attendees (derived value).
	NumAttendees int32 `protobuf:"varint,14,opt,name=num_attendees,json=numAttendees,proto3" json:"num_attendees,omitempty"`
	// ID of the user who owns/organizes this tournament.
	OwnerId string `protobuf:"bytes,15,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	// URL slugs for accessing this tournament.
	Slugs []*Slug `protobuf:"bytes,16,rep,name=slugs,proto3" json:"slugs,omitempty"`
	// Entry fee for tournament attendance in cents.
	VenueFee int32 `protobuf:"varint,17,opt,name=venue_fee,json=venueFee,proto3" json:"venue_fee,omitempty"`
	// Time zone for tournament scheduling (e.g., "America/New_York").
	TimeZone string `protobuf:"bytes,18,opt,name=time_zone,json=timeZone,proto3" json:"time_zone,omitempty"`
	// Visibility status of this tournament.
	VisibilityLevel VisibilityLevel `protobuf:"varint,19,opt,name=visibility_level,json=visibilityLevel,proto3,enum=parrygg.models.VisibilityLevel" json:"visibility_level,omitempty"`
	// Structured geocoded address information for the venue.
	Address *Address `protobuf:"bytes,20,opt,name=address,proto3,oneof" json:"address,omitempty"`
	// Location type for the tournament (e.g. Online, offline)
	LocationType LocationType `protobuf:"varint,21,opt,name=location_type,json=locationType,proto3,enum=parrygg.models.LocationType" json:"location_type,omitempty"`
	// Set time for registration to open.
	RegistrationStartDate *timestamppb.Timestamp `protobuf:"bytes,22,opt,name=registration_start_date,json=registrationStartDate,proto3" json:"registration_start_date,omitempty"`
	// Deadline for registration to close.
	RegistrationEndDate *timestamppb.Timestamp `protobuf:"bytes,23,opt,name=registration_end_date,json=registrationEndDate,proto3" json:"registration_end_date,omitempty"`
	// When this tournament record was created.
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,24,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// When this tournament record was last updated.
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,25,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tournament) Reset() {
	*x = Tournament{}
	mi := &file_models_tournament_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tournament) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tournament) ProtoMessage() {}

func (x *Tournament) ProtoReflect() protoreflect.Message {
	mi := &file_models_tournament_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tournament.ProtoReflect.Descriptor instead.
func (*Tournament) Descriptor() ([]byte, []int) {
	return file_models_tournament_proto_rawDescGZIP(), []int{0}
}

func (x *Tournament) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Tournament) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Tournament) GetShortName() string {
	if x != nil {
		return x.ShortName
	}
	return ""
}

func (x *Tournament) GetVenueAddress() string {
	if x != nil {
		return x.VenueAddress
	}
	return ""
}

func (x *Tournament) GetAdminContact() string {
	if x != nil {
		return x.AdminContact
	}
	return ""
}

func (x *Tournament) GetCurrencyCode() string {
	if x != nil {
		return x.CurrencyCode
	}
	return ""
}

func (x *Tournament) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *Tournament) GetEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

func (x *Tournament) GetState() TournamentState {
	if x != nil {
		return x.State
	}
	return TournamentState_TOURNAMENT_STATE_UNSPECIFIED
}

func (x *Tournament) GetImages() []*Image {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *Tournament) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *Tournament) GetNumAttendees() int32 {
	if x != nil {
		return x.NumAttendees
	}
	return 0
}

func (x *Tournament) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *Tournament) GetSlugs() []*Slug {
	if x != nil {
		return x.Slugs
	}
	return nil
}

func (x *Tournament) GetVenueFee() int32 {
	if x != nil {
		return x.VenueFee
	}
	return 0
}

func (x *Tournament) GetTimeZone() string {
	if x != nil {
		return x.TimeZone
	}
	return ""
}

func (x *Tournament) GetVisibilityLevel() VisibilityLevel {
	if x != nil {
		return x.VisibilityLevel
	}
	return VisibilityLevel_VISIBILITY_LEVEL_UNSPECIFIED
}

func (x *Tournament) GetAddress() *Address {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *Tournament) GetLocationType() LocationType {
	if x != nil {
		return x.LocationType
	}
	return LocationType_LOCATION_TYPE_UNSPECIFIED
}

func (x *Tournament) GetRegistrationStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.RegistrationStartDate
	}
	return nil
}

func (x *Tournament) GetRegistrationEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.RegistrationEndDate
	}
	return nil
}

func (x *Tournament) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Tournament) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// TournamentMutation updates mutable fields of a tournament.
// Subset of Tournament with fields that may be mutated by a request.
// Next id: 17
type TournamentMutation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Updated tournament name.
	Name *string `protobuf:"bytes,1,opt,name=name,proto3,oneof" json:"name,omitempty"`
	// Updated short name.
	ShortName *string `protobuf:"bytes,2,opt,name=short_name,json=shortName,proto3,oneof" json:"short_name,omitempty"`
	// Updated venue address.
	VenueAddress *string `protobuf:"bytes,3,opt,name=venue_address,json=venueAddress,proto3,oneof" json:"venue_address,omitempty"`
	// Updated admin contact information.
	AdminContact *string `protobuf:"bytes,6,opt,name=admin_contact,json=adminContact,proto3,oneof" json:"admin_contact,omitempty"`
	// Updated currency code.
	CurrencyCode *string `protobuf:"bytes,7,opt,name=currency_code,json=currencyCode,proto3,oneof" json:"currency_code,omitempty"`
	// Updated start date.
	StartDate *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=start_date,json=startDate,proto3,oneof" json:"start_date,omitempty"`
	// Updated end date.
	EndDate *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=end_date,json=endDate,proto3,oneof" json:"end_date,omitempty"`
	// Updated owner ID.
	OwnerId *string `protobuf:"bytes,10,opt,name=owner_id,json=ownerId,proto3,oneof" json:"owner_id,omitempty"`
	// Updated venue fee in cents.
	VenueFee *int32 `protobuf:"varint,11,opt,name=venue_fee,json=venueFee,proto3,oneof" json:"venue_fee,omitempty"`
	// Updated time zone.
	TimeZone *string `protobuf:"bytes,12,opt,name=time_zone,json=timeZone,proto3,oneof" json:"time_zone,omitempty"`
	// Updated visibility status.
	VisibilityLevel *VisibilityLevel `protobuf:"varint,13,opt,name=visibility_level,json=visibilityLevel,proto3,enum=parrygg.models.VisibilityLevel,oneof" json:"visibility_level,omitempty"`
	// Updated location type.
	LocationType *LocationType `protobuf:"varint,14,opt,name=location_type,json=locationType,proto3,enum=parrygg.models.LocationType,oneof" json:"location_type,omitempty"`
	// Updated time for registration to open.
	RegistrationStartDate *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=registration_start_date,json=registrationStartDate,proto3,oneof" json:"registration_start_date,omitempty"`
	// Updated deadline for registration to close.
	RegistrationEndDate *timestamppb.Timestamp `protobuf:"bytes,16,opt,name=registration_end_date,json=registrationEndDate,proto3,oneof" json:"registration_end_date,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *TournamentMutation) Reset() {
	*x = TournamentMutation{}
	mi := &file_models_tournament_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TournamentMutation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TournamentMutation) ProtoMessage() {}

func (x *TournamentMutation) ProtoReflect() protoreflect.Message {
	mi := &file_models_tournament_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TournamentMutation.ProtoReflect.Descriptor instead.
func (*TournamentMutation) Descriptor() ([]byte, []int) {
	return file_models_tournament_proto_rawDescGZIP(), []int{1}
}

func (x *TournamentMutation) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *TournamentMutation) GetShortName() string {
	if x != nil && x.ShortName != nil {
		return *x.ShortName
	}
	return ""
}

func (x *TournamentMutation) GetVenueAddress() string {
	if x != nil && x.VenueAddress != nil {
		return *x.VenueAddress
	}
	return ""
}

func (x *TournamentMutation) GetAdminContact() string {
	if x != nil && x.AdminContact != nil {
		return *x.AdminContact
	}
	return ""
}

func (x *TournamentMutation) GetCurrencyCode() string {
	if x != nil && x.CurrencyCode != nil {
		return *x.CurrencyCode
	}
	return ""
}

func (x *TournamentMutation) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *TournamentMutation) GetEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

func (x *TournamentMutation) GetOwnerId() string {
	if x != nil && x.OwnerId != nil {
		return *x.OwnerId
	}
	return ""
}

func (x *TournamentMutation) GetVenueFee() int32 {
	if x != nil && x.VenueFee != nil {
		return *x.VenueFee
	}
	return 0
}

func (x *TournamentMutation) GetTimeZone() string {
	if x != nil && x.TimeZone != nil {
		return *x.TimeZone
	}
	return ""
}

func (x *TournamentMutation) GetVisibilityLevel() VisibilityLevel {
	if x != nil && x.VisibilityLevel != nil {
		return *x.VisibilityLevel
	}
	return VisibilityLevel_VISIBILITY_LEVEL_UNSPECIFIED
}

func (x *TournamentMutation) GetLocationType() LocationType {
	if x != nil && x.LocationType != nil {
		return *x.LocationType
	}
	return LocationType_LOCATION_TYPE_UNSPECIFIED
}

func (x *TournamentMutation) GetRegistrationStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.RegistrationStartDate
	}
	return nil
}

func (x *TournamentMutation) GetRegistrationEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.RegistrationEndDate
	}
	return nil
}

// PageContent represents custom content pages for tournaments.
// Next id: 5
type PageContent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier for the page content (UUID v7).
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Display order index for page navigation.
	Index int32 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	// Page title for navigation and display.
	Title string `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	// Markdown-formatted page content.
	ContentMd     string `protobuf:"bytes,4,opt,name=content_md,json=contentMd,proto3" json:"content_md,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageContent) Reset() {
	*x = PageContent{}
	mi := &file_models_tournament_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageContent) ProtoMessage() {}

func (x *PageContent) ProtoReflect() protoreflect.Message {
	mi := &file_models_tournament_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageContent.ProtoReflect.Descriptor instead.
func (*PageContent) Descriptor() ([]byte, []int) {
	return file_models_tournament_proto_rawDescGZIP(), []int{2}
}

func (x *PageContent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PageContent) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *PageContent) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PageContent) GetContentMd() string {
	if x != nil {
		return x.ContentMd
	}
	return ""
}

// MutablePageContent updates editable fields of page content.
// Subset of PageContent with fields that may be mutated by a request.
// Next id: 4
type MutablePageContent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Updated display order index.
	Index *int32 `protobuf:"varint,1,opt,name=index,proto3,oneof" json:"index,omitempty"`
	// Updated page title.
	Title *string `protobuf:"bytes,2,opt,name=title,proto3,oneof" json:"title,omitempty"`
	// Updated markdown content.
	ContentMd     *string `protobuf:"bytes,3,opt,name=content_md,json=contentMd,proto3,oneof" json:"content_md,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MutablePageContent) Reset() {
	*x = MutablePageContent{}
	mi := &file_models_tournament_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MutablePageContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MutablePageContent) ProtoMessage() {}

func (x *MutablePageContent) ProtoReflect() protoreflect.Message {
	mi := &file_models_tournament_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MutablePageContent.ProtoReflect.Descriptor instead.
func (*MutablePageContent) Descriptor() ([]byte, []int) {
	return file_models_tournament_proto_rawDescGZIP(), []int{3}
}

func (x *MutablePageContent) GetIndex() int32 {
	if x != nil && x.Index != nil {
		return *x.Index
	}
	return 0
}

func (x *MutablePageContent) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *MutablePageContent) GetContentMd() string {
	if x != nil && x.ContentMd != nil {
		return *x.ContentMd
	}
	return ""
}

// TournamentRegistration tracks a user's registration for a tournament.
// Next id: 6
type TournamentRegistration struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the tournament being registered for.
	TournamentId string `protobuf:"bytes,1,opt,name=tournament_id,json=tournamentId,proto3" json:"tournament_id,omitempty"`
	// Whether the user has paid the venue fee.
	PaidVenueFee bool `protobuf:"varint,3,opt,name=paid_venue_fee,json=paidVenueFee,proto3" json:"paid_venue_fee,omitempty"`
	// Registration details for individual events.
	EventRegistrations []*EventRegistration `protobuf:"bytes,4,rep,name=event_registrations,json=eventRegistrations,proto3" json:"event_registrations,omitempty"`
	// The user who is registered.
	User          *User `protobuf:"bytes,5,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TournamentRegistration) Reset() {
	*x = TournamentRegistration{}
	mi := &file_models_tournament_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TournamentRegistration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TournamentRegistration) ProtoMessage() {}

func (x *TournamentRegistration) ProtoReflect() protoreflect.Message {
	mi := &file_models_tournament_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TournamentRegistration.ProtoReflect.Descriptor instead.
func (*TournamentRegistration) Descriptor() ([]byte, []int) {
	return file_models_tournament_proto_rawDescGZIP(), []int{4}
}

func (x *TournamentRegistration) GetTournamentId() string {
	if x != nil {
		return x.TournamentId
	}
	return ""
}

func (x *TournamentRegistration) GetPaidVenueFee() bool {
	if x != nil {
		return x.PaidVenueFee
	}
	return false
}

func (x *TournamentRegistration) GetEventRegistrations() []*EventRegistration {
	if x != nil {
		return x.EventRegistrations
	}
	return nil
}

func (x *TournamentRegistration) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

// TournamentRegistrationMutation updates registration details.
// Subset of TournamentRegistration with fields that may be mutated by a request.
// Next id: 4
type TournamentRegistrationMutation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Updated venue fee payment status.
	PaidVenueFee *bool `protobuf:"varint,1,opt,name=paid_venue_fee,json=paidVenueFee,proto3,oneof" json:"paid_venue_fee,omitempty"`
	// Updated event registration details.
	EventRegistrations []*EventRegistrationMutation `protobuf:"bytes,2,rep,name=event_registrations,json=eventRegistrations,proto3" json:"event_registrations,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *TournamentRegistrationMutation) Reset() {
	*x = TournamentRegistrationMutation{}
	mi := &file_models_tournament_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TournamentRegistrationMutation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TournamentRegistrationMutation) ProtoMessage() {}

func (x *TournamentRegistrationMutation) ProtoReflect() protoreflect.Message {
	mi := &file_models_tournament_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TournamentRegistrationMutation.ProtoReflect.Descriptor instead.
func (*TournamentRegistrationMutation) Descriptor() ([]byte, []int) {
	return file_models_tournament_proto_rawDescGZIP(), []int{5}
}

func (x *TournamentRegistrationMutation) GetPaidVenueFee() bool {
	if x != nil && x.PaidVenueFee != nil {
		return *x.PaidVenueFee
	}
	return false
}

func (x *TournamentRegistrationMutation) GetEventRegistrations() []*EventRegistrationMutation {
	if x != nil {
		return x.EventRegistrations
	}
	return nil
}

// BatchTournamentRegistrationMutation mutates a single users registration in the context of a larger batch.
// Next id: 3
type BatchTournamentRegistrationMutation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the user whose registration to update.
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Registration updates to apply.
	Registration  *TournamentRegistrationMutation `protobuf:"bytes,2,opt,name=registration,proto3" json:"registration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchTournamentRegistrationMutation) Reset() {
	*x = BatchTournamentRegistrationMutation{}
	mi := &file_models_tournament_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchTournamentRegistrationMutation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchTournamentRegistrationMutation) ProtoMessage() {}

func (x *BatchTournamentRegistrationMutation) ProtoReflect() protoreflect.Message {
	mi := &file_models_tournament_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchTournamentRegistrationMutation.ProtoReflect.Descriptor instead.
func (*BatchTournamentRegistrationMutation) Descriptor() ([]byte, []int) {
	return file_models_tournament_proto_rawDescGZIP(), []int{6}
}

func (x *BatchTournamentRegistrationMutation) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *BatchTournamentRegistrationMutation) GetRegistration() *TournamentRegistrationMutation {
	if x != nil {
		return x.Registration
	}
	return nil
}

// TournamentAttendee represents public information about tournament participation.
// Information the client would show one user about other users' registration - e.g. which events, but not payment status.
type TournamentAttendee struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The attending user's public information.
	User *User `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	// Events the user is attending (without payment details).
	Events        []*EventAttendance `protobuf:"bytes,2,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TournamentAttendee) Reset() {
	*x = TournamentAttendee{}
	mi := &file_models_tournament_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TournamentAttendee) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TournamentAttendee) ProtoMessage() {}

func (x *TournamentAttendee) ProtoReflect() protoreflect.Message {
	mi := &file_models_tournament_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TournamentAttendee.ProtoReflect.Descriptor instead.
func (*TournamentAttendee) Descriptor() ([]byte, []int) {
	return file_models_tournament_proto_rawDescGZIP(), []int{7}
}

func (x *TournamentAttendee) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *TournamentAttendee) GetEvents() []*EventAttendance {
	if x != nil {
		return x.Events
	}
	return nil
}

// TournamentAdmin represents administrative access information.
// Publicly visible information about a user/group in the ADMINS group for a tournament.
type TournamentAdmin struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The administrative member (user or group).
	//
	// Types that are valid to be assigned to Member:
	//
	//	*TournamentAdmin_User
	//	*TournamentAdmin_Group
	Member isTournamentAdmin_Member `protobuf_oneof:"member"`
	// Permission level for this admin.
	Permission    TournamentPermission `protobuf:"varint,3,opt,name=permission,proto3,enum=parrygg.models.TournamentPermission" json:"permission,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TournamentAdmin) Reset() {
	*x = TournamentAdmin{}
	mi := &file_models_tournament_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TournamentAdmin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TournamentAdmin) ProtoMessage() {}

func (x *TournamentAdmin) ProtoReflect() protoreflect.Message {
	mi := &file_models_tournament_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TournamentAdmin.ProtoReflect.Descriptor instead.
func (*TournamentAdmin) Descriptor() ([]byte, []int) {
	return file_models_tournament_proto_rawDescGZIP(), []int{8}
}

func (x *TournamentAdmin) GetMember() isTournamentAdmin_Member {
	if x != nil {
		return x.Member
	}
	return nil
}

func (x *TournamentAdmin) GetUser() *User {
	if x != nil {
		if x, ok := x.Member.(*TournamentAdmin_User); ok {
			return x.User
		}
	}
	return nil
}

func (x *TournamentAdmin) GetGroup() *Group {
	if x != nil {
		if x, ok := x.Member.(*TournamentAdmin_Group); ok {
			return x.Group
		}
	}
	return nil
}

func (x *TournamentAdmin) GetPermission() TournamentPermission {
	if x != nil {
		return x.Permission
	}
	return TournamentPermission_PERMISSION_LEVEL_UNSPECIFIED
}

type isTournamentAdmin_Member interface {
	isTournamentAdmin_Member()
}

type TournamentAdmin_User struct {
	// Individual user with admin access.
	User *User `protobuf:"bytes,1,opt,name=user,proto3,oneof"`
}

type TournamentAdmin_Group struct {
	// Group with admin access.
	Group *Group `protobuf:"bytes,2,opt,name=group,proto3,oneof"`
}

func (*TournamentAdmin_User) isTournamentAdmin_Member() {}

func (*TournamentAdmin_Group) isTournamentAdmin_Member() {}

// TournamentIdentifier allows referencing a tournament by ID or slug.
type TournamentIdentifier struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Identifier:
	//
	//	*TournamentIdentifier_Id
	//	*TournamentIdentifier_TournamentSlug
	Identifier    isTournamentIdentifier_Identifier `protobuf_oneof:"identifier"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TournamentIdentifier) Reset() {
	*x = TournamentIdentifier{}
	mi := &file_models_tournament_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TournamentIdentifier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TournamentIdentifier) ProtoMessage() {}

func (x *TournamentIdentifier) ProtoReflect() protoreflect.Message {
	mi := &file_models_tournament_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TournamentIdentifier.ProtoReflect.Descriptor instead.
func (*TournamentIdentifier) Descriptor() ([]byte, []int) {
	return file_models_tournament_proto_rawDescGZIP(), []int{9}
}

func (x *TournamentIdentifier) GetIdentifier() isTournamentIdentifier_Identifier {
	if x != nil {
		return x.Identifier
	}
	return nil
}

func (x *TournamentIdentifier) GetId() string {
	if x != nil {
		if x, ok := x.Identifier.(*TournamentIdentifier_Id); ok {
			return x.Id
		}
	}
	return ""
}

func (x *TournamentIdentifier) GetTournamentSlug() string {
	if x != nil {
		if x, ok := x.Identifier.(*TournamentIdentifier_TournamentSlug); ok {
			return x.TournamentSlug
		}
	}
	return ""
}

type isTournamentIdentifier_Identifier interface {
	isTournamentIdentifier_Identifier()
}

type TournamentIdentifier_Id struct {
	// Direct tournament ID lookup.
	Id string `protobuf:"bytes,1,opt,name=id,proto3,oneof"`
}

type TournamentIdentifier_TournamentSlug struct {
	// Tournament slug lookup.
	TournamentSlug string `protobuf:"bytes,2,opt,name=tournament_slug,json=tournamentSlug,proto3,oneof"`
}

func (*TournamentIdentifier_Id) isTournamentIdentifier_Identifier() {}

func (*TournamentIdentifier_TournamentSlug) isTournamentIdentifier_Identifier() {}

// TournamentPermissionsMetadata contains permission information for a user.
type TournamentPermissionsMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The user's permission level for the tournament.
	TournamentPermission TournamentPermission `protobuf:"varint,1,opt,name=tournament_permission,json=tournamentPermission,proto3,enum=parrygg.models.TournamentPermission" json:"tournament_permission,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *TournamentPermissionsMetadata) Reset() {
	*x = TournamentPermissionsMetadata{}
	mi := &file_models_tournament_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TournamentPermissionsMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TournamentPermissionsMetadata) ProtoMessage() {}

func (x *TournamentPermissionsMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_models_tournament_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TournamentPermissionsMetadata.ProtoReflect.Descriptor instead.
func (*TournamentPermissionsMetadata) Descriptor() ([]byte, []int) {
	return file_models_tournament_proto_rawDescGZIP(), []int{10}
}

func (x *TournamentPermissionsMetadata) GetTournamentPermission() TournamentPermission {
	if x != nil {
		return x.TournamentPermission
	}
	return TournamentPermission_PERMISSION_LEVEL_UNSPECIFIED
}

var File_models_tournament_proto protoreflect.FileDescriptor

const file_models_tournament_proto_rawDesc = "" +
	"\n" +
	"\x17models/tournament.proto\x12\x0eparrygg.models\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x14models/address.proto\x1a\x12models/image.proto\x1a\x12models/event.proto\x1a\x12models/group.proto\x1a\x11models/slug.proto\x1a\x11models/user.proto\"\xd8\b\n" +
	"\n" +
	"Tournament\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"short_name\x18\x03 \x01(\tR\tshortName\x12#\n" +
	"\rvenue_address\x18\x04 \x01(\tR\fvenueAddress\x12#\n" +
	"\radmin_contact\x18\a \x01(\tR\fadminContact\x12#\n" +
	"\rcurrency_code\x18\b \x01(\tR\fcurrencyCode\x129\n" +
	"\n" +
	"start_date\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tstartDate\x125\n" +
	"\bend_date\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\aendDate\x125\n" +
	"\x05state\x18\v \x01(\x0e2\x1f.parrygg.models.TournamentStateR\x05state\x12-\n" +
	"\x06images\x18\f \x03(\v2\x15.parrygg.models.ImageR\x06images\x12-\n" +
	"\x06events\x18\r \x03(\v2\x15.parrygg.models.EventR\x06events\x12#\n" +
	"\rnum_attendees\x18\x0e \x01(\x05R\fnumAttendees\x12\x19\n" +
	"\bowner_id\x18\x0f \x01(\tR\aownerId\x12*\n" +
	"\x05slugs\x18\x10 \x03(\v2\x14.parrygg.models.SlugR\x05slugs\x12\x1b\n" +
	"\tvenue_fee\x18\x11 \x01(\x05R\bvenueFee\x12\x1b\n" +
	"\ttime_zone\x18\x12 \x01(\tR\btimeZone\x12J\n" +
	"\x10visibility_level\x18\x13 \x01(\x0e2\x1f.parrygg.models.VisibilityLevelR\x0fvisibilityLevel\x126\n" +
	"\aaddress\x18\x14 \x01(\v2\x17.parrygg.models.AddressH\x00R\aaddress\x88\x01\x01\x12A\n" +
	"\rlocation_type\x18\x15 \x01(\x0e2\x1c.parrygg.models.LocationTypeR\flocationType\x12R\n" +
	"\x17registration_start_date\x18\x16 \x01(\v2\x1a.google.protobuf.TimestampR\x15registrationStartDate\x12N\n" +
	"\x15registration_end_date\x18\x17 \x01(\v2\x1a.google.protobuf.TimestampR\x13registrationEndDate\x129\n" +
	"\n" +
	"created_at\x18\x18 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x19 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtB\n" +
	"\n" +
	"\b_address\"\xe6\a\n" +
	"\x12TournamentMutation\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tH\x00R\x04name\x88\x01\x01\x12\"\n" +
	"\n" +
	"short_name\x18\x02 \x01(\tH\x01R\tshortName\x88\x01\x01\x12(\n" +
	"\rvenue_address\x18\x03 \x01(\tH\x02R\fvenueAddress\x88\x01\x01\x12(\n" +
	"\radmin_contact\x18\x06 \x01(\tH\x03R\fadminContact\x88\x01\x01\x12(\n" +
	"\rcurrency_code\x18\a \x01(\tH\x04R\fcurrencyCode\x88\x01\x01\x12>\n" +
	"\n" +
	"start_date\x18\b \x01(\v2\x1a.google.protobuf.TimestampH\x05R\tstartDate\x88\x01\x01\x12:\n" +
	"\bend_date\x18\t \x01(\v2\x1a.google.protobuf.TimestampH\x06R\aendDate\x88\x01\x01\x12\x1e\n" +
	"\bowner_id\x18\n" +
	" \x01(\tH\aR\aownerId\x88\x01\x01\x12 \n" +
	"\tvenue_fee\x18\v \x01(\x05H\bR\bvenueFee\x88\x01\x01\x12 \n" +
	"\ttime_zone\x18\f \x01(\tH\tR\btimeZone\x88\x01\x01\x12O\n" +
	"\x10visibility_level\x18\r \x01(\x0e2\x1f.parrygg.models.VisibilityLevelH\n" +
	"R\x0fvisibilityLevel\x88\x01\x01\x12F\n" +
	"\rlocation_type\x18\x0e \x01(\x0e2\x1c.parrygg.models.LocationTypeH\vR\flocationType\x88\x01\x01\x12W\n" +
	"\x17registration_start_date\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampH\fR\x15registrationStartDate\x88\x01\x01\x12S\n" +
	"\x15registration_end_date\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampH\rR\x13registrationEndDate\x88\x01\x01B\a\n" +
	"\x05_nameB\r\n" +
	"\v_short_nameB\x10\n" +
	"\x0e_venue_addressB\x10\n" +
	"\x0e_admin_contactB\x10\n" +
	"\x0e_currency_codeB\r\n" +
	"\v_start_dateB\v\n" +
	"\t_end_dateB\v\n" +
	"\t_owner_idB\f\n" +
	"\n" +
	"_venue_feeB\f\n" +
	"\n" +
	"_time_zoneB\x13\n" +
	"\x11_visibility_levelB\x10\n" +
	"\x0e_location_typeB\x1a\n" +
	"\x18_registration_start_dateB\x18\n" +
	"\x16_registration_end_date\"h\n" +
	"\vPageContent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05index\x18\x02 \x01(\x05R\x05index\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x1d\n" +
	"\n" +
	"content_md\x18\x04 \x01(\tR\tcontentMd\"\x91\x01\n" +
	"\x12MutablePageContent\x12\x19\n" +
	"\x05index\x18\x01 \x01(\x05H\x00R\x05index\x88\x01\x01\x12\x19\n" +
	"\x05title\x18\x02 \x01(\tH\x01R\x05title\x88\x01\x01\x12\"\n" +
	"\n" +
	"content_md\x18\x03 \x01(\tH\x02R\tcontentMd\x88\x01\x01B\b\n" +
	"\x06_indexB\b\n" +
	"\x06_titleB\r\n" +
	"\v_content_md\"\xe7\x01\n" +
	"\x16TournamentRegistration\x12#\n" +
	"\rtournament_id\x18\x01 \x01(\tR\ftournamentId\x12$\n" +
	"\x0epaid_venue_fee\x18\x03 \x01(\bR\fpaidVenueFee\x12R\n" +
	"\x13event_registrations\x18\x04 \x03(\v2!.parrygg.models.EventRegistrationR\x12eventRegistrations\x12(\n" +
	"\x04user\x18\x05 \x01(\v2\x14.parrygg.models.UserR\x04userJ\x04\b\x02\x10\x03\"\xc0\x01\n" +
	"\x1eTournamentRegistrationMutation\x12)\n" +
	"\x0epaid_venue_fee\x18\x01 \x01(\bH\x00R\fpaidVenueFee\x88\x01\x01\x12Z\n" +
	"\x13event_registrations\x18\x02 \x03(\v2).parrygg.models.EventRegistrationMutationR\x12eventRegistrationsB\x11\n" +
	"\x0f_paid_venue_feeJ\x04\b\x03\x10\x04\"\x92\x01\n" +
	"#BatchTournamentRegistrationMutation\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12R\n" +
	"\fregistration\x18\x02 \x01(\v2..parrygg.models.TournamentRegistrationMutationR\fregistration\"w\n" +
	"\x12TournamentAttendee\x12(\n" +
	"\x04user\x18\x01 \x01(\v2\x14.parrygg.models.UserR\x04user\x127\n" +
	"\x06events\x18\x02 \x03(\v2\x1f.parrygg.models.EventAttendanceR\x06events\"\xbc\x01\n" +
	"\x0fTournamentAdmin\x12*\n" +
	"\x04user\x18\x01 \x01(\v2\x14.parrygg.models.UserH\x00R\x04user\x12-\n" +
	"\x05group\x18\x02 \x01(\v2\x15.parrygg.models.GroupH\x00R\x05group\x12D\n" +
	"\n" +
	"permission\x18\x03 \x01(\x0e2$.parrygg.models.TournamentPermissionR\n" +
	"permissionB\b\n" +
	"\x06member\"a\n" +
	"\x14TournamentIdentifier\x12\x10\n" +
	"\x02id\x18\x01 \x01(\tH\x00R\x02id\x12)\n" +
	"\x0ftournament_slug\x18\x02 \x01(\tH\x00R\x0etournamentSlugB\f\n" +
	"\n" +
	"identifier\"z\n" +
	"\x1dTournamentPermissionsMetadata\x12Y\n" +
	"\x15tournament_permission\x18\x01 \x01(\x0e2$.parrygg.models.TournamentPermissionR\x14tournamentPermission*\xaf\x01\n" +
	"\x0fTournamentState\x12 \n" +
	"\x1cTOURNAMENT_STATE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18TOURNAMENT_STATE_PENDING\x10\x01\x12\x1a\n" +
	"\x16TOURNAMENT_STATE_READY\x10\x02\x12 \n" +
	"\x1cTOURNAMENT_STATE_IN_PROGRESS\x10\x03\x12\x1e\n" +
	"\x1aTOURNAMENT_STATE_COMPLETED\x10\x04*\x91\x01\n" +
	"\x14TournamentPermission\x12 \n" +
	"\x1cPERMISSION_LEVEL_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16PERMISSION_LEVEL_ADMIN\x10\x01\x12\x1c\n" +
	"\x18PERMISSION_LEVEL_MANAGER\x10\x02\x12\x1d\n" +
	"\x19PERMISSION_LEVEL_REPORTER\x10\x03*\x8d\x01\n" +
	"\x0fVisibilityLevel\x12 \n" +
	"\x1cVISIBILITY_LEVEL_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17VISIBILITY_LEVEL_PUBLIC\x10\x01\x12\x1e\n" +
	"\x1aVISIBILITY_LEVEL_LINK_ONLY\x10\x02\x12\x1b\n" +
	"\x17VISIBILITY_LEVEL_HIDDEN\x10\x03BA\n" +
	"\x14gg.parry.grpc.modelsP\x01Z'github.com/AaronLieb/octagon/parrygg/pbb\x06proto3"

var (
	file_models_tournament_proto_rawDescOnce sync.Once
	file_models_tournament_proto_rawDescData []byte
)

func file_models_tournament_proto_rawDescGZIP() []byte {
	file_models_tournament_proto_rawDescOnce.Do(func() {
		file_models_tournament_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_models_tournament_proto_rawDesc), len(file_models_tournament_proto_rawDesc)))
	})
	return file_models_tournament_proto_rawDescData
}

var file_models_tournament_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_models_tournament_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_models_tournament_proto_goTypes = []any{
	(TournamentState)(0),                        // 0: parrygg.models.TournamentState
	(TournamentPermission)(0),                   // 1: parrygg.models.TournamentPermission
	(VisibilityLevel)(0),                        // 2: parrygg.models.VisibilityLevel
	(*Tournament)(nil),                          // 3: parrygg.models.Tournament
	(*TournamentMutation)(nil),                  // 4: parrygg.models.TournamentMutation
	(*PageContent)(nil),                         // 5: parrygg.models.PageContent
	(*MutablePageContent)(nil),                  // 6: parrygg.models.MutablePageContent
	(*TournamentRegistration)(nil),              // 7: parrygg.models.TournamentRegistration
	(*TournamentRegistrationMutation)(nil),      // 8: parrygg.models.TournamentRegistrationMutation
	(*BatchTournamentRegistrationMutation)(nil), // 9: parrygg.models.BatchTournamentRegistrationMutation
	(*TournamentAttendee)(nil),                  // 10: parrygg.models.TournamentAttendee
	(*TournamentAdmin)(nil),                     // 11: parrygg.models.TournamentAdmin
	(*TournamentIdentifier)(nil),                // 12: parrygg.models.TournamentIdentifier
	(*TournamentPermissionsMetadata)(nil),       // 13: parrygg.models.TournamentPermissionsMetadata
	(*timestamppb.Timestamp)(nil),               // 14: google.protobuf.Timestamp
	(*Image)(nil),                               // 15: parrygg.models.Image
	(*Event)(nil),                               // 16: parrygg.models.Event
	(*Slug)(nil),                                // 17: parrygg.models.Slug
	(*Address)(nil),                             // 18: parrygg.models.Address
	(LocationType)(0),                           // 19: parrygg.models.LocationType
	(*EventRegistration)(nil),                   // 20: parrygg.models.EventRegistration
	(*User)(nil),                                // 21: parrygg.models.User
	(*EventRegistrationMutation)(nil),           // 22: parrygg.models.EventRegistrationMutation
	(*EventAttendance)(nil),                     // 23: parrygg.models.EventAttendance
	(*Group)(nil),                               // 24: parrygg.models.Group
}
var file_models_tournament_proto_depIdxs = []int32{
	14, // 0: parrygg.models.Tournament.start_date:type_name -> google.protobuf.Timestamp
	14, // 1: parrygg.models.Tournament.end_date:type_name -> google.protobuf.Timestamp
	0,  // 2: parrygg.models.Tournament.state:type_name -> parrygg.models.TournamentState
	15, // 3: parrygg.models.Tournament.images:type_name -> parrygg.models.Image
	16, // 4: parrygg.models.Tournament.events:type_name -> parrygg.models.Event
	17, // 5: parrygg.models.Tournament.slugs:type_name -> parrygg.models.Slug
	2,  // 6: parrygg.models.Tournament.visibility_level:type_name -> parrygg.models.VisibilityLevel
	18, // 7: parrygg.models.Tournament.address:type_name -> parrygg.models.Address
	19, // 8: parrygg.models.Tournament.location_type:type_name -> parrygg.models.LocationType
	14, // 9: parrygg.models.Tournament.registration_start_date:type_name -> google.protobuf.Timestamp
	14, // 10: parrygg.models.Tournament.registration_end_date:type_name -> google.protobuf.Timestamp
	14, // 11: parrygg.models.Tournament.created_at:type_name -> google.protobuf.Timestamp
	14, // 12: parrygg.models.Tournament.updated_at:type_name -> google.protobuf.Timestamp
	14, // 13: parrygg.models.TournamentMutation.start_date:type_name -> google.protobuf.Timestamp
	14, // 14: parrygg.models.TournamentMutation.end_date:type_name -> google.protobuf.Timestamp
	2,  // 15: parrygg.models.TournamentMutation.visibility_level:type_name -> parrygg.models.VisibilityLevel
	19, // 16: parrygg.models.TournamentMutation.location_type:type_name -> parrygg.models.LocationType
	14, // 17: parrygg.models.TournamentMutation.registration_start_date:type_name -> google.protobuf.Timestamp
	14, // 18: parrygg.models.TournamentMutation.registration_end_date:type_name -> google.protobuf.Timestamp
	20, // 19: parrygg.models.TournamentRegistration.event_registrations:type_name -> parrygg.models.EventRegistration
	21, // 20: parrygg.models.TournamentRegistration.user:type_name -> parrygg.models.User
	22, // 21: parrygg.models.TournamentRegistrationMutation.event_registrations:type_name -> parrygg.models.EventRegistrationMutation
	8,  // 22: parrygg.models.BatchTournamentRegistrationMutation.registration:type_name -> parrygg.models.TournamentRegistrationMutation
	21, // 23: parrygg.models.TournamentAttendee.user:type_name -> parrygg.models.User
	23, // 24: parrygg.models.TournamentAttendee.events:type_name -> parrygg.models.EventAttendance
	21, // 25: parrygg.models.TournamentAdmin.user:type_name -> parrygg.models.User
	24, // 26: parrygg.models.TournamentAdmin.group:type_name -> parrygg.models.Group
	1,  // 27: parrygg.models.TournamentAdmin.permission:type_name -> parrygg.models.TournamentPermission
	1,  // 28: parrygg.models.TournamentPermissionsMetadata.tournament_permission:type_name -> parrygg.models.TournamentPermission
	29, // [29:29] is the sub-list for method output_type
	29, // [29:29] is the sub-list for method input_type
	29, // [29:29] is the sub-list for extension type_name
	29, // [29:29] is the sub-list for extension extendee
	0,  // [0:29] is the sub-list for field type_name
}

func init() { file_models_tournament_proto_init() }
func file_models_tournament_proto_init() {
	if File_models_tournament_proto != nil {
		return
	}
	file_models_address_proto_init()
	file_models_image_proto_init()
	file_models_event_proto_init()
	file_models_group_proto_init()
	file_models_slug_proto_init()
	file_models_user_proto_init()
	file_models_tournament_proto_msgTypes[0].OneofWrappers = []any{}
	file_models_tournament_proto_msgTypes[1].OneofWrappers = []any{}
	file_models_tournament_proto_msgTypes[3].OneofWrappers = []any{}
	file_models_tournament_proto_msgTypes[5].OneofWrappers = []any{}
	file_models_tournament_proto_msgTypes[8].OneofWrappers = []any{
		(*TournamentAdmin_User)(nil),
		(*TournamentAdmin_Group)(nil),
	}
	file_models_tournament_proto_msgTypes[9].OneofWrappers = []any{
		(*TournamentIdentifier_Id)(nil),
		(*TournamentIdentifier_TournamentSlug)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_models_tournament_proto_rawDesc), len(file_models_tournament_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_models_tournament_proto_goTypes,
		DependencyIndexes: file_models_tournament_proto_depIdxs,
		EnumInfos:         file_models_tournament_proto_enumTypes,
		MessageInfos:      file_models_tournament_proto_msgTypes,
	}.Build()
	File_models_tournament_proto = out.File
	file_models_tournament_proto_goTypes = nil
	file_models_tournament_proto_depIdxs = nil
}
