// User profile and account management.
// Handles user identity, profile information, and associated visual assets.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: models/user.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Supported OAuth providers for account linking
type LinkedAccountProvider int32

const (
	LinkedAccountProvider_LINKED_ACCOUNT_PROVIDER_UNSPECIFIED LinkedAccountProvider = 0
	LinkedAccountProvider_LINKED_ACCOUNT_PROVIDER_DISCORD     LinkedAccountProvider = 1
	LinkedAccountProvider_LINKED_ACCOUNT_PROVIDER_STARTGG     LinkedAccountProvider = 2
)

// Enum value maps for LinkedAccountProvider.
var (
	LinkedAccountProvider_name = map[int32]string{
		0: "LINKED_ACCOUNT_PROVIDER_UNSPECIFIED",
		1: "LINKED_ACCOUNT_PROVIDER_DISCORD",
		2: "LINKED_ACCOUNT_PROVIDER_STARTGG",
	}
	LinkedAccountProvider_value = map[string]int32{
		"LINKED_ACCOUNT_PROVIDER_UNSPECIFIED": 0,
		"LINKED_ACCOUNT_PROVIDER_DISCORD":     1,
		"LINKED_ACCOUNT_PROVIDER_STARTGG":     2,
	}
)

func (x LinkedAccountProvider) Enum() *LinkedAccountProvider {
	p := new(LinkedAccountProvider)
	*p = x
	return p
}

func (x LinkedAccountProvider) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LinkedAccountProvider) Descriptor() protoreflect.EnumDescriptor {
	return file_models_user_proto_enumTypes[0].Descriptor()
}

func (LinkedAccountProvider) Type() protoreflect.EnumType {
	return &file_models_user_proto_enumTypes[0]
}

func (x LinkedAccountProvider) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LinkedAccountProvider.Descriptor instead.
func (LinkedAccountProvider) EnumDescriptor() ([]byte, []int) {
	return file_models_user_proto_rawDescGZIP(), []int{0}
}

type IdentityActionType int32

const (
	IdentityActionType_IDENTITY_ACTION_TYPE_UNSPECIFIED IdentityActionType = 0
	IdentityActionType_IDENTITY_ACTION_TYPE_LINK        IdentityActionType = 1
	IdentityActionType_IDENTITY_ACTION_TYPE_UNLINK      IdentityActionType = 2
	IdentityActionType_IDENTITY_ACTION_TYPE_MERGE       IdentityActionType = 3
)

// Enum value maps for IdentityActionType.
var (
	IdentityActionType_name = map[int32]string{
		0: "IDENTITY_ACTION_TYPE_UNSPECIFIED",
		1: "IDENTITY_ACTION_TYPE_LINK",
		2: "IDENTITY_ACTION_TYPE_UNLINK",
		3: "IDENTITY_ACTION_TYPE_MERGE",
	}
	IdentityActionType_value = map[string]int32{
		"IDENTITY_ACTION_TYPE_UNSPECIFIED": 0,
		"IDENTITY_ACTION_TYPE_LINK":        1,
		"IDENTITY_ACTION_TYPE_UNLINK":      2,
		"IDENTITY_ACTION_TYPE_MERGE":       3,
	}
)

func (x IdentityActionType) Enum() *IdentityActionType {
	p := new(IdentityActionType)
	*p = x
	return p
}

func (x IdentityActionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IdentityActionType) Descriptor() protoreflect.EnumDescriptor {
	return file_models_user_proto_enumTypes[1].Descriptor()
}

func (IdentityActionType) Type() protoreflect.EnumType {
	return &file_models_user_proto_enumTypes[1]
}

func (x IdentityActionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IdentityActionType.Descriptor instead.
func (IdentityActionType) EnumDescriptor() ([]byte, []int) {
	return file_models_user_proto_rawDescGZIP(), []int{1}
}

// User represents a platform user account with profile information.
// Contains identity, contact, and personalization details.
// Next id: 15
type User struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier for the user (UUID v7).
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Public gaming handle/username.
	GamerTag string `protobuf:"bytes,2,opt,name=gamer_tag,json=gamerTag,proto3" json:"gamer_tag,omitempty"`
	// User's first name.
	FirstName string `protobuf:"bytes,3,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	// User's last name.
	LastName string `protobuf:"bytes,4,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	// Markdown-formatted biography/description.
	BioMd string `protobuf:"bytes,5,opt,name=bio_md,json=bioMd,proto3" json:"bio_md,omitempty"`
	// Preferred pronouns (e.g., "they/them").
	Pronouns string `protobuf:"bytes,6,opt,name=pronouns,proto3" json:"pronouns,omitempty"`
	// URL to user's avatar image.
	AvatarUrl string `protobuf:"bytes,7,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	// Hex color code for profile banner.
	BannerColor string `protobuf:"bytes,8,opt,name=banner_color,json=bannerColor,proto3" json:"banner_color,omitempty"`
	// Country of residence.
	LocationCountry string `protobuf:"bytes,9,opt,name=location_country,json=locationCountry,proto3" json:"location_country,omitempty"`
	// State/province of residence.
	LocationState string `protobuf:"bytes,10,opt,name=location_state,json=locationState,proto3" json:"location_state,omitempty"`
	// City of residence.
	LocationCity string `protobuf:"bytes,11,opt,name=location_city,json=locationCity,proto3" json:"location_city,omitempty"`
	// Profile images (avatars, banners, etc.).
	Images []*Image `protobuf:"bytes,12,rep,name=images,proto3" json:"images,omitempty"`
	// Whether this user is anonymous (not connected to a real account)
	IsAnonymous bool `protobuf:"varint,13,opt,name=is_anonymous,json=isAnonymous,proto3" json:"is_anonymous,omitempty"`
	// Linked external accounts (Discord, start.gg, etc.).
	LinkedAccounts []*LinkedAccount `protobuf:"bytes,14,rep,name=linked_accounts,json=linkedAccounts,proto3" json:"linked_accounts,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_models_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_models_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_models_user_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetGamerTag() string {
	if x != nil {
		return x.GamerTag
	}
	return ""
}

func (x *User) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *User) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *User) GetBioMd() string {
	if x != nil {
		return x.BioMd
	}
	return ""
}

func (x *User) GetPronouns() string {
	if x != nil {
		return x.Pronouns
	}
	return ""
}

func (x *User) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *User) GetBannerColor() string {
	if x != nil {
		return x.BannerColor
	}
	return ""
}

func (x *User) GetLocationCountry() string {
	if x != nil {
		return x.LocationCountry
	}
	return ""
}

func (x *User) GetLocationState() string {
	if x != nil {
		return x.LocationState
	}
	return ""
}

func (x *User) GetLocationCity() string {
	if x != nil {
		return x.LocationCity
	}
	return ""
}

func (x *User) GetImages() []*Image {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *User) GetIsAnonymous() bool {
	if x != nil {
		return x.IsAnonymous
	}
	return false
}

func (x *User) GetLinkedAccounts() []*LinkedAccount {
	if x != nil {
		return x.LinkedAccounts
	}
	return nil
}

// MutableUser updates editable fields of a user profile.
// Subset of User with fields that may be mutated by a request.
// Next id: 11
type MutableUser struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Updated gamer tag.
	GamerTag *string `protobuf:"bytes,1,opt,name=gamer_tag,json=gamerTag,proto3,oneof" json:"gamer_tag,omitempty"`
	// Updated first name.
	FirstName *string `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3,oneof" json:"first_name,omitempty"`
	// Updated last name.
	LastName *string `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3,oneof" json:"last_name,omitempty"`
	// Updated bio in markdown format.
	BioMd *string `protobuf:"bytes,4,opt,name=bio_md,json=bioMd,proto3,oneof" json:"bio_md,omitempty"`
	// Updated pronouns.
	Pronouns *string `protobuf:"bytes,5,opt,name=pronouns,proto3,oneof" json:"pronouns,omitempty"`
	// Updated avatar image ID.
	AvatarImageId *string `protobuf:"bytes,6,opt,name=avatar_image_id,json=avatarImageId,proto3,oneof" json:"avatar_image_id,omitempty"`
	// Updated banner color.
	BannerColor *string `protobuf:"bytes,7,opt,name=banner_color,json=bannerColor,proto3,oneof" json:"banner_color,omitempty"`
	// Updated country.
	LocationCountry *string `protobuf:"bytes,8,opt,name=location_country,json=locationCountry,proto3,oneof" json:"location_country,omitempty"`
	// Updated state/province.
	LocationState *string `protobuf:"bytes,9,opt,name=location_state,json=locationState,proto3,oneof" json:"location_state,omitempty"`
	// Updated city.
	LocationCity  *string `protobuf:"bytes,10,opt,name=location_city,json=locationCity,proto3,oneof" json:"location_city,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MutableUser) Reset() {
	*x = MutableUser{}
	mi := &file_models_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MutableUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MutableUser) ProtoMessage() {}

func (x *MutableUser) ProtoReflect() protoreflect.Message {
	mi := &file_models_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MutableUser.ProtoReflect.Descriptor instead.
func (*MutableUser) Descriptor() ([]byte, []int) {
	return file_models_user_proto_rawDescGZIP(), []int{1}
}

func (x *MutableUser) GetGamerTag() string {
	if x != nil && x.GamerTag != nil {
		return *x.GamerTag
	}
	return ""
}

func (x *MutableUser) GetFirstName() string {
	if x != nil && x.FirstName != nil {
		return *x.FirstName
	}
	return ""
}

func (x *MutableUser) GetLastName() string {
	if x != nil && x.LastName != nil {
		return *x.LastName
	}
	return ""
}

func (x *MutableUser) GetBioMd() string {
	if x != nil && x.BioMd != nil {
		return *x.BioMd
	}
	return ""
}

func (x *MutableUser) GetPronouns() string {
	if x != nil && x.Pronouns != nil {
		return *x.Pronouns
	}
	return ""
}

func (x *MutableUser) GetAvatarImageId() string {
	if x != nil && x.AvatarImageId != nil {
		return *x.AvatarImageId
	}
	return ""
}

func (x *MutableUser) GetBannerColor() string {
	if x != nil && x.BannerColor != nil {
		return *x.BannerColor
	}
	return ""
}

func (x *MutableUser) GetLocationCountry() string {
	if x != nil && x.LocationCountry != nil {
		return *x.LocationCountry
	}
	return ""
}

func (x *MutableUser) GetLocationState() string {
	if x != nil && x.LocationState != nil {
		return *x.LocationState
	}
	return ""
}

func (x *MutableUser) GetLocationCity() string {
	if x != nil && x.LocationCity != nil {
		return *x.LocationCity
	}
	return ""
}

// LinkedAccount represents an external account linked to a user.
// Contains information about connected third-party services.
// Next id: 5
type LinkedAccount struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Provider (e.g., LINKED_ACCOUNT_PROVIDER_DISCORD, LINKED_ACCOUNT_PROVIDER_STARTGG).
	Provider LinkedAccountProvider `protobuf:"varint,1,opt,name=provider,proto3,enum=parrygg.models.LinkedAccountProvider" json:"provider,omitempty"`
	// User ID on the external provider.
	UserId string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Username on the external provider.
	Username string `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	// URL slug for the provider profile (e.g., start.gg slug).
	Slug          string `protobuf:"bytes,4,opt,name=slug,proto3" json:"slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LinkedAccount) Reset() {
	*x = LinkedAccount{}
	mi := &file_models_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinkedAccount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkedAccount) ProtoMessage() {}

func (x *LinkedAccount) ProtoReflect() protoreflect.Message {
	mi := &file_models_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkedAccount.ProtoReflect.Descriptor instead.
func (*LinkedAccount) Descriptor() ([]byte, []int) {
	return file_models_user_proto_rawDescGZIP(), []int{2}
}

func (x *LinkedAccount) GetProvider() LinkedAccountProvider {
	if x != nil {
		return x.Provider
	}
	return LinkedAccountProvider_LINKED_ACCOUNT_PROVIDER_UNSPECIFIED
}

func (x *LinkedAccount) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *LinkedAccount) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LinkedAccount) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

type LinkAccountAction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LinkedAccount *LinkedAccount         `protobuf:"bytes,1,opt,name=linked_account,json=linkedAccount,proto3" json:"linked_account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LinkAccountAction) Reset() {
	*x = LinkAccountAction{}
	mi := &file_models_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinkAccountAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkAccountAction) ProtoMessage() {}

func (x *LinkAccountAction) ProtoReflect() protoreflect.Message {
	mi := &file_models_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkAccountAction.ProtoReflect.Descriptor instead.
func (*LinkAccountAction) Descriptor() ([]byte, []int) {
	return file_models_user_proto_rawDescGZIP(), []int{3}
}

func (x *LinkAccountAction) GetLinkedAccount() *LinkedAccount {
	if x != nil {
		return x.LinkedAccount
	}
	return nil
}

type UnlinkAccountAction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      LinkedAccountProvider  `protobuf:"varint,1,opt,name=provider,proto3,enum=parrygg.models.LinkedAccountProvider" json:"provider,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlinkAccountAction) Reset() {
	*x = UnlinkAccountAction{}
	mi := &file_models_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlinkAccountAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlinkAccountAction) ProtoMessage() {}

func (x *UnlinkAccountAction) ProtoReflect() protoreflect.Message {
	mi := &file_models_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlinkAccountAction.ProtoReflect.Descriptor instead.
func (*UnlinkAccountAction) Descriptor() ([]byte, []int) {
	return file_models_user_proto_rawDescGZIP(), []int{4}
}

func (x *UnlinkAccountAction) GetProvider() LinkedAccountProvider {
	if x != nil {
		return x.Provider
	}
	return LinkedAccountProvider_LINKED_ACCOUNT_PROVIDER_UNSPECIFIED
}

// MergeUserAction represents information about the merging of a prior parry.gg User into a still-existing User.
type MergeUserAction struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The prior user which was merged into the user in question.
	FromUserId    string `protobuf:"bytes,1,opt,name=from_user_id,json=fromUserId,proto3" json:"from_user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MergeUserAction) Reset() {
	*x = MergeUserAction{}
	mi := &file_models_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MergeUserAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MergeUserAction) ProtoMessage() {}

func (x *MergeUserAction) ProtoReflect() protoreflect.Message {
	mi := &file_models_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MergeUserAction.ProtoReflect.Descriptor instead.
func (*MergeUserAction) Descriptor() ([]byte, []int) {
	return file_models_user_proto_rawDescGZIP(), []int{5}
}

func (x *MergeUserAction) GetFromUserId() string {
	if x != nil {
		return x.FromUserId
	}
	return ""
}

// IdentityAction represents a past action taken affecting a user's identity.
type IdentityAction struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier for this action (UUID v7).
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The id of the affected user.
	UserId string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Time at which this action occurred.
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Type-specific action data.
	//
	// Types that are valid to be assigned to Type:
	//
	//	*IdentityAction_LinkAccountAction
	//	*IdentityAction_UnlinkAccountAction
	//	*IdentityAction_MergeUserAction
	Type          isIdentityAction_Type `protobuf_oneof:"type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdentityAction) Reset() {
	*x = IdentityAction{}
	mi := &file_models_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentityAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentityAction) ProtoMessage() {}

func (x *IdentityAction) ProtoReflect() protoreflect.Message {
	mi := &file_models_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentityAction.ProtoReflect.Descriptor instead.
func (*IdentityAction) Descriptor() ([]byte, []int) {
	return file_models_user_proto_rawDescGZIP(), []int{6}
}

func (x *IdentityAction) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *IdentityAction) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *IdentityAction) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *IdentityAction) GetType() isIdentityAction_Type {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *IdentityAction) GetLinkAccountAction() *LinkAccountAction {
	if x != nil {
		if x, ok := x.Type.(*IdentityAction_LinkAccountAction); ok {
			return x.LinkAccountAction
		}
	}
	return nil
}

func (x *IdentityAction) GetUnlinkAccountAction() *UnlinkAccountAction {
	if x != nil {
		if x, ok := x.Type.(*IdentityAction_UnlinkAccountAction); ok {
			return x.UnlinkAccountAction
		}
	}
	return nil
}

func (x *IdentityAction) GetMergeUserAction() *MergeUserAction {
	if x != nil {
		if x, ok := x.Type.(*IdentityAction_MergeUserAction); ok {
			return x.MergeUserAction
		}
	}
	return nil
}

type isIdentityAction_Type interface {
	isIdentityAction_Type()
}

type IdentityAction_LinkAccountAction struct {
	// Linking an external account.
	LinkAccountAction *LinkAccountAction `protobuf:"bytes,4,opt,name=link_account_action,json=linkAccountAction,proto3,oneof"`
}

type IdentityAction_UnlinkAccountAction struct {
	// Unlinking an external account.
	UnlinkAccountAction *UnlinkAccountAction `protobuf:"bytes,5,opt,name=unlink_account_action,json=unlinkAccountAction,proto3,oneof"`
}

type IdentityAction_MergeUserAction struct {
	// Merging a parry.gg user.
	MergeUserAction *MergeUserAction `protobuf:"bytes,6,opt,name=merge_user_action,json=mergeUserAction,proto3,oneof"`
}

func (*IdentityAction_LinkAccountAction) isIdentityAction_Type() {}

func (*IdentityAction_UnlinkAccountAction) isIdentityAction_Type() {}

func (*IdentityAction_MergeUserAction) isIdentityAction_Type() {}

var File_models_user_proto protoreflect.FileDescriptor

const file_models_user_proto_rawDesc = "" +
	"\n" +
	"\x11models/user.proto\x12\x0eparrygg.models\x1a\x12models/image.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf5\x03\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tgamer_tag\x18\x02 \x01(\tR\bgamerTag\x12\x1d\n" +
	"\n" +
	"first_name\x18\x03 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x04 \x01(\tR\blastName\x12\x15\n" +
	"\x06bio_md\x18\x05 \x01(\tR\x05bioMd\x12\x1a\n" +
	"\bpronouns\x18\x06 \x01(\tR\bpronouns\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\a \x01(\tR\tavatarUrl\x12!\n" +
	"\fbanner_color\x18\b \x01(\tR\vbannerColor\x12)\n" +
	"\x10location_country\x18\t \x01(\tR\x0flocationCountry\x12%\n" +
	"\x0elocation_state\x18\n" +
	" \x01(\tR\rlocationState\x12#\n" +
	"\rlocation_city\x18\v \x01(\tR\flocationCity\x12-\n" +
	"\x06images\x18\f \x03(\v2\x15.parrygg.models.ImageR\x06images\x12!\n" +
	"\fis_anonymous\x18\r \x01(\bR\visAnonymous\x12F\n" +
	"\x0flinked_accounts\x18\x0e \x03(\v2\x1d.parrygg.models.LinkedAccountR\x0elinkedAccounts\"\xaf\x04\n" +
	"\vMutableUser\x12 \n" +
	"\tgamer_tag\x18\x01 \x01(\tH\x00R\bgamerTag\x88\x01\x01\x12\"\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tH\x01R\tfirstName\x88\x01\x01\x12 \n" +
	"\tlast_name\x18\x03 \x01(\tH\x02R\blastName\x88\x01\x01\x12\x1a\n" +
	"\x06bio_md\x18\x04 \x01(\tH\x03R\x05bioMd\x88\x01\x01\x12\x1f\n" +
	"\bpronouns\x18\x05 \x01(\tH\x04R\bpronouns\x88\x01\x01\x12+\n" +
	"\x0favatar_image_id\x18\x06 \x01(\tH\x05R\ravatarImageId\x88\x01\x01\x12&\n" +
	"\fbanner_color\x18\a \x01(\tH\x06R\vbannerColor\x88\x01\x01\x12.\n" +
	"\x10location_country\x18\b \x01(\tH\aR\x0flocationCountry\x88\x01\x01\x12*\n" +
	"\x0elocation_state\x18\t \x01(\tH\bR\rlocationState\x88\x01\x01\x12(\n" +
	"\rlocation_city\x18\n" +
	" \x01(\tH\tR\flocationCity\x88\x01\x01B\f\n" +
	"\n" +
	"_gamer_tagB\r\n" +
	"\v_first_nameB\f\n" +
	"\n" +
	"_last_nameB\t\n" +
	"\a_bio_mdB\v\n" +
	"\t_pronounsB\x12\n" +
	"\x10_avatar_image_idB\x0f\n" +
	"\r_banner_colorB\x13\n" +
	"\x11_location_countryB\x11\n" +
	"\x0f_location_stateB\x10\n" +
	"\x0e_location_city\"\x9b\x01\n" +
	"\rLinkedAccount\x12A\n" +
	"\bprovider\x18\x01 \x01(\x0e2%.parrygg.models.LinkedAccountProviderR\bprovider\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x12\n" +
	"\x04slug\x18\x04 \x01(\tR\x04slug\"Y\n" +
	"\x11LinkAccountAction\x12D\n" +
	"\x0elinked_account\x18\x01 \x01(\v2\x1d.parrygg.models.LinkedAccountR\rlinkedAccount\"X\n" +
	"\x13UnlinkAccountAction\x12A\n" +
	"\bprovider\x18\x01 \x01(\x0e2%.parrygg.models.LinkedAccountProviderR\bprovider\"3\n" +
	"\x0fMergeUserAction\x12 \n" +
	"\ffrom_user_id\x18\x01 \x01(\tR\n" +
	"fromUserId\"\xfb\x02\n" +
	"\x0eIdentityAction\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12S\n" +
	"\x13link_account_action\x18\x04 \x01(\v2!.parrygg.models.LinkAccountActionH\x00R\x11linkAccountAction\x12Y\n" +
	"\x15unlink_account_action\x18\x05 \x01(\v2#.parrygg.models.UnlinkAccountActionH\x00R\x13unlinkAccountAction\x12M\n" +
	"\x11merge_user_action\x18\x06 \x01(\v2\x1f.parrygg.models.MergeUserActionH\x00R\x0fmergeUserActionB\x06\n" +
	"\x04type*\x8a\x01\n" +
	"\x15LinkedAccountProvider\x12'\n" +
	"#LINKED_ACCOUNT_PROVIDER_UNSPECIFIED\x10\x00\x12#\n" +
	"\x1fLINKED_ACCOUNT_PROVIDER_DISCORD\x10\x01\x12#\n" +
	"\x1fLINKED_ACCOUNT_PROVIDER_STARTGG\x10\x02*\x9a\x01\n" +
	"\x12IdentityActionType\x12$\n" +
	" IDENTITY_ACTION_TYPE_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19IDENTITY_ACTION_TYPE_LINK\x10\x01\x12\x1f\n" +
	"\x1bIDENTITY_ACTION_TYPE_UNLINK\x10\x02\x12\x1e\n" +
	"\x1aIDENTITY_ACTION_TYPE_MERGE\x10\x03BA\n" +
	"\x14gg.parry.grpc.modelsP\x01Z'github.com/AaronLieb/octagon/parrygg/pbb\x06proto3"

var (
	file_models_user_proto_rawDescOnce sync.Once
	file_models_user_proto_rawDescData []byte
)

func file_models_user_proto_rawDescGZIP() []byte {
	file_models_user_proto_rawDescOnce.Do(func() {
		file_models_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_models_user_proto_rawDesc), len(file_models_user_proto_rawDesc)))
	})
	return file_models_user_proto_rawDescData
}

var file_models_user_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_models_user_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_models_user_proto_goTypes = []any{
	(LinkedAccountProvider)(0),    // 0: parrygg.models.LinkedAccountProvider
	(IdentityActionType)(0),       // 1: parrygg.models.IdentityActionType
	(*User)(nil),                  // 2: parrygg.models.User
	(*MutableUser)(nil),           // 3: parrygg.models.MutableUser
	(*LinkedAccount)(nil),         // 4: parrygg.models.LinkedAccount
	(*LinkAccountAction)(nil),     // 5: parrygg.models.LinkAccountAction
	(*UnlinkAccountAction)(nil),   // 6: parrygg.models.UnlinkAccountAction
	(*MergeUserAction)(nil),       // 7: parrygg.models.MergeUserAction
	(*IdentityAction)(nil),        // 8: parrygg.models.IdentityAction
	(*Image)(nil),                 // 9: parrygg.models.Image
	(*timestamppb.Timestamp)(nil), // 10: google.protobuf.Timestamp
}
var file_models_user_proto_depIdxs = []int32{
	9,  // 0: parrygg.models.User.images:type_name -> parrygg.models.Image
	4,  // 1: parrygg.models.User.linked_accounts:type_name -> parrygg.models.LinkedAccount
	0,  // 2: parrygg.models.LinkedAccount.provider:type_name -> parrygg.models.LinkedAccountProvider
	4,  // 3: parrygg.models.LinkAccountAction.linked_account:type_name -> parrygg.models.LinkedAccount
	0,  // 4: parrygg.models.UnlinkAccountAction.provider:type_name -> parrygg.models.LinkedAccountProvider
	10, // 5: parrygg.models.IdentityAction.created_at:type_name -> google.protobuf.Timestamp
	5,  // 6: parrygg.models.IdentityAction.link_account_action:type_name -> parrygg.models.LinkAccountAction
	6,  // 7: parrygg.models.IdentityAction.unlink_account_action:type_name -> parrygg.models.UnlinkAccountAction
	7,  // 8: parrygg.models.IdentityAction.merge_user_action:type_name -> parrygg.models.MergeUserAction
	9,  // [9:9] is the sub-list for method output_type
	9,  // [9:9] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_models_user_proto_init() }
func file_models_user_proto_init() {
	if File_models_user_proto != nil {
		return
	}
	file_models_image_proto_init()
	file_models_user_proto_msgTypes[1].OneofWrappers = []any{}
	file_models_user_proto_msgTypes[6].OneofWrappers = []any{
		(*IdentityAction_LinkAccountAction)(nil),
		(*IdentityAction_UnlinkAccountAction)(nil),
		(*IdentityAction_MergeUserAction)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_models_user_proto_rawDesc), len(file_models_user_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_models_user_proto_goTypes,
		DependencyIndexes: file_models_user_proto_depIdxs,
		EnumInfos:         file_models_user_proto_enumTypes,
		MessageInfos:      file_models_user_proto_msgTypes,
	}.Build()
	File_models_user_proto = out.File
	file_models_user_proto_goTypes = nil
	file_models_user_proto_depIdxs = nil
}
